### ISSUE TITLE
spring-websocket: Detected an instance of Random/SplittableRandom

### ISSUE THREAD

**Issue by ivangfr** [spring-projects-experimental/spring-native#1034]
Hi, I have this project [`springboot-rsocket-webflux-aop`](https://github.com/ivangfr/springboot-rsocket-webflux-aop) and one of its applications called `movie-client-ui` uses `spring-websocket`.

I've tried to add `spring-native` to the app. However, when building the Docker native image, I'm getting the following exception
```
[INFO]     [creator]     Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected.  To see how this object got instantiated use --trace-object-instantiation=java.util.Random. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
[INFO]     [creator]     Detailed message:
[INFO]     [creator]     Trace:
[INFO]     [creator]      at parsing org.springframework.web.socket.sockjs.support.AbstractSockJsService.access$200(AbstractSockJsService.java:68)
[INFO]     [creator]     Call path from entry point to org.springframework.web.socket.sockjs.support.AbstractSockJsService$InfoHandler.handle(ServerHttpRequest, ServerHttpResponse):
[INFO]     [creator]      at org.springframework.web.socket.sockjs.support.AbstractSockJsService$InfoHandler.handle(AbstractSockJsService.java:590)
[INFO]     [creator]      at org.springframework.web.socket.sockjs.support.AbstractSockJsService.handleRequest(AbstractSockJsService.java:413)
[INFO]     [creator]      at org.springframework.web.socket.sockjs.support.SockJsHttpRequestHandler.handleRequest(SockJsHttpRequestHandler.java:134)
[INFO]     [creator]      at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:52)
[INFO]     [creator]      at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1064)
[INFO]     [creator]      at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
[INFO]     [creator]      at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
[INFO]     [creator]      at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:880)
[INFO]     [creator]      at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
[INFO]     [creator]      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
[INFO]     [creator]      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
[INFO]     [creator]      at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:711)
[INFO]     [creator]      at org.apache.catalina.core.ApplicationDispatcher.doDispatch(ApplicationDispatcher.java:632)
[INFO]     [creator]      at org.apache.catalina.core.ApplicationDispatcher.dispatch(ApplicationDispatcher.java:600)
[INFO]     [creator]      at org.apache.catalina.core.AsyncContextImpl$AsyncRunnable.run(AsyncContextImpl.java:587)
[INFO]     [creator]      at java.lang.Shutdown.runHooks(Shutdown.java:130)
[INFO]     [creator]      at java.lang.Shutdown.shutdown(Shutdown.java:186)
[INFO]     [creator]      at com.oracle.svm.core.jdk.RuntimeSupport.shutdown(RuntimeSupport.java:132)
[INFO]     [creator]      at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
```

**How to reproduce**

- git clone https://github.com/ivangfr/springboot-rsocket-webflux-aop.git
- cd springboot-rsocket-webflux-aop
- git checkout add-spring-native
- ./mvnw clean spring-boot:build-image --projects movie-client-ui -DskipTests

I'm using

- spring-boot 2.5.4
- spring-native 0.10.3

**Comment by sdeleuze** [comment]
Could you please try `--trace-object-instantiation=org.springframework.web.socket.sockjs.support.AbstractSockJsService` to understand why it is initialized at build time?

**Comment by ivangfr** [comment]
Hi @sdeleuze , thanks for the response.

I've added the line you suggested in the `NativeHint.options`. Besides, I've added `--trace-object-instantiation=java.util.Random` as the error message suggests.

So, my application class looks like
```
@NativeHint(
        options = {
                "--trace-object-instantiation=org.springframework.web.socket.sockjs.support.AbstractSockJsService",
                "--trace-object-instantiation=java.util.Random"
        })
@SpringBootApplication
public class MovieClientUiApplication {
...
```

Now, the error message says (P.S. I've **highlighted** the difference from the previous message):

_"Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected.  **Object has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked**. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point."_

Thanks!
