### ISSUE TITLE
Hateoas compatibility issue for DTOs decorated with `@Relation`

### ISSUE THREAD

**Issue by ch4mpy** [spring-projects-experimental/spring-native#1037]
I have some DTOs annoated with `org.springframework.hateoas.server.core.Relation` to force `collectionRelation` (otherwise HATOEAS HAL payload and springdoc-openapi genereated spec diverge).

Native image is build successfully but, at runtime, I get:
```
2021-09-16 20:20:06.707  INFO 1 --- [           main] p.c.r.web.RimaWebEndpointsApplication    : Started RimaWebEndpointsApplication in 0.376 seconds (JVM running for 0.378)
2021-09-16 20:20:20.881  WARN 1 --- [nio-8443-exec-1] o.a.tomcat.util.buf.ByteBufferUtils      : Cannot use direct ByteBuffer cleaner, memory leaking may occur

java.lang.NoSuchMethodException: java.nio.DirectByteBuffer.cleaner()
        at java.lang.Class.getMethod(DynamicHub.java:1120) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.apache.tomcat.util.buf.ByteBufferUtils.<clinit>(ByteBufferUtils.java:62) ~[na:na]
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375) [pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295) [pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.apache.tomcat.util.net.SocketBufferHandler.expand(SocketBufferHandler.java:222) [pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.apache.tomcat.util.net.SecureNioChannel.processSNI(SecureNioChannel.java:320) [pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.apache.tomcat.util.net.SecureNioChannel.handshake(SecureNioChannel.java:154) [pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1702) [pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at java.lang.Thread.run(Thread.java:748) [pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:567) [pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192) [pf.cps.rima.web.RimaWebEndpointsApplication:na]

2021-09-16 20:20:20.917  INFO 1 --- [nio-8443-exec-7] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2021-09-16 20:20:20.917  INFO 1 --- [nio-8443-exec-7] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2021-09-16 20:20:20.918  INFO 1 --- [nio-8443-exec-7] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
2021-09-16 20:20:20.957  INFO 1 --- [nio-8443-exec-7] o.s.aop.framework.BuildTimeAopProxy      : Attempting discovery (load) of build time generated proxy for class: pf.cps.rima.web.endpoints.ProfessionnelsSanteController
2021-09-16 20:20:20.958  INFO 1 --- [nio-8443-exec-7] o.s.aop.framework.BuildTimeAopProxy      : Suitable proxy found with name pf.cps.rima.web.endpoints.ProfessionnelsSanteController$$SpringProxy$e6c1b67c
2021-09-16 20:20:20.958  INFO 1 --- [nio-8443-exec-7] o.s.aop.framework.BuildTimeAopProxy      : Attempting discovery (load) of build time generated proxy for class: org.springframework.hateoas.PagedModel
2021-09-16 20:20:20.958  INFO 1 --- [nio-8443-exec-7] o.s.aop.framework.BuildTimeAopProxy      : Suitable proxy found with name org.springframework.hateoas.PagedModel$$SpringProxy$fa4acd98
2021-09-16 20:20:20.959  INFO 1 --- [nio-8443-exec-7] o.s.aop.framework.BuildTimeAopProxy      : Attempting discovery (load) of build time generated proxy for class: org.springframework.hateoas.EntityModel
2021-09-16 20:20:20.959  INFO 1 --- [nio-8443-exec-7] o.s.aop.framework.BuildTimeAopProxy      : Suitable proxy found with name org.springframework.hateoas.EntityModel$$SpringProxy$ac6a4c76
2021-09-16 20:20:20.973 ERROR 1 --- [nio-8443-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is com.oracle.svm.core.jdk.UnsupportedFeatureError: Proxy class defined by interfaces [interface org.springframework.hateoas.server.core.Relation, interface org.springframework.core.annotation.SynthesizedAnnotation] not found. Generating proxy classes at runtime is not supported. Proxy classes need to be defined at image build time by specifying the list of interfaces that they implement. To define proxy classes use -H:DynamicProxyConfigurationFiles=<comma-separated-config-files> and -H:DynamicProxyConfigurationResources=<comma-separated-config-resources> options.] with root cause

com.oracle.svm.core.jdk.UnsupportedFeatureError: Proxy class defined by interfaces [interface org.springframework.hateoas.server.core.Relation, interface org.springframework.core.annotation.SynthesizedAnnotation] not found. Generating proxy classes at runtime is not supported. Proxy classes need to be defined at image build time by specifying the list of interfaces that they implement. To define proxy classes use -H:DynamicProxyConfigurationFiles=<comma-separated-config-files> and -H:DynamicProxyConfigurationResources=<comma-separated-config-resources> options.
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:88) ~[na:na]
        at com.oracle.svm.reflect.proxy.DynamicProxySupport.getProxyClass(DynamicProxySupport.java:113) ~[na:na]
        at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:54) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.springframework.core.annotation.SynthesizedMergedAnnotationInvocationHandler.createProxy(SynthesizedMergedAnnotationInvocationHandler.java:271) ~[na:na]
        at org.springframework.core.annotation.TypeMappedAnnotation.createSynthesized(TypeMappedAnnotation.java:335) ~[na:na]
        at org.springframework.core.annotation.AbstractMergedAnnotation.synthesize(AbstractMergedAnnotation.java:210) ~[na:na]
        at org.springframework.core.annotation.AbstractMergedAnnotation.synthesize(AbstractMergedAnnotation.java:200) ~[na:na]
        at org.springframework.core.annotation.AnnotatedElementUtils.getMergedAnnotation(AnnotatedElementUtils.java:339) ~[na:na]
        at org.springframework.hateoas.server.core.AnnotationLinkRelationProvider.lambda$lookupAnnotation$0(AnnotationLinkRelationProvider.java:108) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:324) ~[na:na]
        at org.springframework.hateoas.server.core.AnnotationLinkRelationProvider.lookupAnnotation(AnnotationLinkRelationProvider.java:108) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.springframework.hateoas.server.core.AnnotationLinkRelationProvider.supports(AnnotationLinkRelationProvider.java:89) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.springframework.hateoas.server.core.AnnotationLinkRelationProvider.supports(AnnotationLinkRelationProvider.java:35) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.springframework.plugin.core.SimplePluginRegistry.lambda$getPluginFor$0(SimplePluginRegistry.java:113) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[na:na]
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1361) ~[na:na]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[na:na]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) ~[na:na]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) ~[na:na]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:na]
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[na:na]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531) ~[na:na]
        at org.springframework.plugin.core.SimplePluginRegistry.getPluginFor(SimplePluginRegistry.java:114) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.springframework.plugin.core.SimplePluginRegistry.getPluginFor(SimplePluginRegistry.java:167) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.springframework.plugin.core.SimplePluginRegistry.getRequiredPluginFor(SimplePluginRegistry.java:140) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.springframework.plugin.core.SimplePluginRegistry.getRequiredPluginFor(SimplePluginRegistry.java:126) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.springframework.hateoas.server.core.DelegatingLinkRelationProvider.getCollectionResourceRelFor(DelegatingLinkRelationProvider.java:67) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.springframework.hateoas.mediatype.hal.HalEmbeddedBuilder.lambda$getDefaultedRelFor$0(HalEmbeddedBuilder.java:141) ~[na:na]
        at java.util.Optional.orElseGet(Optional.java:267) ~[na:na]
        at org.springframework.hateoas.mediatype.hal.HalEmbeddedBuilder.getDefaultedRelFor(HalEmbeddedBuilder.java:132) ~[na:na]
        at org.springframework.hateoas.mediatype.hal.HalEmbeddedBuilder.add(HalEmbeddedBuilder.java:97) ~[na:na]
        at java.util.ArrayList.forEach(ArrayList.java:1259) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082) ~[na:na]
        at org.springframework.hateoas.mediatype.hal.Jackson2HalModule$EmbeddedMapper.map(Jackson2HalModule.java:874) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.springframework.hateoas.mediatype.hal.Jackson2HalModule$HalResourcesSerializer.serialize(Jackson2HalModule.java:326) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.springframework.hateoas.mediatype.hal.Jackson2HalModule$HalResourcesSerializer.serialize(Jackson2HalModule.java:289) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728) ~[na:na]
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770) ~[na:na]
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480) ~[na:na]
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319) ~[na:na]
        at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1514) ~[na:na]
        at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1006) ~[na:na]
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:454) ~[na:na]
        at org.springframework.http.converter.AbstractGenericHttpMessageConverter.write(AbstractGenericHttpMessageConverter.java:104) ~[na:na]
        at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:290) ~[na:na]
        at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.handleReturnValue(RequestResponseBodyMethodProcessor.java:183) ~[na:na]
        at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:78) ~[na:na]
        at org.springframework.hateoas.server.mvc.RepresentationModelProcessorHandlerMethodReturnValueHandler.handleReturnValue(RepresentationModelProcessorHandlerMethodReturnValueHandler.java:134) ~[na:na]
        at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:78) ~[na:na]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:124) ~[na:na]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[na:na]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1064) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:645) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[na:na]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[na:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327) ~[na:na]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115) ~[na:na]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81) ~[na:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[na:na]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:121) ~[na:na]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115) ~[na:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[na:na]
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126) ~[na:na]
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81) ~[na:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[na:na]
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105) ~[na:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[na:na]
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149) ~[na:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[na:na]
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[na:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[na:na]
        at org.springframework.security.oauth2.server.resource.web.BearerTokenAuthenticationFilter.doFilterInternal(BearerTokenAuthenticationFilter.java:137) ~[na:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[na:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[na:na]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103) ~[na:na]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89) ~[na:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[na:na]
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91) ~[na:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[na:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[na:na]
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) ~[na:na]
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) ~[na:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[na:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[na:na]
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110) ~[na:na]
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80) ~[na:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[na:na]
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55) ~[na:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[na:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[na:na]
        at org.springframework.security.web.access.channel.ChannelProcessingFilter.doFilter(ChannelProcessingFilter.java:133) ~[na:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[na:na]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211) ~[na:na]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183) ~[na:na]
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358) ~[na:na]
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[na:na]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[na:na]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[na:na]
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) ~[na:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[na:na]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[na:na]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[na:na]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) [pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726) [pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at java.lang.Thread.run(Thread.java:748) [pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:567) [pf.cps.rima.web.RimaWebEndpointsApplication:na]
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192) [pf.cps.rima.web.RimaWebEndpointsApplication:na]
```

**Comment by ch4mpy** [comment]
@sdeleuze merci!

Also, this gave me an indication on how to declare proxy hints when I get such an error with my code.
I know this is more GraalVM scope than pure spring-native, but a paragraph on this (what proxy hint to declare on which compilation / runtime error) could be useful.
