### ISSUE TITLE
Restore Spring Integration support

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#1134]
To be discussed with @artembilan and @snicoll.

**Comment by sdeleuze** [comment]
Awesome, thanks a lot @snicoll.

**Comment by sdeleuze** [comment]
I am moving this one to 0.11.0 in order to allow us to focus on testing which is the highest priority.

**Comment by snicoll** [comment]
Spring Integration used to work on AOT and now doesn't anymore so I think we need to make sure we fix that first by not changing things in Spring Integration (or fixing them if they have to be).

The sample fails currently with:

```
2021-11-08 09:54:19.410  INFO 13418 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.integration.config.IntegrationManagementConfiguration' of type [org.springframework.integration.config.IntegrationManagementConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-11-08 09:54:19.430  INFO 13418 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'integrationChannelResolver' of type [org.springframework.integration.support.channel.BeanFactoryChannelResolver] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-11-08 09:54:19.432  INFO 13418 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'integrationDisposableAutoCreatedBeans' of type [org.springframework.integration.config.annotation.Disposables] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-11-08 09:54:19.671  INFO 13418 --- [           main] o.s.j.d.e.EmbeddedDatabaseFactory        : Starting embedded database: url='jdbc:h2:mem:d748fea7-eb9f-4316-817f-59fd975a0704;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false', username='sa'
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.util.ReflectionUtils (jar:file:/Users/snicoll/workspace/work/experimental/spring-native/samples/integration/target/integration-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-core-5.3.13-SNAPSHOT.jar!/) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class)
WARNING: Please consider reporting this to the maintainers of org.springframework.util.ReflectionUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2021-11-08 09:54:20.894  WARN 13418 --- [           main] .r.c.ReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'integrationMessageHandlerMethodFactory': Initialization of bean failed; nested exception is org.springframework.beans.ConversionNotSupportedException: Failed to convert property value of type 'java.util.ImmutableCollections$ListN' to required type 'java.util.List' for property 'customArgumentResolvers'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'org.springframework.beans.factory.support.RootBeanDefinition' to required type 'org.springframework.messaging.handler.invocation.HandlerMethodArgumentResolver' for property 'customArgumentResolvers[0]': no matching editors or conversion strategy found
2021-11-08 09:54:20.914  INFO 13418 --- [           main] o.s.j.d.e.EmbeddedDatabaseFactory        : Shutting down embedded database: url='jdbc:h2:mem:d748fea7-eb9f-4316-817f-59fd975a0704;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false'
2021-11-08 09:54:21.147 ERROR 13418 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'integrationMessageHandlerMethodFactory': Initialization of bean failed; nested exception is org.springframework.beans.ConversionNotSupportedException: Failed to convert property value of type 'java.util.ImmutableCollections$ListN' to required type 'java.util.List' for property 'customArgumentResolvers'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'org.springframework.beans.factory.support.RootBeanDefinition' to required type 'org.springframework.messaging.handler.invocation.HandlerMethodArgumentResolver' for property 'customArgumentResolvers[0]': no matching editors or conversion strategy found
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:628) ~[spring-beans-5.3.13-SNAPSHOT.jar!/:5.3.13-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.13-SNAPSHOT.jar!/:5.3.13-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.13-SNAPSHOT.jar!/:5.3.13-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.13-SNAPSHOT.jar!/:5.3.13-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.13-SNAPSHOT.jar!/:5.3.13-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.13-SNAPSHOT.jar!/:5.3.13-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.13-SNAPSHOT.jar!/:5.3.13-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.13-SNAPSHOT.jar!/:5.3.13-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.13-SNAPSHOT.jar!/:5.3.13-SNAPSHOT]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:64) ~[spring-boot-2.6.0-SNAPSHOT.jar!/:2.6.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:719) ~[classes!/:0.0.1-SNAPSHOT]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:401) ~[classes!/:0.0.1-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) ~[classes!/:0.0.1-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1290) ~[classes!/:0.0.1-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1279) ~[classes!/:0.0.1-SNAPSHOT]
	at com.example.integration.IntegrationApplication.main(IntegrationApplication.java:50) ~[classes!/:0.0.1-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[integration-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[integration-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[integration-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[integration-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
Caused by: org.springframework.beans.ConversionNotSupportedException: Failed to convert property value of type 'java.util.ImmutableCollections$ListN' to required type 'java.util.List' for property 'customArgumentResolvers'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'org.springframework.beans.factory.support.RootBeanDefinition' to required type 'org.springframework.messaging.handler.invocation.HandlerMethodArgumentResolver' for property 'customArgumentResolvers[0]': no matching editors or conversion strategy found
	at org.springframework.beans.AbstractNestablePropertyAccessor.convertIfNecessary(AbstractNestablePropertyAccessor.java:595) ~[spring-beans-5.3.13-SNAPSHOT.jar!/:5.3.13-SNAPSHOT]
	at org.springframework.beans.AbstractNestablePropertyAccessor.convertForProperty(AbstractNestablePropertyAccessor.java:609) ~[spring-beans-5.3.13-SNAPSHOT.jar!/:5.3.13-SNAPSHOT]
	at org.springframework.beans.BeanWrapperImpl.convertForProperty(BeanWrapperImpl.java:219) ~[spring-beans-5.3.13-SNAPSHOT.jar!/:5.3.13-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.convertForProperty(AbstractAutowireCapableBeanFactory.java:1756) ~[spring-beans-5.3.13-SNAPSHOT.jar!/:5.3.13-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1712) ~[spring-beans-5.3.13-SNAPSHOT.jar!/:5.3.13-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1452) ~[spring-beans-5.3.13-SNAPSHOT.jar!/:5.3.13-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619) ~[spring-beans-5.3.13-SNAPSHOT.jar!/:5.3.13-SNAPSHOT]
	... 23 common frames omitted
Caused by: java.lang.IllegalStateException: Cannot convert value of type 'org.springframework.beans.factory.support.RootBeanDefinition' to required type 'org.springframework.messaging.handler.invocation.HandlerMethodArgumentResolver' for property 'customArgumentResolvers[0]': no matching editors or conversion strategy found
	at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:262) ~[spring-beans-5.3.13-SNAPSHOT.jar!/:5.3.13-SNAPSHOT]
	at org.springframework.beans.TypeConverterDelegate.convertToTypedCollection(TypeConverterDelegate.java:528) ~[spring-beans-5.3.13-SNAPSHOT.jar!/:5.3.13-SNAPSHOT]
	at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:176) ~[spring-beans-5.3.13-SNAPSHOT.jar!/:5.3.13-SNAPSHOT]
	at org.springframework.beans.AbstractNestablePropertyAccessor.convertIfNecessary(AbstractNestablePropertyAccessor.java:590) ~[spring-beans-5.3.13-SNAPSHOT.jar!/:5.3.13-SNAPSHOT]
	... 29 common frames omitted
```

**Comment by snicoll** [comment]
Running the integration samples now leads to:

```

***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'integrationDisposableAutoCreatedBeans' could not be registered. A bean with that name has already been defined and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true
```

I suspect that something has been called at build time and is called again at runtime and attempt to register a bean that's already there. @artembilan do you have some cycles to resume this? I intend to spend a bit of time next week on this so any insight would be much appreciated.

**Comment by sdeleuze** [comment]
Require at least Spring Integration `5.5.7`.

**Comment by snicoll** [comment]
Technically this would work for anyone using `0.10.0` and overriding the spring integration version to use. I agree we shouldn't claim it's compatible but if no other changes are required, maybe we could close this one?

**Comment by sdeleuze** [comment]
We could but I thought it would be better to keep it open until we remove the version override in order to have it mentioned in the changelog when effectively supported out of the box (I guess you meant 0.11.0).

**Comment by snicoll** [comment]
Yes sorry I meant `0.11.0`. Spring Native does not provide dependency management and if nothing here is required, it's a bit artificial to keep the issue open. If Spring Integration ships its version in Spring Boot `2.6.2`, then there is no need for a `0.10.1` release to make this work...
