### ISSUE TITLE
Externally managed private methods are not handled properly as they contain the fqn of the declaring class

### ISSUE THREAD

**Issue by phejl** [spring-projects-experimental/spring-native#1135]
Using main branch the generateAot phase throws `java.lang.IllegalStateException: Lifecycle method annotation 'com.some.Class.privateMethod' not found on: class com.some.Class`. This used to work before.

**Comment by snicoll** [comment]
Can you please share a small sample we can run ourselves?

**Comment by phejl** [comment]
@snicoll Yep, I'll try. Or perhaps I'll try to provide a patch. Can be workarounded by changing the modifier of the method.

**Comment by snicoll** [comment]
Yes I am sure of that. If you can't share a sample, can you share a class that contains the `@PostConstruct` and the full stacktrace please?

**Comment by sdeleuze** [comment]
I was able to reproduce it by adding this to `CLR` in `commandlinerunner`:

```
@PostConstruct
private void hello() {
	System.out.println("Hello!");
}
```

The stacktrace was:
```
[INFO] --- spring-aot-maven-plugin:0.11.0-SNAPSHOT:generate (generate) @ commandlinerunner ---
[2021-10-05 11:52:56.112] - ???? INFO [main] --- org.springframework.aot.context.bootstrap.ContextBootstrapContributor: Detected application class: com.example.commandlinerunner.CommandlinerunnerApplication
[2021-10-05 11:52:56.127] - ???? INFO [main] --- org.springframework.aot.context.bootstrap.ContextBootstrapContributor: Processing application context
java.lang.IllegalStateException: Lifecycle method annotation 'com.example.commandlinerunner.CLR.hello' not found on: class com.example.commandlinerunner.CLR
	at org.springframework.aot.context.bootstrap.generator.infrastructure.InitDestroyMethodsDiscoverer.findMethod(InitDestroyMethodsDiscoverer.java:181)
	at org.springframework.aot.context.bootstrap.generator.infrastructure.InitDestroyMethodsDiscoverer.processInitMethods(InitDestroyMethodsDiscoverer.java:89)
	at org.springframework.aot.context.bootstrap.generator.infrastructure.InitDestroyMethodsDiscoverer.processLifecycleMethods(InitDestroyMethodsDiscoverer.java:119)
	at org.springframework.aot.context.bootstrap.generator.infrastructure.InitDestroyMethodsDiscoverer.registerInitMethods(InitDestroyMethodsDiscoverer.java:79)
	at org.springframework.aot.context.bootstrap.generator.infrastructure.BootstrapInfrastructureWriter.handleInitDestroyBeanPostProcessor(BootstrapInfrastructureWriter.java:102)
	at org.springframework.aot.context.bootstrap.generator.infrastructure.BootstrapInfrastructureWriter.writeInfrastructure(BootstrapInfrastructureWriter.java:72)
	at org.springframework.aot.context.bootstrap.generator.ContextBootstrapGenerator.registerApplicationContextInfrastructure(ContextBootstrapGenerator.java:149)
	at org.springframework.aot.context.bootstrap.generator.ContextBootstrapGenerator.generateBootstrapMethod(ContextBootstrapGenerator.java:112)
	at org.springframework.aot.context.bootstrap.generator.ContextBootstrapGenerator.generateBootstrapClass(ContextBootstrapGenerator.java:87)
	at org.springframework.aot.context.bootstrap.ContextBootstrapContributor.contribute(ContextBootstrapContributor.java:75)
	at org.springframework.aot.BootstrapCodeGenerator.generate(BootstrapCodeGenerator.java:90)
	at org.springframework.aot.BootstrapCodeGenerator.generate(BootstrapCodeGenerator.java:70)
	at org.springframework.aot.context.bootstrap.GenerateBootstrap.call(GenerateBootstrap.java:105)
	at org.springframework.aot.context.bootstrap.GenerateBootstrap.call(GenerateBootstrap.java:44)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.springframework.aot.context.bootstrap.GenerateBootstrap.main(GenerateBootstrap.java:110)
[ERROR] 
java.lang.IllegalStateException: Bootstrap code generator finished with exit code: 1
    at org.springframework.aot.maven.GenerateMojo.execute (GenerateMojo.java:138)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR] [org.springframework.aot.maven.GenerateMojo.execute(GenerateMojo.java:138), org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137), org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210), org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156), org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148), org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117), org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81), org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56), org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128), org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305), org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192), org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105), org.apache.maven.cli.MavenCli.execute(MavenCli.java:957), org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289), org.apache.maven.cli.MavenCli.main(MavenCli.java:193), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.base/java.lang.reflect.Method.invoke(Method.java:566), org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282), org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225), org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406), org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)]
```
We should probably add such construct to `features` sample.

**Comment by snicoll** [comment]
This is specific to `@PostConstruct` and how externally managed methods are represented. If the method is private, the String representation contains the fully-qualified name of the declaring class for some reason. We can see this in the issue above, the exception message

```
Lifecycle method annotation 'com.example.commandlinerunner.CLR.hello' not found on: class com.example.commandlinerunner.CLR
```

should rather be:

```
Lifecycle method annotation 'hello' not found on: class com.example.commandlinerunner.CLR
```
