### ISSUE TITLE
when use dom4j to parse message which type is byteArrays, it occurs error

### ISSUE THREAD

**Issue by phlahut** [spring-projects-experimental/spring-native#1148]
org.dom4j.DocumentException: null
        at org.dom4j.io.SAXReader.read(SAXReader.java:468)
        at org.dom4j.io.SAXReader.read(SAXReader.java:401)
        at com.aliyun.iotx.vision.edge.gb28181.biz.infrastructure.sip.helper.RequestEventHelper.getRootElement(RequestEventHelper.java:203)
        at com.aliyun.iotx.vision.edge.gb28181.biz.infrastructure.sip.event.processor.request.MessageRequestProcessor.process(MessageRequestProcessor.java:56)
        at com.aliyun.iotx.vision.edge.gb28181.biz.infrastructure.sip.event.processor.SipProcessorCenter.processRequest(SipProcessorCenter.java:62)
        at com.aliyun.iotx.vision.edge.gb28181.biz.infrastructure.sip.event.listener.SipEventListener.lambda$processRequest$0(SipEventListener.java:35)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:829)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:567)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.lang.NullPointerException: null
        at org.dom4j.tree.NamespaceStack.createNamespace(NamespaceStack.java:407)
        at org.dom4j.tree.NamespaceStack.getQName(NamespaceStack.java:211)
        at org.dom4j.io.SAXContentHandler.startElement(SAXContentHandler.java:226)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:510)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:613)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3063)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:836)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
        at org.dom4j.io.SAXReader.read(SAXReader.java:449)
        ... 10 common frames omitted

**Comment by mrtian2019** [comment]
I have the same problem

**Comment by phlahut** [comment]
sorry for missied the msg, I use the sample's json to solve the problem.
link is 
https://github.com/spring-projects-experimental/spring-native/blob/af0e804e49887b77567721b73efebb18e2992e79/samples/batch-io/src/main/resources/META-INF/native-image/a/b/reflect-config.json#L1733

**Comment by phlahut** [comment]
@mrtian2019 
sorry for missied the msg, I use the sample's json to solve the problem.
link is
spring-native/samples/batch-io/src/main/resources/META-INF/native-image/a/b/reflect-config.json
