### ISSUE TITLE
Error in building sample project from Get Started page

### ISSUE THREAD

**Issue by khaeghar** [spring-projects-experimental/spring-native#1150]
Hi,

I followed step by step every one of the chapters of the Getting Started with the sample project of gs-rest-service. (https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#getting-started-buildpacks)

Once I added and fixed everything in the pom, this was the final result when executing the command 'mvn spring-boot:build-image.

```
[INFO]     [creator]     Fatal error:java.util.MissingResourceException: Can't find bundle for base name org.apache.tomcat.util.threads.res.LocalStrings, locale en_US
[INFO]     [creator]     	at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2055)
[INFO]     [creator]     	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1689)
[INFO]     [creator]     	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593)
[INFO]     [creator]     	at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:1284)
[INFO]     [creator]     	at com.oracle.svm.util.ModuleSupport.getResourceBundleFallback(ModuleSupport.java:82)
[INFO]     [creator]     	at com.oracle.svm.util.ModuleSupport.getResourceBundle(ModuleSupport.java:58)
[INFO]     [creator]     	at com.oracle.svm.core.jdk.LocalizationFeature.addBundleToCache(LocalizationFeature.java:267)
[INFO]     [creator]     	at com.oracle.svm.hosted.ResourcesFeature$ResourcesRegistryImpl.addResourceBundles(ResourcesFeature.java:102)
[INFO]     [creator]     	at com.oracle.svm.core.configure.ResourceConfigurationParser.parseEntry(ResourceConfigurationParser.java:117)
[INFO]     [creator]     	at com.oracle.svm.core.configure.ResourceConfigurationParser.parseTopLevelObject(ResourceConfigurationParser.java:98)
[INFO]     [creator]     	at com.oracle.svm.core.configure.ResourceConfigurationParser.parseAndRegister(ResourceConfigurationParser.java:47)
[INFO]     [creator]     	at com.oracle.svm.hosted.config.ConfigurationParserUtils.doParseAndRegister(ConfigurationParserUtils.java:132)
[INFO]     [creator]     	at com.oracle.svm.hosted.config.ConfigurationParserUtils.lambda$parseAndRegisterConfigurations$3(ConfigurationParserUtils.java:119)
[INFO]     [creator]     	at java.base/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:212)
[INFO]     [creator]     	at com.oracle.svm.hosted.config.ConfigurationParserUtils$1.tryAdvance(ConfigurationParserUtils.java:108)
[INFO]     [creator]     	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:326)
[INFO]     [creator]     	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
[INFO]     [creator]     	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
[INFO]     [creator]     	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
[INFO]     [creator]     	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[INFO]     [creator]     	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[INFO]     [creator]     	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
[INFO]     [creator]     	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
[INFO]     [creator]     	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[INFO]     [creator]     	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[INFO]     [creator]     	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
[INFO]     [creator]     	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[INFO]     [creator]     	at java.base/java.util.stream.IntPipeline.reduce(IntPipeline.java:491)
[INFO]     [creator]     	at java.base/java.util.stream.IntPipeline.sum(IntPipeline.java:449)
[INFO]     [creator]     	at com.oracle.svm.hosted.config.ConfigurationParserUtils.parseAndRegisterConfigurations(ConfigurationParserUtils.java:125)
[INFO]     [creator]     	at com.oracle.svm.hosted.ResourcesFeature.beforeAnalysis(ResourcesFeature.java:115)
[INFO]     [creator]     	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$7(NativeImageGenerator.java:701)
[INFO]     [creator]     	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
[INFO]     [creator]     	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:701)
[INFO]     [creator]     	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:563)
[INFO]     [creator]     	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
[INFO]     [creator]     	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
[INFO]     [creator]     	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[INFO]     [creator]     	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[INFO]     [creator]     	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[INFO]     [creator]     	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[INFO]     [creator]     	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[INFO]     [creator]     Error: Image build request failed with exit status 1
[INFO]     [creator]     unable to invoke layer creator
[INFO]     [creator]     unable to contribute native-image layer
[INFO]     [creator]     error running build
[INFO]     [creator]     exit status 1
[INFO]     [creator]     ERROR: failed to build: exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  57.847 s
[INFO] Finished at: 2021-10-13T05:20:51-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.5.5:build-image (default-cli) on project rest-service-complete: Execution default-cli of goal org.springframework.boot:spring-boot-maven-plugin:2.5.5:build-image failed: Builder lifecycle 'creator' failed with status code 145 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

```

Checked for memory, but it has 16GB on my machine, and I think the error is not the lack of ram, at least this time.

Any possible fix? I tried to add the pom for the tomcat utils so it could add the dependency in build time but doesn't seem to work either. Am I doing something wrong?

**Comment by ttddyy** [comment]
Hi @khaeghar,

It worked fine on my machine.


```
> mvn package -DskipTests

...

[INFO] Successfully built image 'docker.io/library/rest-service-complete:0.0.1-SNAPSHOT'
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:56 min
[INFO] Finished at: 2021-10-15T12:27:03-07:00
[INFO] ------------------------------------------------------------------------
```

Most likely, the issue is that you need to allocate more memory to your docker.

Please reference these "Troubleshooting" entries in the documentation:
- [10.1.3. Out of memory error when building the native image](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#_out_of_memory_error_when_building_the_native_image)
- [10.1.4. Builder lifecycle 'creator' failed with status code 145](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#_builder_lifecycle_creator_failed_with_status_code_145)


FYI: you could generate a project from [start.spring.io](https://start.spring.io/) with "Spring Native" dependency. The generated project has already been configured with all the necessary steps. So, you don't need to manually setup them.
