### ISSUE TITLE
Fix cloud-function-aws sample

### ISSUE THREAD

**Issue by cmoyer2** [spring-projects-experimental/spring-native#1151]
I'm running the cloud-function-aws sample and am getting an error regarding missing native reflection configuration for GenericApplication context.

I've run the following after checking out the code.

`./build.sh`

`mvn package -P native-image`

But I receive the following error when testing the Lambda Function in AWS after deploying the native image zip file.

`2021-10-13 12:35:06.638  INFO 9 --- [           main] o.s.nativex.NativeListener               : This application is bootstrapped with code generated with Spring AOT
.   ____          _            __ _ _
/\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _ | \ \ \ \
\\/  ___)| |_)| | | | | || (_| |  ) ) ) )
'  |____| .__|_| |_|_| |_\__, | / / / /
=========|_|==============|___/=/_/_/_/
:: Spring Boot ::             (v2.6.0-M3)
2021-10-13 12:35:06.677 DEBUG 9 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : Application failed to start **due to an exception
java.lang.NoSuchMethodException: org.springframework.context.support.GenericApplicationContext.<init>()**
at java.lang.Class.getConstructor0(DynamicHub.java:3349) ~[na:na]
at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2553) ~[na:na]
at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:25) ~[na:na]
at org.springframework.boot.ApplicationContextFactory.lambda$ofContextClass$1(ApplicationContextFactory.java:77) ~[na:na]
at org.springframework.boot.ApplicationContextFactory.lambda$of$2(ApplicationContextFactory.java:88) ~[na:na]
at org.springframework.boot.SpringApplication.createApplicationContext(SpringApplication.java:561) ~[cloud-function-aws:2.6.0-M3]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:299) ~[cloud-function-aws:2.6.0-M3]
at org.springframework.cloud.function.context.FunctionalSpringApplication.run(FunctionalSpringApplication.java:88) ~[na:na]
at org.springframework.cloud.function.context.FunctionalSpringApplication.run(FunctionalSpringApplication.java:83) ~[na:na]
at com.example.demo.DemoApplication.main(DemoApplication.java:14) ~[cloud-function-aws:0.0.1-SNAPSHOT]
2021-10-13 12:35:06.677 ERROR 9 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 
***************************
APPLICATION FAILED TO START
***************************
Description:
**Native reflection configuration for org.springframework.context.support.GenericApplicationContext.<init>() is missing.
Action:
Native configuration for a method accessed reflectively is likely missing.**
You can try to configure native hints in order to specify it explicitly.
See https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#native-hints for more details.
END RequestId: 6a92bca8-2768-45f1-9ced-ff4833ee8f42
REPORT RequestId: 6a92bca8-2768-45f1-9ced-ff4833ee8f42	Duration: 298.94 ms	Billed Duration: 299 ms	Memory Size: 128 MB	Max Memory Used: 11 MB	
RequestId: 6a92bca8-2768-45f1-9ced-ff4833ee8f42 Error: Runtime exited with error: exit status 1
Runtime.ExitError`

Am I missing a step when running this sample project?

**Comment by sdeleuze** [comment]
You should use `mvn package -P native` not `mvn package -P native-image`, could you test using that?
