### ISSUE TITLE
Regex characters are not escaped properly for pattern resources

### ISSUE THREAD

**Issue by bojanv55** [spring-projects-experimental/spring-native#1193]
Trying to create native-image with resource:

```
{
  "pattern": "public"
}
```

Resource names are:

```
public/
    {rad}.moj.txt
```

I get:

```
Fatal error:java.util.regex.PatternSyntaxException: Illegal repetition near index 6
public/{rad}.moj.txt
      ^
        at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
        at java.base/java.util.regex.Pattern.closure(Pattern.java:3320)
        at java.base/java.util.regex.Pattern.sequence(Pattern.java:2213)
        at java.base/java.util.regex.Pattern.expr(Pattern.java:2068)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1782)
        at java.base/java.util.regex.Pattern.<init>(Pattern.java:1428)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1068)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.concurrent.ConcurrentHashMap$KeySpliterator.forEachRemaining(ConcurrentHashMap.java:3566)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at com.oracle.svm.hosted.ResourcesFeature.compilePatterns(ResourcesFeature.java:231)
        at com.oracle.svm.hosted.ResourcesFeature.duringAnalysis(ResourcesFeature.java:169)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$12(NativeImageGenerator.java:730)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:71)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:730)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:532)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:491)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:380)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:543)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:573)

```

**Comment by sdeleuze** [comment]
There is potentially an issue in how we escape filenames autodetected in `src/main/resources` and `src/test/resources`. @aclement Could you please let me know where is the code in charge of this?

**Comment by aclement** [comment]
I don't think we have any general handling. The place we saw the issue was inner class references and `ResourcesDescriptor` does that case in a specific way:

```
	public void addClass(String className) {
		add(className.replace(".", "/").replace("$", "\\$") + ".class");
	}
```

The other cases we saw with the agent and they decided to handle that directly by simply encasing all entries with `\\Q` `\\E` (https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html) - this allowed any old characters in between. The simplistic approach here would be to match the agent and just put Q and E around all our entries, but maybe you can do something a little less ugly and only add that if you detect something not in a sensible range, e.g. if it includes something non alphanumeric and it isn't /.$ or something. 

Actually see the second TODO in `BootstrapCodeGenerator` (this is where we auto add all the entries that are resources):
```
Files.walk(resourceFolder).filter(p -> !p.toFile().isDirectory()).forEach(p -> {
  String resourcePattern = p.toString().substring(resourceFolderLen);
  String platformNormalisedResourcePattern = resourcePattern.replace("\\", "/");
  if (!platformNormalisedResourcePattern.startsWith("META-INF/native-image")) {
    if (matchesPatternInCache(platformNormalisedResourcePattern))
      return;
    logger.debug("Resource pattern: " + platformNormalisedResourcePattern);
    // TODO recognize resource bundles?
    // TODO escape the patterns (add leading trailing Q and E sequences...)
    buildContext.describeResources(crd -> crd.add(platformNormalisedResourcePattern));
  }
});
```

**Comment by sdeleuze** [comment]
I can't reproduce this issue, Spring Native configures entries for default directories which do not contain specific characters, not per files entries, and manual ones can be escaped when specifyed.

Please update with a repro project if still relevant WITH `0.11.0-SNAPSHOT`.

**Comment by bojanv55** [comment]
@sdeleuze just tried this with `0.11.0-SNAPSHOT`. got same problem:

```
Fatal error:java.util.regex.PatternSyntaxException: Illegal repetition near index 8
static/{rad}.moj.txt
        ^
        at java.base/java.util.regex.Pattern.error(Pattern.java:2028)
        at java.base/java.util.regex.Pattern.closure(Pattern.java:3309)
```

Just to ask - did you try to reproduce this on **WINDOWS** ?

**Comment by sdeleuze** [comment]
After a discussion with @aclement it seems there is indeed something to fix, I will have another look later.
