### ISSUE TITLE
NullPointerException at ConfigurationPropertiesNativeConfigurationProcessor

### ISSUE THREAD

**Issue by sueleyman-dmr** [spring-projects-experimental/spring-native#1240]
Hi, does someone know what this error means explicitly? Do I have problem, when building the Image with "gradle bootBuildImage" in dependecy injection?

```
`java.lang.NullPointerException
        at org.springframework.boot.context.properties.ConfigurationPropertiesNativeConfigurationProcessor$TypeProcessor.handleValueObjectProperties(ConfigurationPropertiesNativeConfigurationProcessor.java:123)
        at org.springframework.boot.context.properties.ConfigurationPropertiesNativeConfigurationProcessor$TypeProcessor.process(ConfigurationPropertiesNativeConfigurationProcessor.java:103)
        at org.springframework.boot.context.properties.ConfigurationPropertiesNativeConfigurationProcessor$TypeProcessor.handleValueObjectProperties(ConfigurationPropertiesNativeConfigurationProcessor.java:127)
        at org.springframework.boot.context.properties.ConfigurationPropertiesNativeConfigurationProcessor$TypeProcessor.process(ConfigurationPropertiesNativeConfigurationProcessor.java:103)
        at org.springframework.boot.context.properties.ConfigurationPropertiesNativeConfigurationProcessor.processConfigurationProperties(ConfigurationPropertiesNativeConfigurationProcessor.java:67)
        at org.springframework.boot.context.properties.ConfigurationPropertiesNativeConfigurationProcessor.process(ConfigurationPropertiesNativeConfigurationProcessor.java:61)
        at org.springframework.aot.context.bootstrap.generator.infrastructure.nativex.NativeConfigurationRegistrar.lambda$processBeanFactory$0(NativeConfigurationRegistrar.java:55)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.springframework.aot.context.bootstrap.generator.infrastructure.nativex.NativeConfigurationRegistrar.processBeanFactory(NativeConfigurationRegistrar.java:55)
        at org.springframework.aot.context.bootstrap.generator.ApplicationContextAotProcessor.generateBootstrapMethod(ApplicationContextAotProcessor.java:104)
        at org.springframework.aot.context.bootstrap.generator.ApplicationContextAotProcessor.process(ApplicationContextAotProcessor.java:91)
        at org.springframework.aot.build.ContextBootstrapContributor.contribute(ContextBootstrapContributor.java:80)
        at org.springframework.aot.build.BootstrapCodeGenerator.generate(BootstrapCodeGenerator.java:90)
        at org.springframework.aot.build.BootstrapCodeGenerator.generate(BootstrapCodeGenerator.java:68)
        at org.springframework.aot.build.GenerateBootstrapCommand.call(GenerateBootstrapCommand.java:103)
        at org.springframework.aot.build.GenerateBootstrapCommand.call(GenerateBootstrapCommand.java:42)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at org.springframework.aot.build.GenerateBootstrapCommand.main(GenerateBootstrapCommand.java:108)

> Task :generateAot FAILED

FAILURE: Build failed with an exception.
```

**Comment by snicoll** [comment]
Thanks for the report, that looks like a bug in the way a constructor that can't be found is handled.

**Comment by sueleyman-dmr** [comment]
It's a Kotlin project, by the way.

**Comment by snicoll** [comment]
Can you share it by any chance?

**Comment by snicoll** [comment]
@sueleyman-dmr I've pushed a fix but I am still interested to understand why the constructor of your `@ConstructorBinding` type wasn't found.

**Comment by sueleyman-dmr** [comment]
> @sueleyman-dmr I've pushed a fix but I am still interested to understand why the constructor of your `@ConstructorBinding` type wasn't found.

Sorry, it's not possible for me to share any code.
