### ISSUE TITLE
Spring Cloud Consul and org.springframework.boot.context.config.ConfigDataResourceNotFoundException

### ISSUE THREAD

**Issue by sergey-morenets** [spring-projects-experimental/spring-native#1254]
Hi 

We're using Spring Cloud Consul in our application to store and fetch distributed configuration:

```
spring:
  cloud:
    consul:
      retry:
        enabled: true
        initialInterval: 2000
        multiplier: 2
        maxInterval: 60000
  config:
    import: consul:consul:8500/project/default;project/user;project/spring-boot  
```

When we try to generate native image using the latest version of Aot plugin (0.11.0-M2) we receive an error that consul host is not found (it's available only in production):

```
#19 89.01 org.springframework.boot.context.config.ConfigDataResourceNotFoundException: Config data resource '[ConsulConfigDataResource@16c3ca31 context = 'project/spring-boot/', optional = true, properties = [ConsulConfigProperties@2d195ee4 enabled = true, prefixes = list['config'], defaultContext = 'application', profileSeparator = ',', format = KEY_VALUE, dataKey = 'data', aclToken = [null], watch = [ConsulConfigProperties.Watch@2d6aca33 waitTime = 55, enabled = true, delay = 1000], failFast = true, name = 'application']]' via location 'consul:consul:8500/project/default;project/user;project/spring-boot' cannot be found
#19 89.01 	at org.springframework.boot.context.config.ConfigDataResourceNotFoundException.withLocation(ConfigDataResourceNotFoundException.java:97)
#19 89.01 	at org.springframework.boot.context.config.ConfigDataImporter.handle(ConfigDataImporter.java:145)
#19 89.01 	at org.springframework.boot.context.config.ConfigDataImporter.load(ConfigDataImporter.java:136)
#19 89.01 	at org.springframework.boot.context.config.ConfigDataImporter.resolveAndLoad(ConfigDataImporter.java:86)
#19 89.01 	at org.springframework.boot.context.config.ConfigDataEnvironmentContributors.withProcessedImports(ConfigDataEnvironmentContributors.java:121)
#19 89.01 	at org.springframework.boot.context.config.ConfigDataEnvironment.processWithProfiles(ConfigDataEnvironment.java:311)
#19 89.01 	at org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(ConfigDataEnvironment.java:232)
#19 89.01 	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:102)
#19 89.01 	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:94)
#19 89.01 	at org.springframework.boot.AotApplicationContextFactory.loadEnvironment(AotApplicationContextFactory.java:66)
#19 89.01 	at org.springframework.boot.AotApplicationContextFactory.createApplicationContext(AotApplicationContextFactory.java:52)
#19 89.01 	at org.springframework.aot.build.ContextBootstrapContributor.contribute(ContextBootstrapContributor.java:77)
#19 89.01 	at org.springframework.aot.build.BootstrapCodeGenerator.generate(BootstrapCodeGenerator.java:90)
#19 89.01 	at org.springframework.aot.build.BootstrapCodeGenerator.generate(BootstrapCodeGenerator.java:68)
#19 89.01 	at org.springframework.aot.build.GenerateBootstrapCommand.call(GenerateBootstrapCommand.java:103)
#19 89.01 	at org.springframework.aot.build.GenerateBootstrapCommand.call(GenerateBootstrapCommand.java:42)
#19 89.01 	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
#19 89.01 	at picocli.CommandLine.access$1300(CommandLine.java:145)
#19 89.01 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
#19 89.01 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
#19 89.01 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
#19 89.01 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
#19 89.01 	at picocli.CommandLine.execute(CommandLine.java:2078)
#19 89.01 	at org.springframework.aot.build.GenerateBootstrapCommand.main(GenerateBootstrapCommand.java:108)
#19 89.01 Caused by: org.springframework.cloud.consul.config.ConsulPropertySources$PropertySourceNotFoundException: com.ecwid.consul.transport.TransportException: java.net.UnknownHostException: consul: Name or service not known
#19 89.01 	at org.springframework.cloud.consul.config.ConsulPropertySources.createPropertySource(ConsulPropertySources.java:136)
#19 89.01 	at org.springframework.cloud.consul.config.ConsulConfigDataLoader.doLoad(ConsulConfigDataLoader.java:58)
#19 89.01 	at org.springframework.cloud.consul.config.ConsulConfigDataLoader.load(ConsulConfigDataLoader.java:49)
#19 89.01 	at org.springframework.cloud.consul.config.ConsulConfigDataLoader.load(ConsulConfigDataLoader.java:32)
#19 89.01 	at org.springframework.boot.context.config.ConfigDataLoaders.load(ConfigDataLoaders.java:107)
#19 89.01 	at org.springframework.boot.context.config.ConfigDataImporter.load(ConfigDataImporter.java:128)
#19 89.01 	... 21 more
#19 89.01 Caused by: com.ecwid.consul.transport.TransportException: java.net.UnknownHostException: consul: Name or service not known
#19 89.01 	at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:83)
#19 89.01 	at com.ecwid.consul.transport.AbstractHttpTransport.makeGetRequest(AbstractHttpTransport.java:36)
#19 89.01 	at com.ecwid.consul.v1.ConsulRawClient.makeGetRequest(ConsulRawClient.java:139)
#19 89.01 	at com.ecwid.consul.v1.ConsulRawClient.makeGetRequest(ConsulRawClient.java:128)
#19 89.01 	at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVValues(KeyValueConsulClient.java:147)
#19 89.01 	at com.ecwid.consul.v1.ConsulClient.getKVValues(ConsulClient.java:644)
#19 89.01 	at org.springframework.cloud.consul.config.ConsulPropertySource.init(ConsulPropertySource.java:67)
#19 89.01 	at org.springframework.cloud.consul.config.ConsulPropertySources.create(ConsulPropertySources.java:148)
#19 89.01 	at org.springframework.cloud.consul.config.ConsulPropertySources.createPropertySource(ConsulPropertySources.java:127)
#19 89.01 	... 26 more
#19 89.01 Caused by: java.net.UnknownHostException: consul: Name or service not known
#19 89.01 	at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
#19 89.01 	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:933)
#19 89.01 	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519)
#19 89.01 	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852)
#19 89.01 	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
#19 89.02 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1367)
#19 89.02 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1301)
#19 89.02 	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
#19 89.02 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
#19 89.02 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
#19 89.02 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
#19 89.02 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
#19 89.02 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
#19 89.02 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
#19 89.02 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
#19 89.02 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
#19 89.02 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
#19 89.02 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:221)
#19 89.02 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
#19 89.02 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
#19 89.02 	at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:70)
#19 89.02 	... 34 more
```

Our build script:

```
plugins {
     id 'org.springframework.boot' version '2.6.0-SNAPSHOT' apply true     
     id 'org.springframework.experimental.aot' version '0.11.0-SNAPSHOT'
     id 'org.graalvm.buildtools.native' version '0.9.7'    
}

apply from: "../gradle-scripts/build-spring-boot.gradle"

dependencies {
        implementation("org.springframework.boot:spring-boot-starter-data-jpa:${springBootVersion}")
    { exclude group: "org.springframework.boot", module: "spring-boot-starter" }    
}

repositories {
    mavenCentral()
    maven { url 'https://repo.spring.io/release' }
    maven { url 'https://repo.spring.io/snapshot' }
}

```

**Comment by snicoll** [comment]
This is to be expected unfortunately. AOT evaluates condition at build time to build an optimized view of your application, and therefore requires to resolve the environment. If you're default configuration is contacting such as service, it will be resolved at build time. If you don't want that, you need to move this to a profile that you enable only when running the app.

**Comment by sergey-morenets** [comment]
Thank you, @snicoll 

Is it mentioned somewhere in the documentation? Unfortunately I couldn't find that.

**Comment by snicoll** [comment]
https://docs.spring.io/spring-native/docs/0.11.0-RC1/reference/htmlsingle/#spring-aot
