### ISSUE TITLE
Spring Boot cannot build a Java 17 native Docker image because native-image is failing to unresolved method

### ISSUE THREAD

**Issue by Nikolas-Charalambidis** [spring-projects-experimental/spring-native#1286]
I have a simple Spring Boot application using Java 17 and Maven with the following dependencies I would like to build using `spring-boot-maven-plugin` as a native Docker image. The parent version is `2.6.0`:
- `org.springframework.boot`:`spring-boot-starter-data-r2dbc`
- `org.springframework.boot`:`spring-boot-starter-webflux`
- `org.springframework.boot`:`spring-boot-starter-actuator`
- `org.springframework.experimental`:`spring-native` (from `org.springframework.experimental`)
- `io.r2dbc`:`r2dbc-postgresql`

I also use `org.springframework.experimental`:`spring-native` version `0.11.0-M1` as I have found information Java 17 is supported as of `0.11.X` baseline.

I attempt to build a native Docker image using Packeto (that uses GraalVM) using the following command but the image cannot be built due to the error below:

```
./mvnw.cmd spring-boot:build-image -DskipTests
```
(The full error can be found here: [log.txt](https://github.com/spring-projects-experimental/spring-native/files/7566423/log.txt))

```
[INFO]     [creator]     [/layers/paketo-buildpacks_native-image/native-image/sandbox.Application:183]    classlist:   6,694.82 ms,  0.94 GB
[INFO]     [creator]     [/layers/paketo-buildpacks_native-image/native-image/sandbox.Application:183]        (cap):   1,798.10 ms,  0.94 GB
[INFO]     [creator]     [/layers/paketo-buildpacks_native-image/native-image/sandbox.Application:183]        setup:   5,766.55 ms,  0.94 GB
[INFO]     [creator]     [/layers/paketo-buildpacks_native-image/native-image/sandbox.Application:183]     analysis:  12,186.03 ms,  1.50 GB
[INFO]     [creator]     Fatal error:com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing org.springframework.beans.TypeConverterDelegate.convertIfNecessary(java.lang.String, java.lang.Object, java.lang.Object,
 java.lang.Class, org.springframework.core.convert.TypeDescriptor)
[INFO]     [creator]     Parsing context:
[INFO]     [creator]        at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:119)
[INFO]     [creator]        at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:73)
[INFO]     [creator]        at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:45)
```
...
```
[INFO]     [creator]     Caused by: com.oracle.graal.pointsto.util.AnalysisError: parsing had failed in another thread
[INFO]     [creator]            at com.oracle.graal.pointsto.util.AnalysisError.shouldNotReachHere(AnalysisError.java:153)
[INFO]     [creator]            at com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:656)
[INFO]     [creator]            at com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.lookupEncodedGraph(InlineBeforeAnalysis.java:182)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.doInline(PEGraphDecoder.java:1120)
```
...
```
[INFO]     [creator]     Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: org.springframework.beans.BeanUtils$Kot
linDelegate.instantiateClass(java.lang.reflect.Constructor, java.lang.Object[]). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
[INFO]     [creator]            at parsing org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:196)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2624)
[INFO]     [creator]            at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:107)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3485)
```
...
```
[INFO]     [creator]     Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: org.springframework.beans.BeanUtils$KotlinDelegate.instantiateClass(java.lang.reflect.Constructor, ja
va.lang.Object[]). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
[INFO]     [creator]            at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:307)
[INFO]     [creator]            at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedMethod(SharedGraphBuilderPhase.java:298)
[INFO]     [creator]            at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedInvoke(SharedGraphBuilderPhase.java:252)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1677)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1652)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5419)
[INFO]     [creator]            at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3477)
[INFO]     [creator]            ... 39 more
```

Here is the full build configuration: 

```
<build>
	<finalName>spring-boot-reactive</finalName>
	<plugins>
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
			<configuration>
				<image>
					<builder>paketobuildpacks/builder:tiny</builder>
					<env>
						<BP_BOOT_NATIVE_IMAGE>1</BP_BOOT_NATIVE_IMAGE>
						<BP_BOOT_NATIVE_IMAGE_BUILD_ARGUMENTS>-Dspring.spel.ignore=true</BP_BOOT_NATIVE_IMAGE_BUILD_ARGUMENTS>
					</env>
					<buildpacks>
						<buildpack>gcr.io/paketo-buildpacks/java-native-image:5.12.0</buildpack>
					</buildpacks>
				</image>
			</configuration>
		</plugin>

	</plugins>
</build>
```

What's wrong? How can I build a native Docker image using Spring Boot 2.6.X and Java 17?

**Comment by sdeleuze** [comment]
Please use at least 0.11.0-M2 for Java 17 support.

**Comment by Nikolas-Charalambidis** [comment]
@sdeleuze Thanks for a quick answer. I have updated to `0.11.0-M2` but the very same error remains.

**Comment by Nikolas-Charalambidis** [comment]
@sdeleuze Would you reopen this issue?

**Comment by sdeleuze** [comment]
We validate all our samples with Java 17 now, and the build is green with `0.11.0-SNAPSHOT` as well as with `0.11.0-RC1`. Please provide a repro in order to allow me to check if your use case require us to fix something.

**Comment by Nikolas-Charalambidis** [comment]
@sdeleuze I have created a repository where I reproduce the error. Please, check it out: https://github.com/Nikolas-Charalambidis/spring-native-1286. The error can be also seen in Github Actions build: https://github.com/Nikolas-Charalambidis/spring-native-1286/runs/4494241258?check_suite_focus=true

**Comment by Nikolas-Charalambidis** [comment]
@sdeleuze Would you take a look at the issue in my repository where I reproduce it?

**Comment by sdeleuze** [comment]
@Nikolas-Charalambidis You have not configured `spring-aot-maven-plugin`, see [related documentation ](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#_add_the_spring_aot_plugin).

**Comment by Nikolas-Charalambidis** [comment]
@sdeleuze The missing plugin fixed my issue. I have missed the plugin in the documentation. Thanks a lot!
