### ISSUE TITLE
Docker aborts image build when using native image to build (0.11.0-RC1)

### ISSUE THREAD

**Issue by SentryMan** [spring-projects-experimental/spring-native#1293]
Yeah, so I'm trying to build my app with the new release of spring native, but docker is aborting the build with the below error. here is my docker file, please inform if I have made any misstep. https://github.com/SentryMan/Manga-Spring-Backend/blob/jdk-17/Dockerfile

also here is my pom file. https://github.com/SentryMan/Manga-Spring-Backend/blob/jdk-17/pom.xml

```
#10 614.4 === Image generator watchdog detected no activity. This can be a sign of a deadlock during image building. Dumping all stack traces. Current time:  
Sun Nov 21 23:13:24 UTC 2021
#10 617.9 "main" Id=1 in RUNNABLE
#10 617.9     at app//com.oracle.svm.hosted.ResourcesFeature.matches(ResourcesFeature.java:343)
#10 617.9     at app//com.oracle.svm.hosted.ResourcesFeature.scanDirectory(ResourcesFeature.java:288)
#10 617.9     at app//com.oracle.svm.hosted.ResourcesFeature.lambda$duringAnalysis$2(ResourcesFeature.java:226)
#10 617.9     at app//com.oracle.svm.hosted.ResourcesFeature$$Lambda$1592/0x00000007c1c37a10.accept(Unknown Source)
#10 617.9     at java.base@17.0.1/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
#10 617.9     at java.base@17.0.1/java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:174)
#10 617.9     at java.base@17.0.1/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
#10 617.9     at java.base@17.0.1/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
#10 617.9     at java.base@17.0.1/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
#10 617.9     at java.base@17.0.1/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
#10 617.9     at java.base@17.0.1/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
#10 617.9     at java.base@17.0.1/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
#10 617.9     at java.base@17.0.1/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
#10 617.9     at java.base@17.0.1/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
#10 617.9     at app//com.oracle.svm.hosted.ResourcesFeature.duringAnalysis(ResourcesFeature.java:223)
#10 617.9     at app//com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$12(NativeImageGenerator.java:727)
#10 617.9     at app//com.oracle.svm.hosted.NativeImageGenerator$$Lambda$1559/0x00000007c1b9d7f8.accept(Unknown Source)
#10 617.9     at app//com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:73)
#10 617.9     at app//com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:727)
#10 617.9     at app//com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:529)
#10 617.9     at app//com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
#10 617.9     at app//com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
#10 617.9     at app//com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
#10 617.9     at app//com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
#10 617.9     at app//com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)
#10 617.9
#10 617.9 "Reference Handler" Id=2 in RUNNABLE
#10 617.9     at java.base@17.0.1/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
#10 617.9     at java.base@17.0.1/java.lang.ref.Reference.processPendingReferences(Reference.java:253)
#10 617.9     at java.base@17.0.1/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:215)
#10 617.9
#10 617.9 "Finalizer" Id=3 in WAITING on lock=java.lang.ref.ReferenceQueue$Lock@6c9bda28
#10 617.9     at java.base@17.0.1/java.lang.Object.wait(Native Method)
#10 617.9     at java.base@17.0.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
#10 617.9     at java.base@17.0.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
#10 617.9     at java.base@17.0.1/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:172)
#10 617.9
#10 617.9 "Signal Dispatcher" Id=4 in RUNNABLE
#10 617.9
#10 617.9 "JVMCI-native CompilerThread0" Id=7 in RUNNABLE
#10 617.9
#10 617.9 "Common-Cleaner" Id=10 in TIMED_WAITING on lock=java.lang.ref.ReferenceQueue$Lock@68a45363
#10 617.9     at java.base@17.0.1/java.lang.Object.wait(Native Method)
#10 617.9     at java.base@17.0.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
#10 617.9     at java.base@17.0.1/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
#10 617.9     at java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
#10 617.9     at java.base@17.0.1/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:162)
#10 617.9
#10 617.9 "Notification Thread" Id=11 in RUNNABLE
#10 617.9
#10 617.9 "native-image pid watcher" Id=15 in TIMED_WAITING on lock=java.util.TaskQueue@2da6d013
#10 617.9     at java.base@17.0.1/java.lang.Object.wait(Native Method)
#10 617.9     at java.base@17.0.1/java.util.TimerThread.mainLoop(Timer.java:563)
#10 617.9     at java.base@17.0.1/java.util.TimerThread.run(Timer.java:516)
#10 617.9
#10 617.9 "ForkJoinPool.commonPool-worker-2" Id=25 in TIMED_WAITING on lock=java.util.concurrent.ForkJoinPool@395814f
#10 617.9     at java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method)
#10 617.9     at java.base@17.0.1/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:410)
#10 617.9     at java.base@17.0.1/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1726)
#10 617.9     at java.base@17.0.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1623)
#10 617.9     at java.base@17.0.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
#10 617.9
#10 617.9 "Libgraal MBean Registration" Id=35 in TIMED_WAITING
#10 617.9     at java.base@17.0.1/java.lang.Thread.sleep(Native Method)
#10 617.9     at platform/jdk.internal.vm.compiler.management/org.graalvm.compiler.hotspot.management.Factory.run(Factory.java:111)
#10 617.9
#10 617.9 "Thread-1" Id=36 in RUNNABLE
#10 617.9     at java.management@17.0.1/sun.management.ThreadImpl.dumpThreads0(Native Method)
#10 617.9     at java.management@17.0.1/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:521)
#10 617.9     at java.management@17.0.1/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:509)
#10 617.9     at app//com.oracle.svm.hosted.DeadlockWatchdog.threadDump(DeadlockWatchdog.java:113)
#10 617.9     at app//com.oracle.svm.hosted.DeadlockWatchdog.watchdogThread(DeadlockWatchdog.java:80)
#10 617.9     at app//com.oracle.svm.hosted.DeadlockWatchdog$$Lambda$144/0x00000007c169c8b0.run(Unknown Source)
#10 617.9     at java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
#10 617.9
#10 617.9 "ForkJoinPool-2-worker-1" Id=38 in WAITING on lock=java.util.concurrent.ForkJoinPool@2e39e914
#10 617.9     at java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method)
#10 617.9     at java.base@17.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
#10 617.9     at java.base@17.0.1/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1724)
#10 617.9     at java.base@17.0.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1623)
#10 617.9     at java.base@17.0.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
#10 617.9
#10 617.9 "ForkJoinPool-2-worker-5" Id=43 in WAITING on lock=java.util.concurrent.ForkJoinPool@2e39e914
#10 617.9     at java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method)
#10 617.9     at java.base@17.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
#10 617.9     at java.base@17.0.1/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1724)
#10 617.9     at java.base@17.0.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1623)
#10 617.9     at java.base@17.0.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
#10 617.9
#10 617.9 "Timer-0" Id=57 in TIMED_WAITING on lock=java.util.TaskQueue@1cc13c61
#10 617.9     at java.base@17.0.1/java.lang.Object.wait(Native Method)
#10 617.9     at java.base@17.0.1/java.util.TimerThread.mainLoop(Timer.java:563)
#10 617.9     at java.base@17.0.1/java.util.TimerThread.run(Timer.java:516)
#10 617.9
#10 617.9 "ForkJoinPool-2-worker-9" Id=61 in TIMED_WAITING on lock=java.util.concurrent.ForkJoinPool@2e39e914
#10 617.9     at java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method)
#10 617.9     at java.base@17.0.1/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:410)
#10 617.9     at java.base@17.0.1/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1726)
#10 617.9     at java.base@17.0.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1623)
#10 617.9
#10 617.9
#10 617.9 === Memory statistics (in MB):
#10 617.9 === Used heap size: 10103
#10 617.9 === Free heap size: 199
#10 617.9 === Maximum heap size: 10103
#10 617.9 === Image generator watchdog is aborting image generation. To configure the watchdog, use the options -H:DeadlockWatchdogInterval=10 and -H:+DeadlockWatchdogExitOnTimeout
#10 624.3 Error: Image build request failed with exit status 1
------
```

**Comment by sdeleuze** [comment]
I tried to build your app with `mvn spring-boot:build-image` and it seems to work as expected, so I suspect something is wrong in your custom `Dockerfile`. Maybe for that kind of image you should refer to https://www.graalvm.org/reference-manual/native-image/StaticImages/#build-mostly-static-native-image. If you can't make it work with your custom `Dockerfile`, I would suggest to use `mvn spring-boot:build-image` which is designed to avoid this kind of issues.
