### ISSUE TITLE
Possible regression from 0.10.5 regarding management port setting

### ISSUE THREAD

**Issue by kwencel** [spring-projects-experimental/spring-native#1302]
I have noticed that when running a native image of a Spring Boot 2.6.0 app with `id("org.springframework.experimental.aot") version "0.11.0-RC1"` plugin enabled in Gradle, run with the following arguments:
```
-Duser.timezone=Europe/Warsaw
-Duser.language=pl
-Duser.country=PL
-Dcom.sun.management.jmxremote.port=3000
-Dcom.sun.management.jmxremote.rmi.port=3000
-Dcom.sun.management.jmxremote.authenticate=false
-Dcom.sun.management.jmxremote.ssl=false
-Djava.rmi.server.hostname=127.0.0.1
-Dcom.sun.management.jmxremote.local.only=true
-Dserver.address=0.0.0.0
-Dserver.port=8080
-Dmanagement.server.address=0.0.0.0
-Dmanagement.server.port=8081
-Dmanagement.endpoints.web.base-path=/
-Dspring.config.additional-location=/app/config/
-Dspring.profiles.active=k8s
```
shows the following exception on startup and the application stops:
```
java.lang.IllegalStateException: Management-specific server address cannot be configured as the management server is not listening on a separate port
    at org.springframework.util.Assert.state(Assert.java:76) ~[na:na]
    at org.springframework.boot.actuate.autoconfigure.web.server.ManagementContextAutoConfiguration$SameManagementContextConfiguration.verifyAddressConfiguration(ManagementContextAutoConfiguration.java:90) ~[<redacted>]
    at org.springframework.boot.actuate.autoconfigure.web.server.ManagementContextAutoConfiguration$SameManagementContextConfiguration.afterSingletonsInstantiated(ManagementContextAutoConfiguration.java:76) ~[<redacted>]
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:963) ~[na:na]
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[na:na]
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[na:na]
    at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:64) ~[na:na]
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[<redacted>:2.6.0]
    at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412) ~[<redacted>:2.6.0]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) ~[<redacted>:2.6.0]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[<redacted>:2.6.0]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1290) ~[<redacted>:2.6.0]
    at <redacted>.main(Application.kt:51) ~[na:na]
```

It does not happen on 0.10.5 and Spring Boot 2.5.6, therefore I believe there is a regression of some kind.

I have also tested a 0.11.0-RC1 and Spring Boot 2.5.6 combination. I know it is not recommended but I wanted to rule out the possibility that Spring Boot 2.6.0 is a problem here. The problem has also manifested in that configuration, which suggests that there is an issue introduced in the 0.11.0 version.

**Comment by snicoll** [comment]
I am afraid this is the expected behavior. The improvements in terms of build time, startup time, and RSS memory are due to the new AOT engine that has been designed in 0.11. Such engine processes condition at build-time and therefore the fact that a separate management port is required should be set at build-time so that the appropriate infrastructure is generated.

See also [this note in the documentation](https://docs.spring.io/spring-native/docs/current-SNAPSHOT/reference/htmlsingle/#spring-aot).

**Comment by magnus-larsson** [comment]
If anyone, like me, reads about this problem and wonders how to specify "_the fact that a separate management port is required_" at build-time, I recommend setting the property `management.server.port` to a random value in the standard property file (e.g. `src/main/resources/application.yml`). When the AOT engine sees this property it will generate "_the appropriate infrastructure_".

At runtime, the desired management port can be specified using the existing mechanisms.

Also, the link above seems to be outdated, instead I recommend reading this documentation [Spring Native v0.12.1 - AOT engine](https://docs.spring.io/spring-native/docs/0.12.1/reference/htmlsingle/#aot-engine).
