### ISSUE TITLE
org.hibernate.validator.constraints.CodePointLength$NormalizationStrategy was unintentionally initialized at build time

### ISSUE THREAD

**Issue by julb** [spring-projects-experimental/spring-native#1305]
Dear Spring team,

Thanks for what you are doing, that's an awesome job!

I tried to compile a Spring Cloud Function as native.
The build was working file, but started to fail as soon as I add dependency to spring-boot-starter-validation.

Using: GraalVM 21.3.0, Java 17 and 0.11.0-RC1.

Here is the output:
```
[native-image-plugin] Using executable path: /home/julb/.sdkman/candidates/java/21.3.0.r17-grl/bin/native-image
[fun-gen-uuid:9914]    classlist:   4,664.61 ms,  0.96 GB
09:41:53.940 [main] DEBUG org.jboss.logging - Logging Provider: org.jboss.logging.Log4j2LoggerProvider
[fun-gen-uuid:9914]        (cap):     866.30 ms,  0.96 GB
[fun-gen-uuid:9914]        setup:   3,829.01 ms,  0.96 GB
The bundle named: org.apache.tomcat.util.threads.res.LocalStrings, has not been found. If the bundle is part of a module, verify the bundle name is a fully qualified class name. Otherwise verify the bundle path is accessible in the classpath.
Warning: Could not register complete reflection metadata for org.springframework.boot.autoconfigure.session.JdbcSessionProperties. Reason(s): java.lang.NoClassDefFoundError: org/springframework/session/FlushMode
Warning: Could not register complete reflection metadata for org.springframework.boot.autoconfigure.cassandra.CassandraProperties$Request. Reason(s): java.lang.NoClassDefFoundError: com/datastax/oss/driver/api/core/DefaultConsistencyLevel
Warning: Could not register complete reflection metadata for org.springframework.boot.autoconfigure.r2dbc.R2dbcProperties$Pool. Reason(s): java.lang.NoClassDefFoundError: io/r2dbc/spi/ValidationDepth
Warning: Could not register complete reflection metadata for org.springframework.boot.autoconfigure.kafka.KafkaProperties$Jaas. Reason(s): java.lang.NoClassDefFoundError: org/springframework/kafka/security/jaas/KafkaJaasLoginModuleInitializer$ControlFlag
Warning: Could not register complete reflection metadata for org.springframework.boot.autoconfigure.security.saml2.Saml2RelyingPartyProperties$Registration$Acs. Reason(s): java.lang.NoClassDefFoundError: org/springframework/security/saml2/provider/service/registration/Saml2MessageBinding
Warning: Could not register complete reflection metadata for org.springframework.boot.autoconfigure.jooq.JooqProperties. Reason(s): java.lang.NoClassDefFoundError: org/jooq/SQLDialect
Warning: Could not register complete reflection metadata for org.springframework.boot.autoconfigure.mongo.MongoProperties. Reason(s): java.lang.NoClassDefFoundError: org/bson/UuidRepresentation
Warning: Could not register complete reflection metadata for org.springframework.boot.autoconfigure.amqp.RabbitProperties. Reason(s): java.lang.NoClassDefFoundError: org/springframework/amqp/rabbit/connection/AbstractConnectionFactory$AddressShuffleMode
Warning: Could not register complete reflection metadata for org.springframework.boot.autoconfigure.session.RedisSessionProperties. Reason(s): java.lang.NoClassDefFoundError: org/springframework/session/FlushMode
Warning: Could not register complete reflection metadata for org.springframework.boot.autoconfigure.session.HazelcastSessionProperties. Reason(s): java.lang.NoClassDefFoundError: org/springframework/session/FlushMode
Warning: Could not register complete reflection metadata for org.springframework.boot.autoconfigure.amqp.RabbitProperties$SimpleContainer. Reason(s): java.lang.NoClassDefFoundError: org/springframework/amqp/core/AcknowledgeMode
Warning: Could not register complete reflection metadata for org.springframework.boot.autoconfigure.kafka.KafkaProperties$Listener. Reason(s): java.lang.NoClassDefFoundError: org/springframework/kafka/listener/ContainerProperties$AckMode
Warning: Could not register complete reflection metadata for org.springframework.boot.autoconfigure.amqp.RabbitProperties$Cache$Connection. Reason(s): java.lang.NoClassDefFoundError: org/springframework/amqp/rabbit/connection/CachingConnectionFactory$CacheMode
Warning: Could not register complete reflection metadata for org.springframework.boot.autoconfigure.amqp.RabbitProperties$AmqpContainer. Reason(s): java.lang.NoClassDefFoundError: org/springframework/amqp/core/AcknowledgeMode
Warning: Could not register complete reflection metadata for org.springframework.boot.autoconfigure.gson.GsonProperties. Reason(s): java.lang.NoClassDefFoundError: com/google/gson/LongSerializationPolicy
Warning: Could not register complete reflection metadata for org.springframework.boot.autoconfigure.amqp.RabbitProperties$DirectContainer. Reason(s): java.lang.NoClassDefFoundError: org/springframework/amqp/core/AcknowledgeMode
Warning: Could not register complete reflection metadata for org.springframework.boot.autoconfigure.orm.jpa.JpaProperties. Reason(s): java.lang.NoClassDefFoundError: org/springframework/orm/jpa/vendor/Database
Warning: Could not register complete reflection metadata for org.springframework.boot.autoconfigure.data.rest.RepositoryRestProperties. Reason(s): java.lang.NoClassDefFoundError: org/springframework/data/rest/core/mapping/RepositoryDetectionStrategy$RepositoryDetectionStrategies, java.lang.NoClassDefFoundError: org/springframework/data/rest/core/config/RepositoryRestConfiguration
Warning: Could not register complete reflection metadata for org.springframework.boot.autoconfigure.security.saml2.Saml2RelyingPartyProperties$Identityprovider$Singlesignon. Reason(s): java.lang.NoClassDefFoundError: org/springframework/security/saml2/provider/service/registration/Saml2MessageBinding
[fun-gen-uuid:9914]     analysis:  59,613.40 ms,  4.66 GB
Error: Classes that should be initialized at run time got initialized during image building:
 org.hibernate.validator.constraints.CodePointLength$NormalizationStrategy was unintentionally initialized at build time. org.hibernate.validator.constraints.CodePointLength$NormalizationStrategy caused initialization of this class with the following trace:
        at org.hibernate.validator.constraints.CodePointLength$NormalizationStrategy.<clinit>(CodePointLength.java:77)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Unknown Source)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:568)
[fun-gen-uuid:9914]     at java.lang.Class.getEnumConstantsShared(Class.java:3837)
     [total]:   at java.lang.Class.enumConstantDirectory(Class.java:3859)
 68,562.02 ms,  4.66 GB
        at java.lang.Enum.valueOf(Enum.java:267)
        at sun.reflect.annotation.AnnotationParser.parseEnumValue(AnnotationParser.java:479)
        at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:344)
        at java.lang.reflect.Method.getDefaultValue(Method.java:717)
        at com.oracle.svm.reflect.target.Target_java_lang_reflect_Method$DefaultValueComputer.compute(Target_java_lang_reflect_Method.java:117)
        at com.oracle.svm.hosted.substitute.ComputedValueField.readValue(ComputedValueField.java:277)
        at com.oracle.svm.core.meta.ReadableJavaField.readFieldValue(ReadableJavaField.java:36)
        at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:99)
        at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:81)
        at com.oracle.graal.pointsto.ObjectScanner.scanField(ObjectScanner.java:160)
        at com.oracle.graal.pointsto.ObjectScanner.doScan(ObjectScanner.java:333)
        at com.oracle.graal.pointsto.ObjectScanner.lambda$scanConstant$6(ObjectScanner.java:259)
        at com.oracle.graal.pointsto.ObjectScanner$$Lambda$1052/0x00000007c1814b48.run(Unknown Source)
        at com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:188)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:172)
        at com.oracle.graal.pointsto.util.CompletionExecutor$$Lambda$608/0x00000007c1788c78.run(Unknown Source)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.util.concurrent.ForkJoinPool.externalHelpQuiescePool(ForkJoinPool.java:2104)
        at java.util.concurrent.ForkJoinPool.awaitQuiescence(ForkJoinPool.java:3321)
        at com.oracle.graal.pointsto.util.CompletionExecutor.complete(CompletionExecutor.java:238)
        at com.oracle.graal.pointsto.PointsToAnalysis.checkObjectGraph(PointsToAnalysis.java:680)
        at com.oracle.graal.pointsto.PointsToAnalysis.finish(PointsToAnalysis.java:644)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:704)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:529)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)
# Printing build artifacts to: /home/julb/projects/assets/applications/fun-gen-uuid/build/native/nativeCompile/fun-gen-uuid.build_artifacts.txt


com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 org.hibernate.validator.constraints.CodePointLength$NormalizationStrategy was unintentionally initialized at build time. org.hibernate.validator.constraints.CodePointLength$NormalizationStrategy caused initialization of this class with the following trace:
        at org.hibernate.validator.constraints.CodePointLength$NormalizationStrategy.<clinit>(CodePointLength.java:77)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Unknown Source)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:568)
        at java.lang.Class.getEnumConstantsShared(Class.java:3837)
        at java.lang.Class.enumConstantDirectory(Class.java:3859)
        at java.lang.Enum.valueOf(Enum.java:267)
        at sun.reflect.annotation.AnnotationParser.parseEnumValue(AnnotationParser.java:479)
        at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:344)
        at java.lang.reflect.Method.getDefaultValue(Method.java:717)
        at com.oracle.svm.reflect.target.Target_java_lang_reflect_Method$DefaultValueComputer.compute(Target_java_lang_reflect_Method.java:117)
        at com.oracle.svm.hosted.substitute.ComputedValueField.readValue(ComputedValueField.java:277)
        at com.oracle.svm.core.meta.ReadableJavaField.readFieldValue(ReadableJavaField.java:36)
        at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:99)
        at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:81)
        at com.oracle.graal.pointsto.ObjectScanner.scanField(ObjectScanner.java:160)
        at com.oracle.graal.pointsto.ObjectScanner.doScan(ObjectScanner.java:333)
        at com.oracle.graal.pointsto.ObjectScanner.lambda$scanConstant$6(ObjectScanner.java:259)
        at com.oracle.graal.pointsto.ObjectScanner$$Lambda$1052/0x00000007c1814b48.run(Unknown Source)
        at com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:188)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:172)
        at com.oracle.graal.pointsto.util.CompletionExecutor$$Lambda$608/0x00000007c1788c78.run(Unknown Source)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.util.concurrent.ForkJoinPool.externalHelpQuiescePool(ForkJoinPool.java:2104)
        at java.util.concurrent.ForkJoinPool.awaitQuiescence(ForkJoinPool.java:3321)
        at com.oracle.graal.pointsto.util.CompletionExecutor.complete(CompletionExecutor.java:238)
        at com.oracle.graal.pointsto.PointsToAnalysis.checkObjectGraph(PointsToAnalysis.java:680)
        at com.oracle.graal.pointsto.PointsToAnalysis.finish(PointsToAnalysis.java:644)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:704)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:529)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)


        at com.oracle.svm.core.util.UserError.abort(UserError.java:73)
        at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:555)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:168)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$12(NativeImageGenerator.java:727)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:73)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:727)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:529)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)
Error: Image build request failed with exit status 1
```

Note: I get it working by adding this in my `build.gradle`:
```
graalvmNative {
    binaries {
        main {
            buildArgs.add('--initialize-at-build-time=org.hibernate.validator.constraints.CodePointLength$NormalizationStrategy')
        }
    }
}
```

Thanks for your help.

**Comment by julb** [comment]
Note that I retry with the 0.11.0-SNAPSHOT version built from `main` and the problem has gone.
Seems to be fixed, but don't know why.

**Comment by sdeleuze** [comment]
Thanks for the update, please reopen if you know how to reproduce.

**Comment by FalkWoldmann6232** [comment]
Hi. The same issue occurs for me when using graalvm 21.3, spring native 0.11.3-SNAPSHOT, spring cloud function 3.2.3-SNAPSHOT and kotlin 1.6 while building with gradle.

This is my build.gradle.kts

```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import org.springframework.boot.gradle.tasks.bundling.BootBuildImage

val javaVersion = "11"

plugins {
    val kotlinVersion = "1.6.10"

    id("org.springframework.boot") version "2.6.4-SNAPSHOT"
    id("io.spring.dependency-management") version "1.0.11.RELEASE"
    kotlin("jvm") version kotlinVersion
    kotlin("plugin.spring") version kotlinVersion
    id("org.springframework.experimental.aot") version "0.11.3-SNAPSHOT"
}


group = "com.example"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.toVersion(javaVersion)

repositories {
    maven { url = uri("https://repo.spring.io/snapshot") }
    mavenCentral()
    maven { url = uri("https://repo.spring.io/milestone") }
}

extra["springCloudVersion"] = "2021.0.2-SNAPSHOT"
extra["testcontainersVersion"] = "1.16.2"
extra["log4jVersion"] = "2.17.1"


dependencies {
    implementation(platform("software.amazon.awssdk:bom:2.17.134"))

    implementation("org.springframework.boot:spring-boot-starter-data-mongodb")
    implementation("org.springframework.boot:spring-boot-starter-validation")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("org.springframework.cloud:spring-cloud-function-context")
    implementation("org.springframework.cloud:spring-cloud-function-adapter-aws")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310")
    implementation("software.amazon.awssdk:ssm")

    implementation("com.amazonaws:aws-lambda-java-events:3.11.0")
    implementation("com.amazonaws:aws-lambda-java-log4j2:1.5.1")
    implementation("io.github.microutils:kotlin-logging-jvm:2.1.21")
    implementation("org.apache.logging.log4j:log4j-api:${property("log4jVersion")}")
    implementation("org.apache.logging.log4j:log4j-to-slf4j:${property("log4jVersion")}")


    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("org.testcontainers:junit-jupiter")
    testImplementation("org.testcontainers:mongodb")
}

dependencyManagement {
    imports {
        mavenBom("org.testcontainers:testcontainers-bom:${property("testcontainersVersion")}")
        mavenBom("org.springframework.cloud:spring-cloud-dependencies:${property("springCloudVersion")}")
    }
}

tasks.withType<KotlinCompile> {
    kotlinOptions {
        freeCompilerArgs = listOf("-Xjsr305=strict")
        jvmTarget = javaVersion
    }
}

tasks.withType<Test> {
    useJUnitPlatform()
}


tasks.withType<BootBuildImage> {
    builder = "paketobuildpacks/builder:tiny"
    environment = mapOf("BP_NATIVE_IMAGE" to "true")
}
```

**Comment by sdeleuze** [comment]
@FalkWoldmann6232 Please provide a repro project.

**Comment by FalkWoldmann6232** [comment]
Sadly, I cannot reproduce the issue anymore since the build including starter-validation is now working just fine
