### ISSUE TITLE
AOT test code gen fails when same name test classes exist in different package

### ISSUE THREAD

**Issue by ttddyy** [spring-projects-experimental/spring-native#1313]
When there are test classes with the same name in different packages that have independent `MergedContextConfiguration`, the AOT test code generation fails.

For example, if `MyTest` class exists in `com.example.foo` and `com.example.bar` packages, the following exception is thrown.

```
java.lang.IllegalArgumentException: context with id 'MyTestContextInitializer' already exists
	at org.springframework.aot.context.bootstrap.generator.infrastructure.DefaultBootstrapWriterContext.fork(DefaultBootstrapWriterContext.java:129)
	at org.springframework.aot.context.bootstrap.generator.infrastructure.DefaultBootstrapWriterContext.fork(DefaultBootstrapWriterContext.java:123)
	at org.springframework.aot.test.context.bootstrap.generator.TestContextAotProcessor.generateTestContext(TestContextAotProcessor.java:107)
	at org.springframework.aot.test.context.bootstrap.generator.TestContextAotProcessor.generateTestContexts(TestContextAotProcessor.java:78)
	at org.springframework.aot.test.build.TestContextBootstrapContributor.contribute(TestContextBootstrapContributor.java:61)
	at org.springframework.aot.build.BootstrapCodeGenerator.generate(BootstrapCodeGenerator.java:89)
	at org.springframework.aot.build.BootstrapCodeGenerator.generate(BootstrapCodeGenerator.java:68)
	at org.springframework.aot.test.build.GenerateTestBootstrapCommand.call(GenerateTestBootstrapCommand.java:87)
	at org.springframework.aot.test.build.GenerateTestBootstrapCommand.call(GenerateTestBootstrapCommand.java:45)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
```

This is because when a `MergedContextConfiguration` is different, `TestContextConfigurationDescriptorFactory` creates different `TestContextConfigurationDescriptor`s. When this descriptor contains a single test class, it uses the test class name(`MyTestContextInitializer` in this case) as a map key:
https://github.com/spring-projects-experimental/spring-native/blob/d8adb77be77da3f07a18dc95d54a8fec839edb0a/spring-aot-test/src/main/java/org/springframework/aot/test/context/bootstrap/generator/TestContextAotProcessor.java#L149-L153
https://github.com/spring-projects-experimental/spring-native/blob/d8adb77be77da3f07a18dc95d54a8fec839edb0a/spring-aot-test/src/main/java/org/springframework/aot/test/context/bootstrap/generator/TestContextAotProcessor.java#L106-L107

Then, in the `fork` method, the unique check(`this.allContexts.containsKey(id))`) is failing since the test classes in both test descriptors have the same name:
https://github.com/spring-projects-experimental/spring-native/blob/2833e110534bce100820faac881932ca0ae5535e/spring-aot/src/main/java/org/springframework/aot/context/bootstrap/generator/infrastructure/DefaultBootstrapWriterContext.java#L127-L134

In this case, the key needs to be a unique valid java class name.

**Comment by sdeleuze** [comment]
@snicoll Should we consider this one for for `0.11.0.`?

**Comment by snicoll** [comment]
Yes
