### ISSUE TITLE
MockitoPostProcessor should be disabled in AOT since not supported yet

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#1343]
While working on #1084 updated to Spring Native `0.11.0-SNAPSHOT` and following the same repro instructions with https://github.com/sdeleuze/spring-cloud-stream-event-routing-cloudevents, I see the following error during AOT code generation:

```
2021-12-06 08:23:22.861  INFO 20452 --- [           main] .b.t.c.SpringBootTestContextBootstrapper : Found @SpringBootConfiguration com.mycompany.producerservice.ProducerServiceApplication for test class com.mycompany.producerservice.kafka.news.NewsEventProducerTest
java.lang.IllegalArgumentException: Code should not be empty
	at org.springframework.aot.context.bootstrap.generator.bean.support.MultiCodeBlock.add(MultiCodeBlock.java:53)
	at org.springframework.aot.context.bootstrap.generator.bean.support.MultiCodeBlock.add(MultiCodeBlock.java:44)
	at org.springframework.aot.context.bootstrap.generator.bean.support.ParameterWriter.lambda$writeAll$10(ParameterWriter.java:174)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.aot.context.bootstrap.generator.bean.support.ParameterWriter.writeAll(ParameterWriter.java:174)
	at org.springframework.aot.context.bootstrap.generator.bean.support.ParameterWriter.writeParameterValue(ParameterWriter.java:127)
	at org.springframework.aot.context.bootstrap.generator.bean.support.ParameterWriter.writeParameterValue(ParameterWriter.java:79)
	at org.springframework.aot.context.bootstrap.generator.bean.support.ParameterWriter.writeParameterValue(ParameterWriter.java:68)
	at org.springframework.aot.context.bootstrap.generator.bean.DefaultBeanRegistrationWriter.writeArgumentValue(DefaultBeanRegistrationWriter.java:258)
	at org.springframework.aot.context.bootstrap.generator.bean.DefaultBeanRegistrationWriter.handleArgumentValues(DefaultBeanRegistrationWriter.java:242)
	at org.springframework.aot.context.bootstrap.generator.bean.DefaultBeanRegistrationWriter.handleBeanDefinitionMetadata(DefaultBeanRegistrationWriter.java:222)
```

Any thoughts @snicoll ?

**Comment by snicoll** [comment]
Yes. One parameter there is not supported, I'll have a look.

**Comment by snicoll** [comment]
That's `MockitoPostProcessor` that contains a set of `Definition` and these are quite complex so I don't think it is reasonable to pre-process them at build time. I'll see what  we can do.

**Comment by snicoll** [comment]
So I've managed to disable it but as we don't trigger any initializer at runtime anymore, the infrastructure is not created at all and it fails with:

```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.boot.test.mock.mockito.MockitoPostProcessor' available

	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:351)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:342)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1172)
	at org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener.postProcessFields(MockitoTestExecutionListener.java:111)
	at org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener.injectFields(MockitoTestExecutionListener.java:94)
	at org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener.prepareTestInstance(MockitoTestExecutionListener.java:61)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:248)
	at org.springframework.test.context.junit.jupiter.SpringExtension.postProcessTestInstance(SpringExtension.java:138)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeTestInstancePostProcessors$8(ClassBasedTestDescriptor.java:363)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.executeAndMaskThrowable(ClassBasedTestDescriptor.java:368)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeTestInstancePostProcessors$9(ClassBasedTestDescriptor.java:363)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
```

Considering that mockito doesn't work in native, it would be nice to go a little further and skip the whole infrastructure but no injection would be equally confusing as this stacktrace IMO.

**Comment by sdeleuze** [comment]
Can be reproduced via https://github.com/ddn4/spring-stocks with `./mvnw -pl :market-service clean package -Pnative -Dspring.aot.debug=true`.

**Comment by sdeleuze** [comment]
Meaningful error messages are now provided when `@MockBean` or `@SpyBean` are used.
