### ISSUE TITLE
Regression in generateAot

### ISSUE THREAD

**Issue by phejl** [spring-projects-experimental/spring-native#1376]
I'll try to provide more details. For now it looks like app compilable in 0.11.0-RC1 can't be compiled with 0.11.0 (after update of AccessBits to TypeAccess) as generateAot task fails.

```
java.lang.IllegalStateException: Failed to introspect Class [org.springframework.core.MethodParameter$KotlinDelegate] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@251a69d7]
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:481)
        at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:321)
        at org.springframework.data.TypeModelProcessor.visitMethodsOfType(TypeModelProcessor.java:154)
        at org.springframework.data.TypeModelProcessor.processType(TypeModelProcessor.java:122)
        at org.springframework.data.TypeModelProcessor.processType(TypeModelProcessor.java:129)
        at org.springframework.data.TypeModelProcessor.processType(TypeModelProcessor.java:129)
        at org.springframework.data.TypeModelProcessor.processType(TypeModelProcessor.java:129)
        at org.springframework.data.TypeModelProcessor.processType(TypeModelProcessor.java:129)
        at org.springframework.data.TypeModelProcessor.processType(TypeModelProcessor.java:129)
        at org.springframework.data.TypeModelProcessor.processType(TypeModelProcessor.java:129)
        at org.springframework.data.TypeModelProcessor.processType(TypeModelProcessor.java:129)
        at org.springframework.data.TypeModelProcessor.processType(TypeModelProcessor.java:129)
        at org.springframework.data.TypeModelProcessor.processType(TypeModelProcessor.java:129)
        at org.springframework.data.TypeModelProcessor.processType(TypeModelProcessor.java:129)
        at org.springframework.data.TypeModelProcessor.processType(TypeModelProcessor.java:129)
        at org.springframework.data.TypeModelProcessor.process(TypeModelProcessor.java:110)
        at org.springframework.data.TypeModelProcessor$TypeModelCollector.forEach(TypeModelProcessor.java:193)
        at org.springframework.data.RepositoryDefinitionConfigurationProcessor$RepositoryConfigurationContributor.writeDomainTypeConfiguration(RepositoryDefinitionConfigurationProcessor.java:297)
        at org.springframework.data.RepositoryDefinitionConfigurationProcessor$RepositoryConfigurationContributor.writeConfiguration(RepositoryDefinitionConfigurationProcessor.java:238)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.springframework.data.RepositoryDefinitionConfigurationProcessor$Processor.process(RepositoryDefinitionConfigurationProcessor.java:101)
        at org.springframework.data.RepositoryDefinitionConfigurationProcessor.process(RepositoryDefinitionConfigurationProcessor.java:88)
        at org.springframework.aot.context.bootstrap.generator.infrastructure.nativex.NativeConfigurationRegistrar.lambda$processBeanFactory$0(NativeConfigurationRegistrar.java:55)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.springframework.aot.context.bootstrap.generator.infrastructure.nativex.NativeConfigurationRegistrar.processBeanFactory(NativeConfigurationRegistrar.java:55)
        at org.springframework.aot.context.bootstrap.generator.ApplicationContextAotProcessor.bootstrapMethod(ApplicationContextAotProcessor.java:107)
        at org.springframework.aot.context.bootstrap.generator.ApplicationContextAotProcessor.process(ApplicationContextAotProcessor.java:95)
        at org.springframework.aot.build.ContextBootstrapContributor.contribute(ContextBootstrapContributor.java:80)
        at org.springframework.aot.build.BootstrapCodeGenerator.generate(BootstrapCodeGenerator.java:91)
        at org.springframework.aot.build.BootstrapCodeGenerator.generate(BootstrapCodeGenerator.java:71)
        at org.springframework.aot.build.GenerateBootstrapCommand.call(GenerateBootstrapCommand.java:107)
        at org.springframework.aot.build.GenerateBootstrapCommand.call(GenerateBootstrapCommand.java:42)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at org.springframework.aot.build.GenerateBootstrapCommand.main(GenerateBootstrapCommand.java:112)
Caused by: java.lang.NoClassDefFoundError: kotlin/reflect/KParameter
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
        at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504)
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:463)
        ... 39 more
Caused by: java.lang.ClassNotFoundException: kotlin.reflect.KParameter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 43 more
```

**Comment by sdeleuze** [comment]
Ok please share a repro and I will have a look.

**Comment by sdeleuze** [comment]
@phejl Could you please share a repro ?

**Comment by phejl** [comment]
@sdeleuze Unfortunately I can't (employer's code). But I'll try to either debug or share some repro case. I just need a bit of a free time. I'm sorry end of year is a bit busy for me.

**Comment by sdeleuze** [comment]
@phejl Hey, any chance you could provide a repro ?

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by phejl** [comment]
@sdeleuze I'm sorry I finally found some time to investigate bit more. It looks like related to Spring Data class where `TypeModelProcessor` is going through types and it gets to `org.springframework.core.MethodParameter` where it tries to get methods of inner class `KotlinDelegate` and fails on `java.lang.NoClassDefFoundError: kotlin/reflect/KParameter`. I think this _might_ have been introduced by  `99e10001d5c3c552b9313faf3c9278b492db56e2`. I can see there is a type filter for `kotlin` package but it does not catch this case where type is `org.springframework.core.MethodParameter$KotlinDelegate`

**Comment by sdeleuze** [comment]
Np, thanks for your feedback. Indeed, could be the cause. Can you craft a repro that we could use to fix this issue?

**Comment by phejl** [comment]
Here it is. The problem is triggered by `IndexResolver` I believe.
[repro.patch.txt](https://github.com/spring-projects-experimental/spring-native/files/7824526/repro.patch.txt)

**Comment by sdeleuze** [comment]
Thanks I can reproduce.
