### ISSUE TITLE
Support scoped beans with proxy mode `ScopedProxyMode.INTERFACES`

### ISSUE THREAD

**Issue by nbruno** [spring-projects-experimental/spring-native#1422]
Currently, only scoped beans with proxy mode `ScopedProxyMode.TARGET_CLASS` are supported. If `ScopedProxyMode.INTERFACES` is used, a warning is printed during AOT generation:

> 2022-01-04 08:55:22.662  WARN 85785 --- [           main] .s.c.a.ScopeNativeConfigurationProcessor : Inferring JDK dynamic proxy for scopedTarget.accessTokenRequest bean annotated with @Scope is not supported yet

This causes a missing proxy at runtime exception. However, a custom `proxy-config.json` can be supplied with the interfaces needed for that proxy, specifically the bean type and the following interfaces:

```
<bean type>
org.springframework.aop.scope.ScopedObject
java.io.Serializable
org.springframework.aop.framework.AopInfrastructureBean
org.springframework.aop.SpringProxy
org.springframework.aop.framework.Advised
org.springframework.core.DecoratingProxy
```

But doing so later fails at runtime with:

```
Caused by: org.springframework.beans.NotWritablePropertyException: Invalid property 'proxyTargetClass' of bean class [com.sun.proxy.$Proxy196]: Bean property 'proxyTargetClass' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
	at org.springframework.beans.BeanWrapperImpl.createNotWritablePropertyException(BeanWrapperImpl.java:243) ~[na:na]
	at org.springframework.beans.AbstractNestablePropertyAccessor.processLocalProperty(AbstractNestablePropertyAccessor.java:432) ~[na:na]
	at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:278) ~[na:na]
	at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:266) ~[na:na]
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:104) ~[na:na]
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:79) ~[na:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1740) ~[na:na]
	... 17 common frames omitted
```

While it is apparent in [the code](https://github.com/spring-projects-experimental/spring-native/blob/e45378d2734bba543447b274d09c3781ba05c7b8/spring-aot/src/main/java/org/springframework/context/annotation/ScopeNativeConfigurationProcessor.java) and logs that this is not yet supported, I did not see an existing issue tracking this. 

If there are any tips as to how to properly configure the JDK proxy, I'd be glad to attempt a pull request.

**Comment by sdeleuze** [comment]
Spring Native is now superseded by Spring Boot 3 official native support, see [the related reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html) for more details.

As a consequence, I am closing this issue, and recommend trying your use case with latest Spring Boot 3 version. If you still experience the issue reported here, please open an issue directly on the related Spring project (Spring Framework, Data, Security, Boot, Cloud, etc.) with a reproducer.

Thanks for your contribution on the experimental Spring Native project, we hope you will enjoy the official native support introduced by Spring Boot 3.
