### ISSUE TITLE
Spring config import vault  - compilation error with GraalVM 21.3.0

### ISSUE THREAD

**Issue by stefferro** [spring-projects-experimental/spring-native#1423]
Hi,

I would like to bring to your attention an issue I am experiencing when building my spring native project over GraalVM 21.3.

See the attached sample project: [sample-project.zip](https://github.com/spring-projects-experimental/spring-native/files/7808162/sample-project.zip)

In this project, I want to validate that a secret can be loaded from a vault and injected into a field. 
It works perfectly fine when I run the application locally 
```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.2)

2022-01-04 10:29:32.529  INFO 12400 --- [           main] com.spf.DemoApplication                  : No active profile set, falling back to default profiles: default
2022-01-04 10:29:33.007  INFO 12400 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=ce9fb587-bddc-3547-96a4-69e256b77739
2022-01-04 10:29:33.179  INFO 12400 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8081 (http)
2022-01-04 10:29:33.187  INFO 12400 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-01-04 10:29:33.187  INFO 12400 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.56]
2022-01-04 10:29:33.288  INFO 12400 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-01-04 10:29:33.288  INFO 12400 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 734 ms
secret = This_Is_A_Secret
2022-01-04 10:29:33.657  INFO 12400 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8081 (http) with context path ''
2022-01-04 10:29:33.783  INFO 12400 --- [           main] com.spf.DemoApplication                  : Started DemoApplication in 2.304 seconds (JVM running for 2.631)

```
We can see the secret 'This_Is_A_Secret' being printed in the log.

But when I build the native image, I get the following error:
```
2022.01.04 11:09:06  [INFO]     [creator]     [/layers/paketo-buildpacks_native-image/native-image/com.spf.DemoApplication:197]     (clinit):   7,213.55 ms,  5.48 GB
2022.01.04 11:09:06  [INFO]     [creator]     [/layers/paketo-buildpacks_native-image/native-image/com.spf.DemoApplication:197]   (typeflow):  45,300.35 ms,  5.48 GB
2022.01.04 11:09:06  [INFO]     [creator]     [/layers/paketo-buildpacks_native-image/native-image/com.spf.DemoApplication:197]    (objects):  57,156.22 ms,  5.48 GB
2022.01.04 11:09:06  [INFO]     [creator]     [/layers/paketo-buildpacks_native-image/native-image/com.spf.DemoApplication:197]   (features):  29,308.13 ms,  5.48 GB
2022.01.04 11:09:06  [INFO]     [creator]     [/layers/paketo-buildpacks_native-image/native-image/com.spf.DemoApplication:197]     analysis: 146,769.14 ms,  5.48 GB
2022.01.04 11:09:15  [INFO]     [creator]     [/layers/paketo-buildpacks_native-image/native-image/com.spf.DemoApplication:197]     universe:  11,999.86 ms,  5.48 GB
2022.01.04 11:09:25  [INFO]     [creator]     [/layers/paketo-buildpacks_native-image/native-image/com.spf.DemoApplication:197]      (parse):   8,523.00 ms,  5.24 GB
2022.01.04 11:09:52  [INFO]     [creator]     [/layers/paketo-buildpacks_native-image/native-image/com.spf.DemoApplication:197]     (inline):  26,957.02 ms,  5.52 GB
2022.01.04 11:10:49  [INFO]     [creator]     [/layers/paketo-buildpacks_native-image/native-image/com.spf.DemoApplication:197]    (compile):  54,807.10 ms,  5.83 GB
2022.01.04 11:10:51  [INFO]     [creator]     [/layers/paketo-buildpacks_native-image/native-image/com.spf.DemoApplication:197]      compile:  96,236.09 ms,  5.83 GB
2022.01.04 11:10:51  [INFO]     [creator]     Fatal error:java.lang.NullPointerException
2022.01.04 11:10:51  [INFO]     [creator]     	at jdk.internal.vm.compiler/org.graalvm.compiler.core.common.util.FrequencyEncoder.getIndex(FrequencyEncoder.java:114)
2022.01.04 11:10:51  [INFO]     [creator]     	at com.oracle.svm.core.code.MethodMetadataEncoder.encodeMethodMetadata(MethodMetadataEncoder.java:200)
2022.01.04 11:10:51  [INFO]     [creator]     	at com.oracle.svm.core.code.MethodMetadataEncoder.encodeAllAndInstall(MethodMetadataEncoder.java:97)
2022.01.04 11:10:51  [INFO]     [creator]     	at com.oracle.svm.core.code.CodeInfoEncoder.encodeAllAndInstall(CodeInfoEncoder.java:266)
2022.01.04 11:10:51  [INFO]     [creator]     	at com.oracle.svm.hosted.image.NativeImageCodeCache.buildRuntimeMetadata(NativeImageCodeCache.java:272)
2022.01.04 11:10:51  [INFO]     [creator]     	at com.oracle.svm.hosted.image.LIRNativeImageCodeCache.layoutMethods(LIRNativeImageCodeCache.java:106)
2022.01.04 11:10:51  [INFO]     [creator]     	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:608)
2022.01.04 11:10:51  [INFO]     [creator]     	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
2022.01.04 11:10:51  [INFO]     [creator]     	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
2022.01.04 11:10:51  [INFO]     [creator]     	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
2022.01.04 11:10:51  [INFO]     [creator]     	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
2022.01.04 11:10:51  [INFO]     [creator]     	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)
2022.01.04 11:10:51  [INFO]     [creator]     [/layers/paketo-buildpacks_native-image/native-image/com.spf.DemoApplication:197]      [total]: 272,758.79 ms,  5.83 GB
```

Before running the native build, I generate the native configuration files using the AOT agent with GraalVM 21.3.0 :
```
$GRAALVM_HOME/bin/java -agentlib:native-image-agent=config-output-dir=src/main/resources/META-INF/native-image -jar target/config-import-vault-native-demo-0.0.1-SNAPSHOT.jar
```
_!!! Please note that if I generate the AOT files with GraalVM 21.2.0, the native is fine and the generated native image works !!!_

Do you have any idea on why the native build fails ? Thank you for your help on this.

**How to reproduce:**
- Generate/Regenerate the native configuration files using the AOT agent and GraalVM 21.3.0
- Run the native compilation `mvn spring-boot:build-image -PnativeImage` _- I am stucked at the stage with GraalVM 21.3.0 -_
- After the native image has been built, start a local vault instance and add the secret in path /secret/myapp (key = secret) via http://localhost:8200/ui/vault
```
docker run --rm -p 8200:8200 -e VAULT_DEV_ROOT_TOKEN_ID=root vault
```
- Run the docker native image and see the secret being printed in the log

**Comment by sdeleuze** [comment]
Spring Cloud Config Vault is not supported yet, you can track #1366 related issue.
