### ISSUE TITLE
Preview features are not enabled. Try running with '--enable-preview'

### ISSUE THREAD

**Issue by bojanv55** [spring-projects-experimental/spring-native#1449]
Got the problem during compilation. Is it possible to add this flag `--enable-preview` somehow to `spring-aot-maven-plugin:0.11.1:generate` phase?

```
java.lang.IllegalStateException: Failed to introspect Class [MediaPlaylistController] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@6f94fa3e]
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:481)
        at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:321)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.buildLifecycleMetadata(InitDestroyAnnotationBeanPostProcessor.java:232)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.findLifecycleMetadata(InitDestroyAnnotationBeanPostProcessor.java:210)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(InitDestroyAnnotationBeanPostProcessor.java:149)
        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(CommonAnnotationBeanPostProcessor.java:305)
        at org.springframework.context.annotation.CommonAnnotationBeanDefinitionPostProcessor.postProcessBeanDefinition(CommonAnnotationBeanDefinitionPostProcessor.java:46)
        at org.springframework.context.annotation.BuildTimeBeanDefinitionsRegistrar.lambda$postProcessBeanDefinitions$2(BuildTimeBeanDefinitionsRegistrar.java:83)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.springframework.context.annotation.BuildTimeBeanDefinitionsRegistrar.postProcessBeanDefinitions(BuildTimeBeanDefinitionsRegistrar.java:83)
        at org.springframework.context.annotation.BuildTimeBeanDefinitionsRegistrar.processBeanDefinitions(BuildTimeBeanDefinitionsRegistrar.java:67)
        at org.springframework.aot.context.bootstrap.generator.ApplicationContextAotProcessor.process(ApplicationContextAotProcessor.java:94)
        at org.springframework.aot.build.ContextBootstrapContributor.contribute(ContextBootstrapContributor.java:80)
        at org.springframework.aot.build.BootstrapCodeGenerator.generate(BootstrapCodeGenerator.java:91)
        at org.springframework.aot.build.BootstrapCodeGenerator.generate(BootstrapCodeGenerator.java:71)
        at org.springframework.aot.build.GenerateBootstrapCommand.call(GenerateBootstrapCommand.java:107)
        at org.springframework.aot.build.GenerateBootstrapCommand.call(GenerateBootstrapCommand.java:42)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at org.springframework.aot.build.GenerateBootstrapCommand.main(GenerateBootstrapCommand.java:112)
Caused by: java.lang.UnsupportedClassVersionError: Preview features are not enabled for MediaPlaylist (class file version 61.65535). Try running with '--enable-preview'
```

I already have this in pom.xml, but it is not making any difference:

```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-compiler-plugin</artifactId>
	<configuration>
		<source>17</source>
		<target>17</target>
		<compilerArgs>--enable-preview</compilerArgs>
	</configuration>
</plugin>
```

**Comment by sdeleuze** [comment]
Maybe `GenerateMojo` and `TestGenerateMojo` should copy more than `compileSourceRoots` and `compilePath`.

@bclozel @snicoll Any take on if we should copy `compilerArgs` as well or even other ones?

**Comment by bojanv55** [comment]
@sdeleuze Is there some temp workaround (Except I guess compiling the whole code with this params embedded)?

**Comment by bojanv55** [comment]
OK, seems this did the trick `set JAVA_TOOL_OPTIONS=--enable-preview`

**Comment by snicoll** [comment]
@bojanv55 thanks but we'd like to do something about this.

**Comment by bojanv55** [comment]
OK.

Also what i needed to do when compiling in remote docker:

```
<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<image>
						<builder>paketobuildpacks/builder:tiny</builder>
						<env>
							<JAVA_TOOL_OPTIONS>--enable-preview</JAVA_TOOL_OPTIONS>
```

**Comment by sdeleuze** [comment]
Spring Native is now superseded by Spring Boot 3 official native support, see [the related reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html) for more details.

As a consequence, I am closing this issue, and recommend trying your use case with latest Spring Boot 3 version. If you still experience the issue reported here, please open an issue directly on the related Spring project (Spring Framework, Data, Security, Boot, Cloud, etc.) with a reproducer.

Thanks for your contribution on the experimental Spring Native project, we hope you will enjoy the official native support introduced by Spring Boot 3.
