### ISSUE TITLE
Failed to process lifecycle methods on bean definition with name 'dataSource'

### ISSUE THREAD

**Issue by Xinmudotmoe** [spring-projects-experimental/spring-native#1455]
When **com.alibaba:druid-spring-boot-starter** (data source) is introduced, native cannot be produced.

Demo Project:

https://github.com/Xinmudotmoe/spring-native-little-issues/tree/issus-lifecycle-init-datasource

When only **com.alibaba:druid** is introduced, the packaging is successful, but the runtime is a little troublesome. It works fine with configuration. I think the same effect can be achieved within a plugin.

Demo Project:

https://github.com/Xinmudotmoe/spring-native-little-issues/tree/issues-runtime-datasource

**Comment by snicoll** [comment]
Thanks for the sample. I missed that the demo project was in a branch so I got confused initially that the project was building fine for me. Switching to the first branch led to:

```
java.lang.IllegalStateException: Failed to process lifecycle methods on bean definition with name 'dataSource'
	at org.springframework.aot.context.bootstrap.generator.infrastructure.InitDestroyMethodsDiscoverer.processLifecycleMethods(InitDestroyMethodsDiscoverer.java:106)
	at org.springframework.aot.context.bootstrap.generator.infrastructure.InitDestroyMethodsDiscoverer.registerInitMethods(InitDestroyMethodsDiscoverer.java:67)
	at org.springframework.aot.context.bootstrap.generator.infrastructure.BootstrapInfrastructureWriter.handleInitDestroyBeanPostProcessor(BootstrapInfrastructureWriter.java:105)
	at org.springframework.aot.context.bootstrap.generator.infrastructure.BootstrapInfrastructureWriter.writeInfrastructure(BootstrapInfrastructureWriter.java:75)
	at org.springframework.aot.context.bootstrap.generator.ApplicationContextAotProcessor.registerApplicationContextInfrastructure(ApplicationContextAotProcessor.java:157)
	at org.springframework.aot.context.bootstrap.generator.ApplicationContextAotProcessor.bootstrapMethod(ApplicationContextAotProcessor.java:103)
	at org.springframework.aot.context.bootstrap.generator.ApplicationContextAotProcessor.process(ApplicationContextAotProcessor.java:96)
	at org.springframework.aot.build.ContextBootstrapContributor.contribute(ContextBootstrapContributor.java:80)
	at org.springframework.aot.build.BootstrapCodeGenerator.generate(BootstrapCodeGenerator.java:91)
	at org.springframework.aot.build.BootstrapCodeGenerator.generate(BootstrapCodeGenerator.java:71)
	at org.springframework.aot.build.GenerateBootstrapCommand.call(GenerateBootstrapCommand.java:107)
	at org.springframework.aot.build.GenerateBootstrapCommand.call(GenerateBootstrapCommand.java:42)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.springframework.aot.build.GenerateBootstrapCommand.main(GenerateBootstrapCommand.java:112)
Caused by: java.lang.IllegalStateException: Lifecycle method annotation 'init' on 'javax.sql.DataSource' not found
	at org.springframework.aot.context.bootstrap.generator.infrastructure.InitDestroyMethodsDiscoverer.findMethod(InitDestroyMethodsDiscoverer.java:188)
	at org.springframework.aot.context.bootstrap.generator.infrastructure.InitDestroyMethodsDiscoverer.processInitMethods(InitDestroyMethodsDiscoverer.java:74)
	at org.springframework.aot.context.bootstrap.generator.infrastructure.InitDestroyMethodsDiscoverer.processLifecycleMethods(InitDestroyMethodsDiscoverer.java:99)
	... 19 more
```

**Comment by Xinmudotmoe** [comment]
In https://github.com/Xinmudotmoe/spring-native-little-issues/commit/bf335f66c4140cd257b22d5df80af7fb2f639ca8 the build is failing.  Later added **reflect-config.json** in the next commit.

The issue of the second branch may be solved by this project.

However, the problem of the second branch can find a corresponding solution after the packaging fails, perhaps as a low priority issue.

Thank you so much for everything you do.

**Comment by snicoll** [comment]
Unfortunately, that's an issue in Druid, I've created https://github.com/alibaba/druid/issues/4673

I will check what the framework does at runtime when it can't find a method that has been defined and I'll adapt accordingly.

**Comment by snicoll** [comment]
@Xinmudotmoe you might be able to workaround the issue by adding the following to your project's configuration:

```java
@Bean(initMethod = "init")
public DruidDataSourceWrapper dataSource() {
	return new DruidDataSourceWrapper();
}
```

(and remove the runtime scope for Druid).

**Comment by snicoll** [comment]
This is the error that we get at runtime (non AOT):

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in org.example.MainApplication: Invocation of init method failed; nested exception is org.springframework.beans.factory.support.BeanDefinitionValidationException: Could not find an init method named 'doesNotExist' on bean with name 'dataSource'
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.15.jar:5.3.15]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[classes/:na]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414) ~[classes/:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) ~[classes/:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[classes/:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[classes/:na]
	at org.example.MainApplication.main(MainApplication.java:14) ~[classes/:na]
Caused by: org.springframework.beans.factory.support.BeanDefinitionValidationException: Could not find an init method named 'doesNotExist' on bean with name 'dataSource'
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1895) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1872) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.15.jar:5.3.15]
	... 16 common frames omitted
```

For consistency with the core container, I am going to leave the current algorithm as is.
