### ISSUE TITLE
[Bug] spring boot log4j2 instead of logback not working

### ISSUE THREAD

**Issue by ceyhunn** [spring-projects-experimental/spring-native#1478]
I Build spring boot application with following gradle plugin and dependencies:
```
plugins {
    id 'org.springframework.boot' version '2.6.3'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
    id 'java'
    id 'org.springframework.experimental.aot' version '0.11.2'
}
dependencies {
    implementation "org.springframework.boot:spring-boot-starter-log4j2"
    modules {
        module("org.springframework.boot:spring-boot-starter-logging") {
            replacedBy("org.springframework.boot:spring-boot-starter-log4j2", "Use Log4j2 instead of Logback")
        }
    }
}
```
However it gives me following error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/boot/logging/LogFile
        at org.springframework.aot.build.GenerateBootstrapCommand.call(GenerateBootstrapCommand.java:93)
        at org.springframework.aot.build.GenerateBootstrapCommand.call(GenerateBootstrapCommand.java:42)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at org.springframework.aot.build.GenerateBootstrapCommand.main(GenerateBootstrapCommand.java:112)
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.logging.LogFile
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 10 more
```

**Comment by ttddyy** [comment]
Hi @ceyhunn,

Log4j2 is not supported.

From [documentation](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#_starters_requiring_no_special_build_configuration) (see `spring-boot-starter-logging`)
> Log4j2 is not supported yet, see #115.

**Comment by ceyhunn** [comment]
Hi @ttddyy , sorry for late answer, same error with with default logback, I think this is not log4j2 specific error.
