### ISSUE TITLE
Native reflection configuration for java.lang.Integer.parseInt(java.lang.String) is missing.

### ISSUE THREAD

**Issue by klboke** [spring-projects-experimental/spring-native#1494]
Hello
I tried to integrate a configuration center client in spring-native project, he can run well in jvm mode, and native can pass compile, but when run, it reported an exception. I have tried various ways to understand the reason for the exception, including whether the reflection is not configured correctly. In the end, I can't figure out the cause of the exception, can you help me?

Running Environment：
- system ：mac
- graalvm ：graalvm-ce-java17-21.3.1
- spring-boot.version : 2.6.3
- java.version : jDK17
- spring-native.version : 0.11.2

dependencies：
```xml
        <dependency>
            <groupId>com.ctrip.framework.apollo</groupId>
            <artifactId>apollo-client</artifactId>
            <version>1.9.1</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.inject</groupId>
                    <artifactId>guice</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.google.inject</groupId>
            <artifactId>guice</artifactId>
            <version>5.1.0</version>
        </dependency>
```
Exception Stacks
```java
2022-02-15 11:22:57.770  INFO 12573 --- [           main] o.s.nativex.NativeListener               : AOT mode enabled

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.3)

2022-02-15 11:22:57.773  INFO 12573 --- [           main] c.t.apolloproxy.ApolloProxyApplication   : Starting ApolloProxyApplication v0.0.1-SNAPSHOT using Java 17.0.2 on kldeMacBook-Pro-6.local with PID 12573 (/Users/kl/worknamespace/apollo-proxy/target/apollo-proxy started by kl in /Users/kl/worknamespace/apollo-proxy/target)
2022-02-15 11:22:57.773  INFO 12573 --- [           main] c.t.apolloproxy.ApolloProxyApplication   : No active profile set, falling back to default profiles: default
2022-02-15 11:22:57.775  WARN 12573 --- [           main] w.s.c.ServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'configPropertySourcesProcessor': Unexpected exception during bean creation; nested exception is com.ctrip.framework.apollo.exceptions.ApolloConfigException: Unable to load instance for com.ctrip.framework.apollo.spring.config.ConfigPropertySourceFactory!
2022-02-15 11:22:57.775 ERROR 12573 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Native reflection configuration for java.lang.Integer.parseInt(java.lang.String) is missing.

Action:

Native configuration for a method accessed reflectively is likely missing.
You can try to configure native hints in order to specify it explicitly.
See https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#native-hints for more details.

```

**Comment by sdeleuze** [comment]
Can you please try to run the generated executable with the `--debug` flag to see the stacktrace and have more information about the source of the reflection usage?

**Comment by klboke** [comment]
@sdeleuze  
Thank you very much, --debug is very useful, finally saw the exception stack information, it looks like the internal use of google guice framework caused the problem, how to configure support for this?
```java
kldeMacBook-Pro-6:target kl$ ./apollo-proxy --debug
2022-02-16 09:57:34.824  INFO 21281 --- [           main] o.s.nativex.NativeListener               : AOT mode enabled

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.3)

2022-02-16 09:57:34.828  INFO 21281 --- [           main] c.t.apolloproxy.ApolloProxyApplication   : Starting ApolloProxyApplication v0.0.1-SNAPSHOT using Java 17.0.2 on kldeMacBook-Pro-6.local with PID 21281 (/Users/kl/worknamespace/apollo-proxy/target/apollo-proxy started by kl in /Users/kl/worknamespace/apollo-proxy/target)
2022-02-16 09:57:34.828  INFO 21281 --- [           main] c.t.apolloproxy.ApolloProxyApplication   : No active profile set, falling back to default profiles: default
2022-02-16 09:57:34.828 DEBUG 21281 --- [           main] w.s.c.ServletWebServerApplicationContext : Refreshing org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext@7c33bbb6
2022-02-16 09:57:34.830  WARN 21281 --- [           main] w.s.c.ServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'configPropertySourcesProcessor': Unexpected exception during bean creation; nested exception is com.ctrip.framework.apollo.exceptions.ApolloConfigException: Unable to load instance for com.ctrip.framework.apollo.spring.config.ConfigPropertySourceFactory!
2022-02-16 09:57:34.831 DEBUG 21281 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : Application failed to start due to an exception

java.lang.NoSuchMethodException: java.lang.Integer.parseInt(java.lang.String)
        at java.lang.Class.getMethod(DynamicHub.java:1139) ~[apollo-proxy:na]
        at com.google.inject.internal.TypeConverterBindingProcessor.convertToPrimitiveType(TypeConverterBindingProcessor.java:122) ~[na:na]
        at com.google.inject.internal.TypeConverterBindingProcessor.prepareBuiltInConverters(TypeConverterBindingProcessor.java:45) ~[na:na]
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:182) ~[na:na]
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107) ~[na:na]
        at com.google.inject.Guice.createInjector(Guice.java:87) ~[na:na]
        at com.google.inject.Guice.createInjector(Guice.java:69) ~[na:na]
        at com.google.inject.Guice.createInjector(Guice.java:59) ~[na:na]
        at com.ctrip.framework.apollo.spring.util.SpringInjector.getInjector(SpringInjector.java:38) ~[na:na]
        at com.ctrip.framework.apollo.spring.util.SpringInjector.getInstance(SpringInjector.java:53) ~[na:na]
        at com.ctrip.framework.apollo.spring.config.PropertySourcesProcessor.<init>(PropertySourcesProcessor.java:63) ~[na:na]
        at com.ctrip.framework.apollo.spring.config.ConfigPropertySourcesProcessor.<init>(ConfigPropertySourcesProcessor.java:30) ~[na:na]
        at com.ctrip.framework.apollo.spring.boot.ApolloAutoConfiguration.configPropertySourcesProcessor(ApolloAutoConfiguration.java:34) ~[apollo-proxy:1.9.1]
        at org.springframework.aot.ContextBootstrapInitializer.lambda$initialize$67(ContextBootstrapInitializer.java:442) ~[na:na]
        at org.springframework.aot.beans.factory.ThrowableSupplier.get(ThrowableSupplier.java:17) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1249) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1191) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[na:na]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213) ~[na:na]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:106) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) ~[na:na]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[na:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[apollo-proxy:2.6.3]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414) ~[apollo-proxy:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) ~[apollo-proxy:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[apollo-proxy:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[apollo-proxy:2.6.3]
        at com.taptap.apolloproxy.ApolloProxyApplication.main(ApolloProxyApplication.java:10) ~[apollo-proxy:0.0.1-SNAPSHOT]

2022-02-16 09:57:34.912 ERROR 21281 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Native reflection configuration for java.lang.Integer.parseInt(java.lang.String) is missing.

Action:

Native configuration for a method accessed reflectively is likely missing.
You can try to configure native hints in order to specify it explicitly.
See https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#native-hints for more details.

```

**Comment by sdeleuze** [comment]
You can add the missing reflection configuration via [native hints](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#native-hints). Be also aware that we are working with GraalVM team on a configuration repository for native support outside of Spring.
