### ISSUE TITLE
AOP issues

### ISSUE THREAD

**Issue by smoell** [spring-projects-experimental/spring-native#1503]
Hi all,

I've created a project with Spring Native including AWS X-Ray. I've created an Aspect:

```
@Aspect
@Component
public class XRayInspector extends AbstractXRayInterceptor {
    @Override
    protected Map<String, Map<String, Object>> generateMetadata(ProceedingJoinPoint proceedingJoinPoint, Subsegment subsegment) {
        return super.generateMetadata(proceedingJoinPoint, subsegment);
    }

    @Override
    @Pointcut("@within(com.amazonaws.xray.spring.aop.XRayEnabled) && ( bean(*Service))")
    public void xrayEnabledClasses() {
    }
}
```

The annotated service looks like this:

```
@Service
@XRayEnabled
public class CustomerService {

    @Autowired
    CustomerRepository customerRepository;
```

In my reflect-config.json, I've the following entries (file has been created using the GraalVM tracing agent):

```
{
  "name":"com.amazonaws.xray.spring.aop.XRayEnabled",
  "queryAllDeclaredMethods":true,
  "allDeclaredMethods": true
},
{
  "name":"com.amazon.customerService.service.CustomerService",
  "allDeclaredFields":true,
  "allDeclaredMethods": true,
  "queryAllDeclaredMethods":true,
  "queryAllPublicMethods":true,
  "queryAllDeclaredConstructors":true,
  "methods":[{"name":"<init>","parameterTypes":[] }]}
,
```

After starting the application, I still get the following exception:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'healthEndpointGroupsBeanPostProcessor': Initialization of bean failed; nested exception is java.lang.IllegalArgumentException: error Type referred to is not an annotation type: com$amazonaws$xray$spring$aop$XRayEnabled
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:628) ~[CustomerService:5.3.15]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[CustomerService:5.3.15]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[CustomerService:5.3.15]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[CustomerService:5.3.15]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[CustomerService:5.3.15]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213) ~[CustomerService:5.3.15]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:270) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:762) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:567) ~[na:na]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[na:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[CustomerService:2.6.3]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414) ~[CustomerService:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) ~[CustomerService:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[CustomerService:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[CustomerService:2.6.3]
        at com.amazon.customerService.CustomerServiceApplication.main(CustomerServiceApplication.java:10) ~[CustomerService:0.0.1]
```

I'm not exactly sure how to fix this, thank you.

**Comment by sdeleuze** [comment]
Using AOP require configuring proxies AOT with related native hints, see [the related documentation](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#native-hints). If you are interested in automatic inference, you me be interested to track #1145.

If you still see the error after configuring the relevant AOT and JDK dynamic proxies, please share a repro and comment here.

**Comment by smoell** [comment]
Thank you for the help, I fixed the issue.

**Comment by zayitloud** [comment]
Hi @smoell 
We are facing a similar issue, would you mind sharing how you solved it?

Thanks in advance.
