### ISSUE TITLE
Webflux: NoUniqueBeanDefinitionException

### ISSUE THREAD

**Issue by ilgrosso** [spring-projects-experimental/spring-native#1535]
I am playing with the very promising features of Spring Native here: https://github.com/ilgrosso/notturno

I am currently trying to set up some Webflux REST services with configuration as follows: https://github.com/ilgrosso/notturno/blob/master/src/main/java/org/apache/syncope/core/rest/RESTContext.java e.g.

```java
@Configuration
@EnableWebFlux
public class RESTContext implements WebFluxConfigurer {

    @Override
    public void configureViewResolvers(final ViewResolverRegistry registry) {
        registry.defaultViews(new HttpMessageWriterView(new Jackson2JsonEncoder()));
    }

    @Bean
    public UserService userService() {
        return new UserService();
    }
}
```

When running the project via the Spring Boot Maven plugin, all is working as expected.

If instead I am first building via the `native-maven-plugin`, then I am getting the following startup exception:

```
2022-03-17 16:58:29.191  WARN 181470 --- [           main] .r.c.ReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'errorWebExceptionHandler': Unsatisfied dependency expressed through method 'errorWebExceptionHandler' parameter 3; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverCodecConfigurer': Unexpected exception during bean creation; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'org.springframework.web.reactive.config.WebFluxConfigurationSupport' available: expected single matching bean but found 2: org.springframework.boot.autoconfigure.web.reactive.WebFluxAutoConfiguration$EnableWebFluxConfiguration,org.springframework.web.reactive.config.DelegatingWebFluxConfiguration
2022-03-17 16:58:29.193 ERROR 181470 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'errorWebExceptionHandler': Unsatisfied dependency expressed through method 'errorWebExceptionHandler' parameter 3; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverCodecConfigurer': Unexpected exception during bean creation; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'org.springframework.web.reactive.config.WebFluxConfigurationSupport' available: expected single matching bean but found 2: org.springframework.boot.autoconfigure.web.reactive.WebFluxAutoConfiguration$EnableWebFluxConfiguration,org.springframework.web.reactive.config.DelegatingWebFluxConfiguration
        at org.springframework.aot.beans.factory.InjectedConstructionResolver.resolve(InjectedConstructionResolver.java:88) ~[na:na]
        at org.springframework.aot.beans.factory.InjectedElementResolver.resolve(InjectedElementResolver.java:35) ~[na:na]
        at org.springframework.aot.beans.factory.InjectedElementResolver.create(InjectedElementResolver.java:66) ~[na:na]
        at org.springframework.aot.beans.factory.BeanDefinitionRegistrar$BeanInstanceContext.create(BeanDefinitionRegistrar.java:211) ~[na:na]
        at org.springframework.aot.ContextBootstrapInitializer.lambda$initialize$20(ContextBootstrapInitializer.java:212) ~[na:na]
        at org.springframework.aot.beans.factory.BeanDefinitionRegistrar$ThrowableFunction.apply(BeanDefinitionRegistrar.java:294) ~[na:na]
        at org.springframework.aot.beans.factory.BeanDefinitionRegistrar.lambda$instanceSupplier$0(BeanDefinitionRegistrar.java:115) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1249) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1191) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[na:na]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[na:na]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[na:na]
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:64) ~[na:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740) ~[syncope:2.6.4]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415) ~[syncope:2.6.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[syncope:2.6.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) ~[syncope:2.6.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[syncope:2.6.4]
        at org.apache.syncope.core.starter.SyncopeCoreApplication.main(SyncopeCoreApplication.java:10) ~[syncope:4.0.0-SNAPSHOT]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverCodecConfigurer': Unexpected exception during bean creation; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'org.springframework.web.reactive.config.WebFluxConfigurationSupport' available: expected single matching bean but found 2: org.springframework.boot.autoconfigure.web.reactive.WebFluxAutoConfiguration$EnableWebFluxConfiguration,org.springframework.web.reactive.config.DelegatingWebFluxConfiguration
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:555) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[na:na]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[na:na]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[na:na]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389) ~[na:na]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309) ~[na:na]
        at org.springframework.aot.beans.factory.InjectedConstructionResolver.lambda$resolve$0(InjectedConstructionResolver.java:83) ~[na:na]
        at org.springframework.aot.beans.factory.InjectedConstructionResolver.resolveDependency(InjectedConstructionResolver.java:97) ~[na:na]
        at org.springframework.aot.beans.factory.InjectedConstructionResolver.resolve(InjectedConstructionResolver.java:83) ~[na:na]
        ... 24 common frames omitted
Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'org.springframework.web.reactive.config.WebFluxConfigurationSupport' available: expected single matching bean but found 2: org.springframework.boot.autoconfigure.web.reactive.WebFluxAutoConfiguration$EnableWebFluxConfiguration,org.springframework.web.reactive.config.DelegatingWebFluxConfiguration
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1271) ~[na:na]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:494) ~[na:na]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:349) ~[na:na]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:342) ~[na:na]
        at org.springframework.aot.ContextBootstrapInitializer.lambda$initialize$42(ContextBootstrapInitializer.java:249) ~[na:na]
        at org.springframework.aot.beans.factory.BeanDefinitionRegistrar$ThrowableSupplier.get(BeanDefinitionRegistrar.java:317) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1249) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1191) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[na:na]
        ... 34 common frames omitted
```

Am I doing anything wrong?

**Comment by sdeleuze** [comment]
@snicoll I can reproduce an issue (not sure this is exactly the same) on the JVM in AOT mode, is it something of interest for you ?

```
❯ java -DspringAot=true -jar target/syncope-4.0.0-SNAPSHOT-exec.jar 
2022-03-18 09:18:20.712  INFO 12169 --- [           main] o.s.nativex.NativeListener               : AOT mode enabled
2022-03-18 09:18:20.736  INFO 12169 --- [           main] o.s.boot.SpringApplication               : 
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::       (v4.0.0-SNAPSHOT)


2022-03-18 09:18:20.813  INFO 12169 --- [           main] o.a.s.c.starter.SyncopeCoreApplication   : Starting SyncopeCoreApplication v4.0.0-SNAPSHOT using Java 17.0.2 on m1 with PID 12169 (/home/seb/playground/notturno/target/syncope-4.0.0-SNAPSHOT-exec.jar started by seb in /home/seb/playground/notturno)
2022-03-18 09:18:20.813  INFO 12169 --- [           main] o.a.s.c.starter.SyncopeCoreApplication   : No active profile set, falling back to 1 default profile: "default"
2022-03-18 09:18:21.226  WARN 12169 --- [           main] .r.c.ReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'errorWebExceptionHandler': Unsatisfied dependency expressed through method 'errorWebExceptionHandler' parameter 3; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverCodecConfigurer': Unexpected exception during bean creation; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'org.springframework.web.reactive.config.WebFluxConfigurationSupport' available: expected single matching bean but found 2: org.springframework.boot.autoconfigure.web.reactive.WebFluxAutoConfiguration$EnableWebFluxConfiguration,org.springframework.web.reactive.config.DelegatingWebFluxConfiguration
2022-03-18 09:18:21.245 ERROR 12169 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 3 of method errorWebExceptionHandler in org.springframework.boot.autoconfigure.web.reactive.error.ErrorWebFluxAutoConfiguration required a single bean, but 2 were found:
	- org.springframework.boot.autoconfigure.web.reactive.WebFluxAutoConfiguration$EnableWebFluxConfiguration: defined in null
	- org.springframework.web.reactive.config.DelegatingWebFluxConfiguration: defined in null


Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
```

**Comment by snicoll** [comment]
It's not really an AOT problem. `RESTContext` is an auto-configuration (a bit odd) that has `@EnableWebflux` (it shouldn't). It's not ordered against our webflux auto-configuration and it contributes a `DelegatingWebFluxConfiguration` regardless of one being already present or not (that's also wrong). 

It looks like at runtime, the undefined order is so that our auto-configuration backs off (because it runs after). The undefined order with AOT is reverse, hence the exception.

To prove this, I've added `@AutoConfigureBefore(WebFluxAutoConfiguration.class)` in `RESTContext` and the app starts in AOT mode as well.

**Comment by ilgrosso** [comment]
Thank you very much @snicoll for your insights.
