### ISSUE TITLE
grpc sample fails with GraalVM 22.1

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects-experimental/spring-native#1543]
`grpc` sample build fails with Java 17 `22.1.0-dev`:

```
[7/7] Creating image...                                                                                  (0.0s @ 3.25GB)
Fatal error: com.oracle.svm.core.util.VMError$HostedError: com.oracle.svm.core.util.UserError$UserException: Image heap writing found a class not seen during static analysis. Did a static field or an object referenced from a static field change during native image generation? For example, a lazily initialized cache could have been initialized during image generation, in which case you need to force eager initialization of the cache before static analysis or reset the cache using a field value recomputation.
    class: org.springframework.context.annotation.AnnotationScopeMetadataResolver
  reachable through:
    object: [Ljava.lang.Class;@588e060c  of class: java.lang.Class[]
    object: com.oracle.svm.core.code.ImageCodeInfo@df61967  of class: com.oracle.svm.core.code.ImageCodeInfo
    root: com.oracle.svm.core.graal.snippets.CEntryPointSnippets.createIsolate(CEntryPointCreateIsolateParameters, int)

	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:72)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:677)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:514)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:413)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:591)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:129)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:621)
```

**Comment by mhalbritter** [comment]
I got a build from Graal team which is based on https://github.com/oracle/graal/pull/4414, which fixes this issue.
