### ISSUE TITLE
events fails with GraalVM 22.1

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects-experimental/spring-native#1551]
```
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment GraalVM CE 22.1.0-dev (build 17.0.3+4-jvmci-22.1-b03)
OpenJDK 64-Bit Server VM GraalVM CE 22.1.0-dev (build 17.0.3+4-jvmci-22.1-b03, mixed mode, sharing)
```

build works fine, running it throws this exception:

```
2022-03-28 14:09:25.755  INFO 99420 --- [           main] o.s.nativex.NativeListener               : AOT mode enabled

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.4)

2022-03-28 14:09:25.757  INFO 99420 --- [           main] com.example.events.EventApplication      : Starting EventApplication v0.0.1-SNAPSHOT using Java 17.0.3 on fedora with PID 99420 (/home/moe/Projects/spring-native/samples/events/target/events started by moe in /home/moe/Projects/spring-native/samples/events)
2022-03-28 14:09:25.757  INFO 99420 --- [           main] com.example.events.EventApplication      : No active profile set, falling back to 1 default profile: "default"
2022-03-28 14:09:25.786  INFO 99420 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2022-03-28 14:09:25.792  INFO 99420 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2022-03-28 14:09:25.793  INFO 99420 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2022-03-28 14:09:25.796  INFO 99420 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.6.5.Final
2022-03-28 14:09:25.798  INFO 99420 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
2022-03-28 14:09:25.801  INFO 99420 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
2022-03-28 14:09:25.801  WARN 99420 --- [           main] org.hibernate.dialect.H2Dialect          : HHH000431: Unable to determine H2 database version, certain features may not work
2022-03-28 14:09:25.809  INFO 99420 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2022-03-28 14:09:25.809  INFO 99420 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2022-03-28 14:09:25.810  INFO 99420 --- [           main] o.s.aop.framework.BuildTimeAopProxy      : Attempting discovery (load) of build time generated proxy for class: com.example.events.SamplePublisher
2022-03-28 14:09:25.810  INFO 99420 --- [           main] o.s.aop.framework.BuildTimeAopProxy      : Suitable proxy found with name com.example.events.SamplePublisher$$SpringProxy$106600a6
2022-03-28 14:09:25.824 ERROR 99420 --- [           main] o.s.boot.SpringApplication               : Application run failed

com.oracle.svm.core.jdk.UnsupportedFeatureError: Proxy class defined by interfaces [interface org.springframework.transaction.event.TransactionalEventListener, interface org.springframework.core.annotation.SynthesizedAnnotation] not found. Generating proxy classes at runtime is not supported. Proxy classes need to be defined at image build time by specifying the list of interfaces that they implement. To define proxy classes use -H:DynamicProxyConfigurationFiles=<comma-separated-config-files> and -H:DynamicProxyConfigurationResources=<comma-separated-config-resources> options.
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89) ~[na:na]
	at com.oracle.svm.reflect.proxy.DynamicProxySupport.getProxyClass(DynamicProxySupport.java:158) ~[na:na]
	at java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:48) ~[events:na]
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1037) ~[events:na]
	at org.springframework.core.annotation.SynthesizedMergedAnnotationInvocationHandler.createProxy(SynthesizedMergedAnnotationInvocationHandler.java:305) ~[na:na]
	at org.springframework.core.annotation.TypeMappedAnnotation.createSynthesized(TypeMappedAnnotation.java:335) ~[na:na]
	at org.springframework.core.annotation.AbstractMergedAnnotation.synthesize(AbstractMergedAnnotation.java:210) ~[events:5.3.16]
	at org.springframework.core.annotation.AbstractMergedAnnotation.synthesize(AbstractMergedAnnotation.java:200) ~[events:5.3.16]
	at org.springframework.core.annotation.AnnotatedElementUtils.findMergedAnnotation(AnnotatedElementUtils.java:634) ~[na:na]
	at org.springframework.transaction.event.TransactionalApplicationListenerMethodAdapter.<init>(TransactionalApplicationListenerMethodAdapter.java:67) ~[na:na]
	at org.springframework.transaction.event.TransactionalEventListenerFactory.createApplicationListener(TransactionalEventListenerFactory.java:56) ~[events:5.3.16]
	at org.springframework.context.event.EventListenerRegistrar.register(EventListenerRegistrar.java:59) ~[na:na]
	at org.springframework.context.event.EventListenerRegistrar.afterSingletonsInstantiated(EventListenerRegistrar.java:52) ~[na:na]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:972) ~[events:0.11.4-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[events:5.3.16]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[events:5.3.16]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740) ~[events:2.6.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415) ~[events:2.6.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[events:2.6.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) ~[events:2.6.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[events:2.6.4]
	at com.example.events.EventApplication.main(EventApplication.java:14) ~[events:0.0.1-SNAPSHOT]

2022-03-28 14:09:25.824  INFO 99420 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2022-03-28 14:09:25.824  INFO 99420 --- [           main] .SchemaDropperImpl$DelayedDropActionImpl : HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
2022-03-28 14:09:25.824  INFO 99420 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2022-03-28 14:09:25.824  INFO 99420 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
FAILURE: the output of the application does not contain the expected output
```

**Comment by mhalbritter** [comment]
This looks like a missing entry in `proxy-config.json`, but i just double checked that it builds with GraalVM 22.0.

**Comment by mhalbritter** [comment]
Adding

```json
  [
    "org.springframework.transaction.event.TransactionalEventListener",
    "org.springframework.core.annotation.SynthesizedAnnotation"
  ]
```

to `proxy-config.json` solves the issue, but i'm puzzled why this is needed in 22.1 and not in 22.0.

**Comment by mhalbritter** [comment]
Here's the PR which fixes this issue: https://github.com/spring-projects-experimental/spring-native/pull/1560
