### ISSUE TITLE
neo4jDriver bean can not be intitialized

### ISSUE THREAD

**Issue by Jamsa** [spring-projects-experimental/spring-native#1596]
My application is a spring boot Neo4j application.
The native version throws exception when init the neo4jDriver bean.
Can I add Native hint to fix it?

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'neo4jDriver': Unexpected exception during bean creation; nested exception is org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [java.net.URI]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:555) ~[retail-api:5.3.18]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[retail-api:5.3.18]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[retail-api:5.3.18]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[retail-api:5.3.18]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[retail-api:5.3.18]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[na:na]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389) ~[na:na]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309) ~[na:na]
	at org.springframework.aot.beans.factory.InjectedConstructionResolver.lambda$resolve$0(InjectedConstructionResolver.java:83) ~[na:na]
	at org.springframework.aot.beans.factory.InjectedConstructionResolver.resolveDependency(InjectedConstructionResolver.java:97) ~[na:na]
	at org.springframework.aot.beans.factory.InjectedConstructionResolver.resolve(InjectedConstructionResolver.java:83) ~[na:na]
	... 74 common frames omitted
Caused by: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [java.net.URI]
	at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:322) ~[na:na]
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:195) ~[na:na]
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:175) ~[na:na]
```

**Comment by Jamsa** [comment]
fixed by changing the neo4j configuration item in `application.properties` from 
`spring.data.neo4j`
to 
`spring.neo4j`
