### ISSUE TITLE
Add R2DBC PostgreSQL support

### ISSUE THREAD

**Issue by operrin** [spring-projects-experimental/spring-native#1626]
Version 2.7.0 of Springboot (reactive), native (0.12) generation, MacOS, OpenJDK Runtime Environment GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06)

I try to access a Pg database, hosted on my machine, using localhost:5432/orders.
Everything is working fine using the non-native version, the resource file is used as expected.
When generating the native version, and try to access the endpoint, I get this exception:

```
2022-06-03 14:32:15.209 ERROR 67389 --- [actor-tcp-nio-1] a.w.r.e.AbstractErrorWebExceptionHandler : [3dc865e0-1]  500 Server Error for HTTP GET "/intervenants/"

org.springframework.dao.DataAccessResourceFailureException: Failed to obtain R2DBC Connection; nested exception is io.r2dbc.postgresql.PostgresqlConnectionFactory$PostgresConnectionException: Cannot connect to localhost/<unresolved>:5432
	at org.springframework.r2dbc.connection.ConnectionFactoryUtils.lambda$getConnection$0(ConnectionFactoryUtils.java:88) ~[na:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
	*__checkpoint ⇢ Handler org.miage.intervenantservice.boundary.IntervenantRouter$$Lambda$33f6ea66eb22970ddf524a223f0b6a228e9aeae3@2ff3d3b3 [DispatcherHandler]
	*__checkpoint ⇢ HTTP GET "/intervenants/" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at org.springframework.r2dbc.connection.ConnectionFactoryUtils.lambda$getConnection$0(ConnectionFactoryUtils.java:88) ~[na:na]
```

**Comment by snicoll** [comment]
@operrin where does it say there it "does not load the database properties"? All I can see there is that it can't connect to your local database. If you had a small sample that demonstrates the problem we could run ourselves that would help quite a bit.

**Comment by mhalbritter** [comment]
I got a different error, which seems like a bug:

1. Clone the repo
2. Change `spring.r2dbc.url=r2dbc:postgresql://localhost:5432/postgres` in application.properties
3. Start postgres: `docker run --rm -p 5432:5432 -e POSTGRES_PASSWORD=riovas postgres`
4. Start application
5. Run `curl http://localhost:8080/intervenants -s -S -v -H "Accept: application/json, */*"`

Then I get this stacktrace:

```
org.springframework.dao.DataAccessResourceFailureException: Failed to obtain R2DBC Connection; nested exception is io.r2dbc.postgresql.PostgresqlConnectionFactory$PostgresConnectionException: Cannot connect to localhost/<unresolved>:5432
        at org.springframework.r2dbc.connection.ConnectionFactoryUtils.lambda$getConnection$0(ConnectionFactoryUtils.java:88) ~[na:na]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
        *__checkpoint ⇢ Handler org.miage.intervenantservice.boundary.IntervenantRouter$$Lambda$33f6ea66eb22970ddf524a223f0b6a228e9aeae3@320237d3 [DispatcherHandler]
        *__checkpoint ⇢ HTTP GET "/intervenants" [ExceptionHandlingWebHandler]
Original Stack Trace:
                at org.springframework.r2dbc.connection.ConnectionFactoryUtils.lambda$getConnection$0(ConnectionFactoryUtils.java:88) ~[na:na]
                at reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3733) ~[intervenant-service:3.4.18]
                at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94) ~[na:na]
                at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106) ~[na:na]
                at reactor.core.publisher.FluxRetry$RetrySubscriber.onError(FluxRetry.java:95) ~[intervenant-service:3.4.18]
                at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172) ~[intervenant-service:3.4.18]
                at reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:477) ~[intervenant-service:0.2.8]
                at reactor.pool.SimpleDequePool.lambda$drainLoop$9(SimpleDequePool.java:431) ~[intervenant-service:0.2.8]
                at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:186) ~[intervenant-service:3.4.18]
                at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onError(FluxMap.java:265) ~[na:na]
                at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106) ~[na:na]
                at reactor.core.publisher.Operators.error(Operators.java:198) ~[intervenant-service:3.4.18]
                at reactor.core.publisher.MonoError.subscribe(MonoError.java:53) ~[na:na]
                at reactor.core.publisher.Mono.subscribe(Mono.java:4400) ~[intervenant-service:3.4.18]
                at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103) ~[na:na]
                at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:129) ~[intervenant-service:3.4.18]
                at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[na:na]
                at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[na:na]
                at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[na:na]
                at reactor.core.publisher.MonoDelayUntil$DelayUntilCoordinator.complete(MonoDelayUntil.java:418) ~[intervenant-service:3.4.18]
                at reactor.core.publisher.MonoDelayUntil$DelayUntilTrigger.onComplete(MonoDelayUntil.java:531) ~[na:na]
                at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:220) ~[na:na]
                at reactor.core.publisher.FluxHandle$HandleConditionalSubscriber.onComplete(FluxHandle.java:437) ~[na:na]
                at reactor.core.publisher.FluxCreate$BaseSink.complete(FluxCreate.java:460) ~[intervenant-service:3.4.18]
                at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:805) ~[intervenant-service:3.4.18]
                at reactor.core.publisher.FluxCreate$BufferAsyncSink.complete(FluxCreate.java:753) ~[intervenant-service:3.4.18]
                at reactor.core.publisher.FluxCreate$SerializedFluxSink.drainLoop(FluxCreate.java:247) ~[intervenant-service:3.4.18]
                at reactor.core.publisher.FluxCreate$SerializedFluxSink.drain(FluxCreate.java:213) ~[intervenant-service:3.4.18]
                at reactor.core.publisher.FluxCreate$SerializedFluxSink.complete(FluxCreate.java:204) ~[intervenant-service:3.4.18]
                at io.r2dbc.postgresql.client.ReactorNettyClient$Conversation.complete(ReactorNettyClient.java:619) ~[intervenant-service:0.9.1.RELEASE]
                at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.emit(ReactorNettyClient.java:885) ~[na:na]
                at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:761) ~[na:na]
                at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:667) ~[na:na]
                at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:126) ~[na:na]
                at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854) ~[na:na]
                at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224) ~[na:na]
                at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224) ~[na:na]
                at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:279) ~[intervenant-service:1.0.19]
                at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:388) ~[intervenant-service:1.0.19]
                at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:404) ~[intervenant-service:1.0.19]
                at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93) ~[na:na]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[intervenant-service:4.1.77.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[intervenant-service:4.1.77.Final]
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[intervenant-service:4.1.77.Final]
                at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[intervenant-service:4.1.77.Final]
                at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[intervenant-service:4.1.77.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[intervenant-service:4.1.77.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[intervenant-service:4.1.77.Final]
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[intervenant-service:4.1.77.Final]
                at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[intervenant-service:4.1.77.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[intervenant-service:4.1.77.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[intervenant-service:4.1.77.Final]
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[intervenant-service:4.1.77.Final]
                at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[na:na]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[intervenant-service:4.1.77.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[intervenant-service:4.1.77.Final]
                at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[intervenant-service:4.1.77.Final]
                at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[intervenant-service:4.1.77.Final]
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[na:na]
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[na:na]
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[na:na]
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[na:na]
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[na:na]
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[na:na]
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[na:na]
                at java.lang.Thread.run(Thread.java:833) ~[intervenant-service:na]
                at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704) ~[intervenant-service:na]
                at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202) ~[na:na]
Caused by: io.r2dbc.postgresql.PostgresqlConnectionFactory$PostgresConnectionException: Cannot connect to localhost/<unresolved>:5432
        at io.r2dbc.postgresql.PostgresqlConnectionFactory.cannotConnect(PostgresqlConnectionFactory.java:216) ~[na:na]
        at reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3733) ~[intervenant-service:3.4.18]
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94) ~[na:na]
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:129) ~[intervenant-service:3.4.18]
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[na:na]
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[na:na]
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[na:na]
        at reactor.core.publisher.MonoDelayUntil$DelayUntilCoordinator.complete(MonoDelayUntil.java:418) ~[intervenant-service:3.4.18]
        at reactor.core.publisher.MonoDelayUntil$DelayUntilTrigger.onComplete(MonoDelayUntil.java:531) ~[na:na]
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:220) ~[na:na]
        at reactor.core.publisher.FluxHandle$HandleConditionalSubscriber.onComplete(FluxHandle.java:437) ~[na:na]
        at reactor.core.publisher.FluxCreate$BaseSink.complete(FluxCreate.java:460) ~[intervenant-service:3.4.18]
        at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:805) ~[intervenant-service:3.4.18]
        at reactor.core.publisher.FluxCreate$BufferAsyncSink.complete(FluxCreate.java:753) ~[intervenant-service:3.4.18]
        at reactor.core.publisher.FluxCreate$SerializedFluxSink.drainLoop(FluxCreate.java:247) ~[intervenant-service:3.4.18]
        at reactor.core.publisher.FluxCreate$SerializedFluxSink.drain(FluxCreate.java:213) ~[intervenant-service:3.4.18]
        at reactor.core.publisher.FluxCreate$SerializedFluxSink.complete(FluxCreate.java:204) ~[intervenant-service:3.4.18]
        at io.r2dbc.postgresql.client.ReactorNettyClient$Conversation.complete(ReactorNettyClient.java:619) ~[intervenant-service:0.9.1.RELEASE]
        at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.emit(ReactorNettyClient.java:885) ~[na:na]
        at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:761) ~[na:na]
        at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:667) ~[na:na]
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:126) ~[na:na]
        at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854) ~[na:na]
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224) ~[na:na]
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224) ~[na:na]
        at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:279) ~[intervenant-service:1.0.19]
        at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:388) ~[intervenant-service:1.0.19]
        at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:404) ~[intervenant-service:1.0.19]
        at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93) ~[na:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[intervenant-service:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[intervenant-service:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[intervenant-service:4.1.77.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[intervenant-service:4.1.77.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[intervenant-service:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[intervenant-service:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[intervenant-service:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[intervenant-service:4.1.77.Final]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[intervenant-service:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[intervenant-service:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[intervenant-service:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[intervenant-service:4.1.77.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[na:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[intervenant-service:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[intervenant-service:4.1.77.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[intervenant-service:4.1.77.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[intervenant-service:4.1.77.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[na:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[na:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[na:na]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[na:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[na:na]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[na:na]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[na:na]
        at java.lang.Thread.run(Thread.java:833) ~[intervenant-service:na]
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704) ~[intervenant-service:na]
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202) ~[na:na]
Caused by: java.lang.IllegalArgumentException: Class java.time.Instant[] is instantiated reflectively but was never registered.Register the class by adding "unsafeAllocated" for the class in reflect-config.json.
        at com.oracle.svm.core.graal.snippets.SubstrateAllocationSnippets.arrayHubErrorStub(SubstrateAllocationSnippets.java:252) ~[intervenant-service:na]
        at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1054) ~[na:na]
        at io.r2dbc.postgresql.codec.CachedCodecLookup.afterCodecAdded(CachedCodecLookup.java:70) ~[na:na]
        at io.r2dbc.postgresql.codec.DefaultCodecs.<init>(DefaultCodecs.java:82) ~[na:na]
        at io.r2dbc.postgresql.codec.DefaultCodecs.<init>(DefaultCodecs.java:66) ~[na:na]
        at io.r2dbc.postgresql.PostgresqlConnectionFactory.lambda$doCreateConnection$13(PostgresqlConnectionFactory.java:157) ~[na:na]
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125) ~[intervenant-service:3.4.18]
        ... 52 common frames omitted
```

**Comment by mhalbritter** [comment]
We have a sample for `r2dbc`, but it uses H2 and not PostgreSQL. This seems like a incompatability with R2DBC and PostgreSQL.

**Comment by salaboy** [comment]
@mhalbritter I can see this closed.. can you guide me to see if I can fix it on my project while I wait for 12.1?

**Comment by snicoll** [comment]
@salaboy doesn't the commit help? It's mostly around a sample and additional hints: https://github.com/spring-projects-experimental/spring-native/commit/2db718d14c2897581e2b733cc88ef1b302b5b41b#diff-85b671bf6819b49e86acb5307b02560dc91d153dfd300aa7ddbb7f30baaf7a33R16-R23

**Comment by salaboy** [comment]
@snicoll I am trying to replicate that in my project but it is not working.. I've just added a comment into an import.. that doesn't seem right

**Comment by snicoll** [comment]
Your spring.factories is missing the key. It's a key value pair not a flat list of classes.

**Comment by mhalbritter** [comment]
You can also just put the hints on your `@SpringBootApplication` class:

```
@NativeHint(
        trigger = PostgresqlConnectionFactoryProvider.class,
        types = {
                @TypeHint(types = { Instant[].class, ZonedDateTime[].class, URI[].class }, access = {}),
        }
)
```

**Comment by salaboy** [comment]
@mhalbritter trying now

**Comment by operrin** [comment]
I've modifed my test project accordingly to your comments (Hints class and META-INF), and I still have an exception:

`
Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'intervenantHandler': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'intervenantService': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'intervenantRepository': Cannot resolve reference to bean 'r2dbcEntityTemplate' while setting bean property 'entityOperations'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'r2dbcEntityTemplate': Unsatisfied dependency expressed through method 'r2dbcEntityTemplate' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'r2dbcConverter': Unsatisfied dependency expressed through method 'r2dbcConverter' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'r2dbcMappingContext': Unsatisfied dependency expressed through method 'r2dbcMappingContext' parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.data.r2dbc.R2dbcDataAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'r2dbcDatabaseClient': Unsatisfied dependency expressed through method 'r2dbcDatabaseClient' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'connectionFactory': Unexpected exception during bean creation; nested exception is java.lang.IllegalStateException: Unable to create a ConnectionFactory for 'ConnectionFactoryOptions{options={database=orders, host=localhost, driver=postgresql, password=REDACTED, port=5432, user=postgres}}'. Available drivers: [ pool ]
`

The last line seems to indicate a problem of ConnectionFactory.

**Comment by salaboy** [comment]
@operrin that issue is because you have a wrong URL in the connection string, or at least I was getting something pretty similar when I had a wrong url

**Comment by operrin** [comment]
@salaboy Not working for me, with all the parameters checked.

**Comment by mhalbritter** [comment]
I added the hints to the main app [from your sample](https://github.com/spring-projects-experimental/spring-native/issues/1626#issuecomment-1150852631) and it works. Please share the complete project and the instructions how to run it if you suspect that this isn't fixed yet.

**Comment by operrin** [comment]
You can find the project here: https://github.com/operrin/native-bug/ 
Run a pg database (either locally or via docker)
Still unable to start the native app while everything is ok with the java version.

**Comment by mhalbritter** [comment]
Hey @operrin, the problem in your application is this here:

```
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>r2dbc-postgresql</artifactId>
			<scope>provided</scope>
		</dependency>
```

remove the `<scope>` element and it works.

**Comment by operrin** [comment]
Thanks !

**Comment by fragaLY** [comment]
Seems like this is a typical definition exception, try to run in the same network, i.e. using docker-compose and replace 'localhost' with {hostName} of Postgres container.
