### ISSUE TITLE
native start error

### ISSUE THREAD

**Issue by 929541303** [spring-projects-experimental/spring-native#1648]
i can start by java -DspringAot=true -jar mediamanager-2.0.2-20220402-exec.jar, but could not start by native image ;

```
rg.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'openApiControllerWebMvc': Unsatisfied dependency expressed through constructor parameter 3; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webMvcOpenApiTransformationFilterRegistry': Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'type' of bean class [org.springframework.plugin.core.support.PluginRegistryFactoryBean]: Bean property 'type' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
	at org.springframework.aot.beans.factory.InjectedConstructionResolver.resolve(InjectedConstructionResolver.java:88) ~[na:na]
	at org.springframework.aot.beans.factory.InjectedElementResolver.resolve(InjectedElementResolver.java:35) ~[mediamanager:0.12.0]
	at org.springframework.aot.beans.factory.InjectedElementResolver.create(InjectedElementResolver.java:66) ~[mediamanager:0.12.0]
	at org.springframework.aot.beans.factory.BeanDefinitionRegistrar$BeanInstanceContext.create(BeanDefinitionRegistrar.java:211) ~[na:na]
	at org.springframework.aot.ContextBootstrapInitializer.lambda$initialize$1(ContextBootstrapInitializer.java:304) ~[na:na]
	at org.springframework.aot.beans.factory.BeanDefinitionRegistrar$ThrowableFunction.apply(BeanDefinitionRegistrar.java:294) ~[mediamanager:0.12.0]
	at org.springframework.aot.beans.factory.BeanDefinitionRegistrar.lambda$instanceSupplier$0(BeanDefinitionRegistrar.java:115) ~[na:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1249) ~[mediamanager:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1191) ~[mediamanager:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[mediamanager:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[mediamanager:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[mediamanager:5.3.20]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[mediamanager:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[mediamanager:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[mediamanager:5.3.20]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[mediamanager:5.3.20]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[mediamanager:5.3.20]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[mediamanager:5.3.20]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[na:na]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[mediamanager:2.7.0]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[mediamanager:2.7.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[mediamanager:2.7.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[mediamanager:2.7.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[mediamanager:2.7.0]
```

**Comment by mhalbritter** [comment]
If you'd like us to spend some time investigating, please take the time to provide a complete minimal sample (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by 929541303** [comment]
来信收到，查看后会及时回复您！

**Comment by brianmolinaspring** [comment]
hello guys, were you able to solve this problem?

**Comment by 929541303** [comment]
来信收到，查看后会及时回复您！

**Comment by brianmolinaspring** [comment]
@929541303 @mhalbritter ,could you help with this error?

**Comment by mhalbritter** [comment]
Sure, if you provide a sample which reproduces this problem, i'm happy to help/

**Comment by 929541303** [comment]
来信收到，查看后会及时回复您！
