### ISSUE TITLE
Error creating bean with name 'entityManagerFactory'

### ISSUE THREAD

**Issue by fragaLY** [spring-projects-experimental/spring-native#1668]
Hello, pioneers,

I would like to find a way of solving the problem regarding the entity manager initialization.

The sample of the project is here: https://github.com/fragaLY/performance-researches/tree/master/spring-boot-web-native

1. To be ready to start it up please run the `docker-compose up` in the /docker directory to boot up the database.
2. After that execute `./gradlew nativeCompile`
3. Run built artifact.

The actual result is:

> 2022-07-11 16:37:59.475  INFO 96854 --- [           main] o.s.nativex.NativeListener               : AOT mode enabled
2022-07-11 16:37:59.481  INFO 96854 --- [           main] b.v.s.SpringBootWebNativeApplication     : Starting SpringBootWebNativeApplication using Java 17.0.3 on MACHINE with PID 96854 (/Users/Vadzim_Kavalkou/IdeaProjects/common/performance-researches/spring-boot-web-native/build/native/nativeCompile/spring-boot-web-native started by Vadzim_Kavalkou in /Users/Vadzim_Kavalkou/IdeaProjects/common/performance-researches/spring-boot-web-native/build/native/nativeCompile)
2022-07-11 16:37:59.481  INFO 96854 --- [           main] b.v.s.SpringBootWebNativeApplication     : No active profile set, falling back to 1 default profile: "default"
2022-07-11 16:37:59.522  INFO 96854 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2022-07-11 16:37:59.523  INFO 96854 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-07-11 16:37:59.523  INFO 96854 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.64]
2022-07-11 16:37:59.529  INFO 96854 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-07-11 16:37:59.529  INFO 96854 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 47 ms
2022-07-11 16:37:59.548  INFO 96854 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2022-07-11 16:37:59.550  INFO 96854 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.6.9.Final
2022-07-11 16:37:59.552  INFO 96854 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
2022-07-11 16:37:59.555  INFO 96854 --- [           main] com.zaxxer.hikari.HikariDataSource       : hikari-pool - Starting...
2022-07-11 16:37:59.580  INFO 96854 --- [           main] com.zaxxer.hikari.HikariDataSource       : hikari-pool - Start completed.
2022-07-11 16:37:59.580  INFO 96854 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.PostgreSQL95Dialect
2022-07-11 16:37:59.583 ERROR 96854 --- [           main] org.hibernate.AssertionFailure           : HHH000099: an assertion failure occurred (this may indicate a bug in Hibernate, but is more likely due to unsafe use of the session): java.lang.NullPointerException
2022-07-11 16:37:59.583  WARN 96854 --- [           main] w.s.c.ServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory': Invocation of init method failed; nested exception is org.hibernate.AssertionFailure: Error calling ServiceLoader.Provider.type()
2022-07-11 16:37:59.583  INFO 96854 --- [           main] com.zaxxer.hikari.HikariDataSource       : hikari-pool - Shutdown initiated...
2022-07-11 16:37:59.583  INFO 96854 --- [           main] com.zaxxer.hikari.HikariDataSource       : hikari-pool - Shutdown completed.
2022-07-11 16:37:59.583  INFO 96854 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2022-07-11 16:37:59.585 ERROR 96854 --- [           main] o.s.boot.SpringApplication               : Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory': Invocation of init method failed; nested exception is org.hibernate.AssertionFailure: Error calling ServiceLoader.Provider.type()
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-boot-web-native:5.3.21]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-boot-web-native:5.3.21]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-boot-web-native:5.3.21]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-boot-web-native:5.3.21]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-boot-web-native:5.3.21]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-boot-web-native:5.3.21]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-boot-web-native:5.3.21]
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154) ~[spring-boot-web-native:5.3.21]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:908) ~[spring-boot-web-native:5.3.21]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-boot-web-native:5.3.21]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-web-native:2.7.1]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-web-native:2.7.1]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-web-native:2.7.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-web-native:2.7.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-web-native:2.7.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-web-native:2.7.1]
        at by.vk.springbootwebnative.SpringBootWebNativeApplication.main(SpringBootWebNativeApplication.java:10) ~[spring-boot-web-native:na]
Caused by: org.hibernate.AssertionFailure: Error calling ServiceLoader.Provider.type()
        at org.hibernate.boot.registry.classloading.internal.AggregatedServiceLoader$ClassPathAndModulePathAggregatedServiceLoader.collectServiceIfNotDuplicate(AggregatedServiceLoader.java:272) ~[na:na]
        at org.hibernate.boot.registry.classloading.internal.AggregatedServiceLoader$ClassPathAndModulePathAggregatedServiceLoader.loadAll(AggregatedServiceLoader.java:201) ~[na:na]
        at org.hibernate.boot.registry.classloading.internal.AggregatedServiceLoader$ClassPathAndModulePathAggregatedServiceLoader.getAll(AggregatedServiceLoader.java:187) ~[na:na]
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.loadJavaServices(ClassLoaderServiceImpl.java:251) ~[na:na]
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.handleTypes(MetadataBuildingProcess.java:390) ~[na:na]
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:132) ~[na:na]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1460) ~[na:na]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1494) ~[na:na]
        at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58) ~[na:na]
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365) ~[spring-boot-web-native:5.3.21]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409) ~[spring-boot-web-native:5.3.21]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396) ~[spring-boot-web-native:5.3.21]
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341) ~[spring-boot-web-native:5.3.21]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-boot-web-native:5.3.21]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-boot-web-native:5.3.21]
        ... 16 common frames omitted
Caused by: java.lang.NullPointerException: null
        at org.hibernate.boot.registry.classloading.internal.AggregatedServiceLoader$ClassPathAndModulePathAggregatedServiceLoader.collectServiceIfNotDuplicate(AggregatedServiceLoader.java:269) ~[na:na]
        ... 30 common frames omitted

In spite of this, `./gradlew bootRun` works perfectly.

**Comment by mhalbritter** [comment]
I don't see funky stuff in your application which could lead to a failure. But you have `com.vladmihalcea:hibernate-types-55:2.16.3` in your application. Spring Native doesn't have support for that library yet. Hopefully we can fix this with Spring Boot 3.

**Comment by fragaLY** [comment]
I've decided not to invent the wheel and removed `com.vladmihalcea:hibernate-types-55:2.16.3` from dependencies.

As a result, I have a fully working solution.

Yeah, well, I built my own theme park, with blackjack and spring native. 

The example is here: https://github.com/fragaLY/performance-researcahes/tree/master/spring-boot-web-native

The result of performance compared with the default web implementation: https://github.com/fragaLY/performance-researches/tree/master/spring-boot-web I could provide later. For sure, if you will need it.

**Comment by vladmihalcea** [comment]
@fragaLY Hibernate Types does not provide support for native environments. It's unlikely that it will work as it hadn't worked on Quarkus with GraalVM

https://github.com/vladmihalcea/hibernate-types/issues/202

If anyone wants to make it work for native environments, feel free to provide a Pull Request.

**Comment by fragaLY** [comment]
@vladmihalcea , I have a workaround at the moment. So, if I will have free time I could contribute.

**Comment by vladmihalcea** [comment]
All the best!

**Comment by ducanh2110** [comment]
@mhalbritter Hi. I have the same problems without using hibernate-types. Here is my pom `<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>vn.com.vndirect.pms</groupId>
    <artifactId>pms-api</artifactId>
    <packaging>jar</packaging>
    <version>${revision}</version>
    <name>pms-api</name>
    <url>http://maven.apache.org</url>

    <parent>
        <groupId>vn.com.vndirect.pms</groupId>
        <artifactId>pms-bom</artifactId>
        <version>1.0.3</version>
        <relativePath /> 
    </parent>

    <properties>
        <revision>2.9.7-${build.suffix}</revision>
        <java.version>11</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <spring-cloud.version>2021.0.3</spring-cloud.version>
        <mapstruct.version>1.4.2.Final</mapstruct.version>
        <jwt.version>0.9.0</jwt.version>
        <swagger.version>2.9.2</swagger.version>
        <vndid.driver.version>1.7.2</vndid.driver.version>
        <home-nlp.version>1.0.4</home-nlp.version>
        <sonar.host.url>https://sonar.vndirect.com.vn</sonar.host.url>
        <sonar.projectKey>PMS.API</sonar.projectKey>
        <sonar.login>ea6a1ac2d3852a678ee4e0f22b7fe3eb5b2c9d5c</sonar.login>
        <sonar.plugin.version>3.7.0.1746</sonar.plugin.version>
        <asciidoctor.version>1.5.8</asciidoctor.version>
        <logback.version>1.2.10</logback.version>
        <pms.model.version>1.4.4</pms.model.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-boot-starter</artifactId>
            <version>3.16.3</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.restdocs</groupId>
            <artifactId>spring-restdocs-mockmvc</artifactId>
            <scope>test</scope>
        </dependency>
        
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-boot-starter</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>31.1-jre</version>
        </dependency>


        









        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${mapstruct.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.github.ozlerhakan</groupId>
            <artifactId>poiji</artifactId>
            <version>3.0.3</version>
        </dependency>
        <dependency>
            <groupId>vn.com.vndirect.vndid</groupId>
            <artifactId>vndid-driver</artifactId>
            <version>${vndid.driver.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.solr</groupId>
                    <artifactId>solr-solrj</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-log4j2</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.homedirect.common</groupId>
            <artifactId>home-nlp</artifactId>
            <version>${home-nlp.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.solr</groupId>
                    <artifactId>solr-solrj</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.logging.log4j</groupId>
                    <artifactId>log4j-slf4j-impl</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-log4j2</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-apt</artifactId>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>vn.com.vndirect.pms</groupId>
            <artifactId>pms-model</artifactId>
            <version>${pms.model.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>spring-data-solr</artifactId>
                    <groupId>org.springframework.data</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>vn.com.vndirect.common</groupId>
            <artifactId>pms-common</artifactId>
            <version>1.0.2</version>
        </dependency>






        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.experimental</groupId>
            <artifactId>spring-native</artifactId>
            <version>0.12.1</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <profiles>
        <profile>
            <id>native</id>
            <properties>
                <build.suffix>SNAPSHOT</build.suffix>
            </properties>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.graalvm.buildtools</groupId>
                        <artifactId>native-maven-plugin</artifactId>
                        <version>0.9.0</version>
                        <executions>
                            <execution>
                                <id>build-native</id>
                                <goals>
                                    <goal>build</goal>
                                </goals>
                                <phase>package</phase>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <configuration>
                            <classifier>exec</classifier>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>local</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <build.suffix>SNAPSHOT</build.suffix>
            </properties>
        </profile>
        <profile>
            <id>dev</id>
            <properties>
                <build.suffix>SNAPSHOT</build.suffix>
            </properties>
        </profile>
        <profile>
            <id>uat</id>
            <properties>
                <build.suffix>SNAPSHOT</build.suffix>
            </properties>
        </profile>
        <profile>
            <id>staging</id>
            <properties>
                <build.suffix>RELEASE</build.suffix>
            </properties>
        </profile>
        <profile>
            <id>prod</id>
            <properties>
                <build.suffix>RELEASE</build.suffix>
            </properties>
        </profile>
    </profiles>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <image>
                        <builder>paketobuildpacks/builder:tiny</builder>
                        <env>
                            <BP_NATIVE_IMAGE>true</BP_NATIVE_IMAGE>
                        </env>
                    </image>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>build-info</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <annotationProcessors>
                        <annotationProcessor>lombok.launch.AnnotationProcessorHider$AnnotationProcessor</annotationProcessor>
                        <annotationProcessor>com.querydsl.apt.jpa.JPAAnnotationProcessor</annotationProcessor>
                        <annotationProcessor>org.mapstruct.ap.MappingProcessor</annotationProcessor>
                    </annotationProcessors>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>com.querydsl</groupId>
                            <artifactId>querydsl-core</artifactId>
                            <version>${querydsl.version}</version>
                        </path>
                        <path>
                            <groupId>com.querydsl</groupId>
                            <artifactId>querydsl-apt</artifactId>
                            <version>${querydsl.version}</version>
                        </path>
                        <path>
                            <groupId>com.mysema.codegen</groupId>
                            <artifactId>codegen</artifactId>
                            <version>0.6.8</version>
                        </path>
                        <path>
                            <groupId>org.eclipse.persistence</groupId>
                            <artifactId>javax.persistence</artifactId>
                            <version>2.1.0</version>
                        </path>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${mapstruct.version}</version>
                        </path>
                        <path>
                            <groupId>jakarta.annotation</groupId>
                            <artifactId>jakarta.annotation-api</artifactId>
                            <version>${jakarta-annotation.version}</version>
                        </path>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <compilerArg>
                            -Amapstruct.defaultComponentModel=spring
                        </compilerArg>
                    </compilerArgs>
                    <forceJavacCompilerUse>true</forceJavacCompilerUse>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.sonarsource.scanner.maven</groupId>
                <artifactId>sonar-maven-plugin</artifactId>
                <version>${sonar.plugin.version}</version>
            </plugin>
            <plugin>
                <groupId>org.asciidoctor</groupId>
                <artifactId>asciidoctor-maven-plugin</artifactId>
                <version>${asciidoctor.version}</version>
                <executions>
                    <execution>
                        <id>generate-docs</id>
                        <phase>prepare-package</phase> 
                        <goals>
                            <goal>process-asciidoc</goal>
                        </goals>
                        <configuration>
                            <backend>html</backend>
                            <doctype>book</doctype>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.springframework.restdocs</groupId>
                        <artifactId>spring-restdocs-asciidoctor</artifactId>
                        <version>${spring-restdocs.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <artifactId>maven-resources-plugin</artifactId>
                <version>2.7</version>
                <executions>
                    <execution>
                        <id>copy-resources</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>
                                ${project.build.outputDirectory}/static/docs
                            </outputDirectory>
                            <resources>
                                <resource>
                                    <directory>
                                        ${project.build.directory}/generated-docs
                                    </directory>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.springframework.experimental</groupId>
                <artifactId>spring-aot-maven-plugin</artifactId>
                <version>0.12.1</version>
                <executions>
                    <execution>
                        <id>generate</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <repositories>
        <repository>
            <id>spring-release</id>
            <name>Spring release</name>
            <url>https://repo.spring.io/release</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>spring-release</id>
            <name>Spring release</name>
            <url>https://repo.spring.io/release</url>
        </pluginRepository>
    </pluginRepositories>
</project>
`

**Comment by sdeleuze** [comment]
@ducanh2110 The proper fix should come via https://github.com/vladmihalcea/hibernate-types/issues/202.

**Comment by sdeleuze** [comment]
@ducanh2110 If you want some help, please create a dedicated issue with a full repro. Since we are focusing on Spring Boot 3 native support, I advise you to test with Spring Boot 3 M5 which has just been released, since on Spring Native side we will only fix critical issues.

**Comment by ducanh2110** [comment]
@sdeleuze thanks for support. I will try spring boot 3
