### ISSUE TITLE
Native reflection configuration for org.springframework.ws.soap.saaj.SaajSoapMessageFactory is missing.

### ISSUE THREAD

**Issue by brianmolinaspring** [spring-projects-experimental/spring-native#1696]
hello guys, how are you? I managed to compile my native image but when starting my container I get the following error:

Native reflection configuration for org.springframework.ws.soap.saaj.SaajSoapMessageFactory is missing.

022-08-21 00:27:37.907  INFO 1 --- [           main] c.c.m.MsConCbsQueryAdjustLogApplication  : Starting MsConCbsQueryAdjustLogApplication using Java 11.0.15 on 308fcc294147 with PID 1 (/workspace/com.cbs.ms.MsConCbsQueryAdjustLogApplication started by cnb in /workspace)
2022-08-21 00:27:37.907  INFO 1 --- [           main] c.c.m.MsConCbsQueryAdjustLogApplication  : No active profile set, falling back to 1 default profile: "default"
2022-08-21 00:27:37.916  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.ws.config.annotation.DelegatingWsConfiguration' of type [org.springframework.ws.config.annotation.DelegatingWsConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-08-21 00:27:37.918  INFO 1 --- [           main] .w.s.a.s.AnnotationActionEndpointMapping : Supporting [WS-Addressing August 2004, WS-Addressing 1.0]
2022-08-21 00:27:37.937  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2022-08-21 00:27:37.938  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-08-21 00:27:37.938  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.65]
2022-08-21 00:27:37.946  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-08-21 00:27:37.946  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 38 ms
2022-08-21 00:27:37.960  WARN 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'queryAdjustLogClient': Unsatisfied dependency expressed through field 'ws'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'queryAdjust': Unexpected exception during bean creation; nested exception is org.springframework.beans.factory.BeanInitializationException: Could not find default strategy class for interface [org.springframework.ws.WebServiceMessageFactory]; nested exception is java.lang.ClassNotFoundException: org.springframework.ws.soap.saaj.SaajSoapMessageFactory
2022-08-21 00:27:37.961  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2022-08-21 00:27:37.963 ERROR 1 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   :

***************************
APPLICATION FAILED TO START
***************************

Description:

Native reflection configuration for org.springframework.ws.soap.saaj.SaajSoapMessageFactory is missing.

Action:

Native configuration for a class accessed reflectively is likely missing.
You can try to configure native hints in order to specify it explicitly.
See https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#native-hints for more details.

helpme ?

**Comment by sdeleuze** [comment]
Hi, please follow what is suggested in the error message by adding a `@TypeHint(types = org.springframework.ws.soap.saaj.SaajSoapMessageFactory.class)` hint to your application.

**Comment by brianmolinaspring** [comment]
Thanks, but now obtain the following error:

.   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.7.3)

2022-08-22 16:20:08.026  INFO 1 --- [           main] c.c.m.MsConCbsQueryAdjustLogApplication  : Starting MsConCbsQueryAdjustLogApplication using Java 11.0.15 on eceecccdee9c with PID 1 (/workspace/com.cbs.ms.MsConCbsQueryAdjustLogApplication started by cnb in /workspace)
2022-08-22 16:20:08.026  INFO 1 --- [           main] c.c.m.MsConCbsQueryAdjustLogApplication  : No active profile set, falling back to 1 default profile: "default"
2022-08-22 16:20:08.026 DEBUG 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Refreshing org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext@1395e61c
2022-08-22 16:20:08.035  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.ws.config.annotation.DelegatingWsConfiguration' of type [org.springframework.ws.config.annotation.DelegatingWsConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-08-22 16:20:08.037  INFO 1 --- [           main] .w.s.a.s.AnnotationActionEndpointMapping : Supporting [WS-Addressing August 2004, WS-Addressing 1.0]
2022-08-22 16:20:08.039  WARN 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webMvcObjectMapperConfigurer': Initialization of bean failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.cache.config.internalCacheAdvisor': Unsatisfied dependency expressed through method 'cacheAdvisor' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.annotation.ProxyCachingConfiguration': Initialization of bean failed; nested exception is java.lang.IllegalArgumentException: Class org.springframework.core.annotation.TypeMappedAnnotation[] is instantiated reflectively but was never registered.Register the class by adding "unsafeAllocated" for the class in reflect-config.json.
2022-08-22 16:20:08.041 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webMvcObjectMapperConfigurer': Initialization of bean failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.cache.config.internalCacheAdvisor': Unsatisfied dependency expressed through method 'cacheAdvisor' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.annotation.ProxyCachingConfiguration': Initialization of bean failed; nested exception is java.lang.IllegalArgumentException: Class org.springframework.core.annotation.TypeMappedAnnotation[] is instantiated reflectively but was never registered.Register the class by adding "unsafeAllocated" for the class in reflect-config.json.
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:628) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:270) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:762) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:567) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[na:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:na]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:na]
        at com.cbs.ms.MsConCbsQueryAdjustLogApplication.main(MsConCbsQueryAdjustLogApplication.java:91) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:na]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.cache.config.internalCacheAdvisor': Unsatisfied dependency expressed through method 'cacheAdvisor' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.annotation.ProxyCachingConfiguration': Initialization of bean failed; nested exception is java.lang.IllegalArgumentException: Class org.springframework.core.annotation.TypeMappedAnnotation[] is instantiated reflectively but was never registered.Register the class by adding "unsafeAllocated" for the class in reflect-config.json.
        at org.springframework.aot.beans.factory.InjectedConstructionResolver.resolve(InjectedConstructionResolver.java:88) ~[na:na]
        at org.springframework.aot.beans.factory.InjectedElementResolver.resolve(InjectedElementResolver.java:35) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:0.12.1]
        at org.springframework.aot.beans.factory.InjectedElementResolver.create(InjectedElementResolver.java:66) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:0.12.1]
        at org.springframework.aot.beans.factory.BeanDefinitionRegistrar$BeanInstanceContext.create(BeanDefinitionRegistrar.java:211) ~[na:na]
        at org.springframework.aot.ContextBootstrapInitializer.lambda$initialize$141(ContextBootstrapInitializer.java:611) ~[na:na]
        at org.springframework.aot.beans.factory.BeanDefinitionRegistrar$ThrowableFunction.apply(BeanDefinitionRegistrar.java:294) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:0.12.1]
        at org.springframework.aot.beans.factory.BeanDefinitionRegistrar.lambda$instanceSupplier$0(BeanDefinitionRegistrar.java:115) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1249) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1191) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.aop.framework.autoproxy.BeanFactoryAdvisorRetrievalHelper.findAdvisorBeans(BeanFactoryAdvisorRetrievalHelper.java:91) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findCandidateAdvisors(AbstractAdvisorAutoProxyCreator.java:111) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findEligibleAdvisors(AbstractAdvisorAutoProxyCreator.java:96) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.getAdvicesAndAdvisorsForBean(AbstractAdvisorAutoProxyCreator.java:78) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:341) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:293) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:455) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1808) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        ... 15 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.annotation.ProxyCachingConfiguration': Initialization of bean failed; nested exception is java.lang.IllegalArgumentException: Class org.springframework.core.annotation.TypeMappedAnnotation[] is instantiated reflectively but was never registered.Register the class by adding "unsafeAllocated" for the class in reflect-config.json.
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:628) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:233) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1284) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1245) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:494) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:349) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:342) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.aot.ContextBootstrapInitializer.lambda$initialize$143(ContextBootstrapInitializer.java:613) ~[na:na]
        at org.springframework.aot.beans.factory.BeanDefinitionRegistrar$ThrowableSupplier.get(BeanDefinitionRegistrar.java:317) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:0.12.1]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1249) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1191) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.aot.beans.factory.InjectedConstructionResolver.lambda$resolve$0(InjectedConstructionResolver.java:83) ~[na:na]
        at org.springframework.aot.beans.factory.InjectedConstructionResolver.resolveDependency(InjectedConstructionResolver.java:97) ~[na:na]
        at org.springframework.aot.beans.factory.InjectedConstructionResolver.resolve(InjectedConstructionResolver.java:83) ~[na:na]
        ... 38 common frames omitted
Caused by: java.lang.IllegalArgumentException: Class org.springframework.core.annotation.TypeMappedAnnotation[] is instantiated reflectively but was never registered.Register the class by adding "unsafeAllocated" for the class in reflect-config.json.
        at com.oracle.svm.core.graal.snippets.SubstrateAllocationSnippets.arrayHubErrorStub(SubstrateAllocationSnippets.java:252) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:na]
        at org.springframework.core.type.classreading.MergedAnnotationReadingVisitor$ArrayVisitor.visitEnd(MergedAnnotationReadingVisitor.java:180) ~[na:na]
        at org.springframework.asm.ClassReader.readElementValues(ClassReader.java:3009) ~[na:na]
        at org.springframework.asm.ClassReader.readElementValue(ClassReader.java:3179) ~[na:na]
        at org.springframework.asm.ClassReader.readElementValues(ClassReader.java:2999) ~[na:na]
        at org.springframework.asm.ClassReader.accept(ClassReader.java:609) ~[na:na]
        at org.springframework.asm.ClassReader.accept(ClassReader.java:425) ~[na:na]
        at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:49) ~[na:na]
        at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:132) ~[na:na]
        at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:81) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.aot.context.annotation.ImportAwareBeanPostProcessor.setAnnotationMetadata(ImportAwareBeanPostProcessor.java:60) ~[na:na]
        at org.springframework.aot.context.annotation.ImportAwareBeanPostProcessor.postProcessBeforeInitialization(ImportAwareBeanPostProcessor.java:49) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        ... 64 common frames omitted

**Comment by brianmolinaspring** [comment]
@sdeleuze , could helpme?

**Comment by brianmolinaspring** [comment]
@sdeleuze @mhalbritter spring boot native has support for Jaxb2Marshaller

**Comment by mhalbritter** [comment]
> UnsupportedFeatureError: Proxy class defined by interfaces [interface java.util.List, interface org.springframework.aop.SpringProxy, interface org.springframework.aop.framework.Advised, interface org.springframework.core.DecoratingProxy] not found

See #1700.

**Comment by mhalbritter** [comment]
Regaring JAXB: It looks like the `petclinic-keyvalue` sample uses JAXB:

```
    <dependency>
      <groupId>jakarta.xml.bind</groupId>
      <artifactId>jakarta.xml.bind-api</artifactId>
    </dependency>
```

Please take a look at how XML support is configured there. Apart from that, we can't help you if you can't share a sample application. It doesn't have to be your private code, it can be another minimal project which demonstrates the issue you're having.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
