### ISSUE TITLE
 Error creating bean with name 'openApiControllerWebMvc': Unsatisfied dependency expressed through constructor parameter 3;

### ISSUE THREAD

**Issue by brianmolinaspring** [spring-projects-experimental/spring-native#1697]
hello guys, could you help me?

```
2022-08-20 20:54:22 INFO  o.s.nativex.NativeListener - AOT mode enabled

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.7.3)

2022-08-20 20:54:22 INFO  c.p.ms.GetCouponsDetailsApplication - Starting GetCouponsDetailsApplication using Java 11.0.15 on 7dffaec9dc92 with PID 1 (/workspace/com.psp.ms.GetCouponsDetailsApplication started by cnb in /workspace)
2022-08-20 20:54:22 INFO  c.p.ms.GetCouponsDetailsApplication - No active profile set, falling back to 1 default profile: "default"
2022-08-20 20:54:22 DEBUG o.s.b.w.s.c.ServletWebServerApplicationContext - Refreshing org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext@37d0350
2022-08-20 20:54:22 INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.springframework.ws.config.annotation.DelegatingWsConfiguration' of type [org.springframework.ws.config.annotation.DelegatingWsConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-08-20 20:54:22 INFO  o.s.w.s.a.s.AnnotationActionEndpointMapping - Supporting [WS-Addressing August 2004, WS-Addressing 1.0]
2022-08-20 20:54:22 DEBUG o.s.b.w.e.t.TomcatServletWebServerFactory - Code archive: /workspace/com.psp.ms.GetCouponsDetailsApplication
2022-08-20 20:54:22 DEBUG o.s.b.w.e.t.TomcatServletWebServerFactory - Code archive: /workspace/com.psp.ms.GetCouponsDetailsApplication
2022-08-20 20:54:22 DEBUG o.s.b.w.e.t.TomcatServletWebServerFactory - None of the document roots [src/main/webapp, public, static] point to a directory and will be ignored.
2022-08-20 20:54:22 INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat initialized with port(s): 8081 (https)
2022-08-20 20:54:22 INFO  o.a.catalina.core.StandardService - Starting service [Tomcat]
2022-08-20 20:54:22 INFO  o.a.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/9.0.65]
2022-08-20 20:54:22 INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext
2022-08-20 20:54:22 DEBUG o.s.b.w.s.c.ServletWebServerApplicationContext - Published root WebApplicationContext as ServletContext attribute with name [org.springframework.web.context.WebApplicationContext.ROOT]
2022-08-20 20:54:22 INFO  o.s.b.w.s.c.ServletWebServerApplicationContext - Root WebApplicationContext: initialization completed in 55 ms
2022-08-20 20:54:22 DEBUG o.s.b.w.s.ServletContextInitializerBeans - Mapping filters: characterEncodingFilter urls=[/*] order=-2147483648, formContentFilter urls=[/*] order=-9900, requestContextFilter urls=[/*] order=-105
2022-08-20 20:54:22 DEBUG o.s.b.w.s.ServletContextInitializerBeans - Mapping servlets: dispatcherServlet urls=[/], messageDispatcherServlet urls=[/services/*]
2022-08-20 20:54:22 DEBUG o.s.b.w.s.f.OrderedRequestContextFilter - Filter 'requestContextFilter' configured for use
2022-08-20 20:54:22 DEBUG o.s.b.w.s.f.OrderedCharacterEncodingFilter - Filter 'characterEncodingFilter' configured for use
2022-08-20 20:54:22 DEBUG o.s.b.w.s.f.OrderedFormContentFilter - Filter 'formContentFilter' configured for use
2022-08-20 20:54:22 INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2022-08-20 20:54:24 INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2022-08-20 20:54:24 DEBUG o.s.b.a.AutoConfigurationPackages - @EnableAutoConfiguration was declared on a class in the package 'com.psp.ms'. Automatic @Repository and @Entity scanning is enabled.
2022-08-20 20:54:24 INFO  o.h.jpa.internal.util.LogHelper - HHH000204: Processing PersistenceUnitInfo [name: default]
2022-08-20 20:54:24 INFO  org.hibernate.Version - HHH000412: Hibernate ORM core version 5.6.10.Final
2022-08-20 20:54:24 INFO  o.h.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
2022-08-20 20:54:24 INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.Oracle10gDialect
2022-08-20 20:54:24 INFO  o.h.e.t.j.p.i.JtaPlatformInitiator - HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2022-08-20 20:54:24 INFO  o.s.o.j.LocalContainerEntityManagerFactoryBean - Initialized JPA EntityManagerFactory for persistence unit 'default'
2022-08-20 20:54:24 DEBUG o.s.b.c.p.s.ConfigurationPropertySourcesPropertyResolver$DefaultResolver - Found key 'server.variables.msgType' in PropertySource 'Config resource 'class path resource [application.yml]' via location 'optional:classpath:/'' with value of type String
2022-08-20 20:54:24 DEBUG o.s.b.c.p.s.ConfigurationPropertySourcesPropertyResolver$DefaultResolver - Found key 'server.variables.msgTypeE' in PropertySource 'Config resource 'class path resource [application.yml]' via location 'optional:classpath:/'' with value of type String
2022-08-20 20:54:24 DEBUG o.s.b.c.p.s.ConfigurationPropertySourcesPropertyResolver$DefaultResolver - Found key 'error.MSG125.code' in PropertySource 'Config resource 'class path resource [application.yml]' via location 'optional:classpath:/'' with value of type String
2022-08-20 20:54:24 DEBUG o.s.b.c.p.s.ConfigurationPropertySourcesPropertyResolver$DefaultResolver - Found key 'error.MSG125.description' in PropertySource 'Config resource 'class path resource [application.yml]' via location 'optional:classpath:/'' with value of type String
2022-08-20 20:54:24 DEBUG o.s.b.c.p.s.ConfigurationPropertySourcesPropertyResolver$DefaultResolver - Found key 'error.MSG001.code' in PropertySource 'Config resource 'class path resource [application.yml]' via location 'optional:classpath:/'' with value of type String
2022-08-20 20:54:24 DEBUG o.s.b.c.p.s.ConfigurationPropertySourcesPropertyResolver$DefaultResolver - Found key 'error.MSG001.description' in PropertySource 'Config resource 'class path resource [application.yml]' via location 'optional:classpath:/'' with value of type String
2022-08-20 20:54:24 DEBUG o.s.b.c.p.s.ConfigurationPropertySourcesPropertyResolver$DefaultResolver - Found key 'error.MSG122.code' in PropertySource 'Config resource 'class path resource [application.yml]' via location 'optional:classpath:/'' with value of type String
2022-08-20 20:54:24 DEBUG o.s.b.c.p.s.ConfigurationPropertySourcesPropertyResolver$DefaultResolver - Found key 'error.MSG122.description' in PropertySource 'Config resource 'class path resource [application.yml]' via location 'optional:classpath:/'' with value of type String
2022-08-20 20:54:24 WARN  o.s.b.w.s.c.ServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'openApiControllerWebMvc': Unsatisfied dependency expressed through constructor parameter 3; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webMvcOpenApiTransformationFilterRegistry': Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'type' of bean class [org.springframework.plugin.core.support.PluginRegistryFactoryBean]: Bean property 'type' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
2022-08-20 20:54:24 INFO  o.s.o.j.LocalContainerEntityManagerFactoryBean - Closing JPA EntityManagerFactory for persistence unit 'default'
2022-08-20 20:54:24 INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2022-08-20 20:54:26 INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
2022-08-20 20:54:26 INFO  o.a.catalina.core.StandardService - Stopping service [Tomcat]
2022-08-20 20:54:26 ERROR o.s.boot.SpringApplication - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'openApiControllerWebMvc': Unsatisfied dependency expressed through constructor parameter 3; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webMvcOpenApiTransformationFilterRegistry': Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'type' of bean class [org.springframework.plugin.core.support.PluginRegistryFactoryBean]: Bean property 'type' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
        at org.springframework.aot.beans.factory.InjectedConstructionResolver.resolve(InjectedConstructionResolver.java:88)
        at org.springframework.aot.beans.factory.InjectedElementResolver.resolve(InjectedElementResolver.java:35)
        at org.springframework.aot.beans.factory.InjectedElementResolver.create(InjectedElementResolver.java:66)
        at org.springframework.aot.beans.factory.BeanDefinitionRegistrar$BeanInstanceContext.create(BeanDefinitionRegistrar.java:211)
        at org.springframework.aot.ContextBootstrapInitializer.lambda$initialize$2(ContextBootstrapInitializer.java:360)        at org.springframework.aot.beans.factory.BeanDefinitionRegistrar$ThrowableFunction.apply(BeanDefinitionRegistrar.java:294)
        at org.springframework.aot.beans.factory.BeanDefinitionRegistrar.lambda$instanceSupplier$0(BeanDefinitionRegistrar.java:115)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1249)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1191)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
        at com.psp.ms.GetCouponsDetailsApplication.main(GetCouponsDetailsApplication.java:16)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webMvcOpenApiTransformationFilterRegistry': Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'type' of bean class [org.springframework.plugin.core.support.PluginRegistryFactoryBean]: Bean property 'type' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1744)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1452)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
        at org.springframework.aot.beans.factory.InjectedConstructionResolver.lambda$resolve$0(InjectedConstructionResolver.java:83)
        at org.springframework.aot.beans.factory.InjectedConstructionResolver.resolveDependency(InjectedConstructionResolver.java:97)
        at org.springframework.aot.beans.factory.InjectedConstructionResolver.resolve(InjectedConstructionResolver.java:83)
        ... 24 common frames omitted
Caused by: org.springframework.beans.NotWritablePropertyException: Invalid property 'type' of bean class [org.springframework.plugin.core.support.PluginRegistryFactoryBean]: Bean property 'type' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
        at org.springframework.beans.BeanWrapperImpl.createNotWritablePropertyException(BeanWrapperImpl.java:243)
        at org.springframework.beans.AbstractNestablePropertyAccessor.processLocalProperty(AbstractNestablePropertyAccessor.java:432)
        at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:278)
        at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:266)
        at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:104)
        at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:79)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1740)
        ... 37 common frames omitted
```

**Comment by mhalbritter** [comment]
If you'd like us to spend some time investigating, please take the time to provide a complete minimal sample (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by brianmolinaspring** [comment]
hello how are you, currently I can not share the project since it is private, how else could you help me?

**Comment by brianmolinaspring** [comment]
hello guys, could you help me?

now get this error

2022-08-22 20:32:34.026  WARN 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Exception encountered during context initializati
on - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'swagger2Controll
erWebMvc': Unsatisfied dependency expressed through constructor parameter 3; nested exception is org.springframework.beans.factory.BeanCreationExc
eption: Error creating bean with name 'webMvcSwaggerTransformationFilterRegistry': FactoryBean threw exception on object creation; nested exceptio
n is com.oracle.svm.core.jdk.UnsupportedFeatureError: Proxy class defined by interfaces [interface java.util.List, interface org.springframework.a
op.SpringProxy, interface org.springframework.aop.framework.Advised, interface org.springframework.core.DecoratingProxy] not found. Generating pro
xy classes at runtime is not supported. Proxy classes need to be defined at image build time by specifying the list of interfaces that they implem
ent. To define proxy classes use -H:DynamicProxyConfigurationFiles=<comma-separated-config-files> and -H:DynamicProxyConfigurationResources=<comma
-separated-config-resources> options.
2022-08-22 20:32:34.026  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2022-08-22 20:32:34.028 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'swagger2ControllerWebMvc': Unsatisfied dependency
 expressed through constructor parameter 3; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with 
name 'webMvcSwaggerTransformationFilterRegistry': FactoryBean threw exception on object creation; nested exception is com.oracle.svm.core.jdk.Unsu
pportedFeatureError: Proxy class defined by interfaces [interface java.util.List, interface org.springframework.aop.SpringProxy, interface org.spr
ingframework.aop.framework.Advised, interface org.springframework.core.DecoratingProxy] not found. Generating proxy classes at runtime is not supp
orted. Proxy classes need to be defined at image build time by specifying the list of interfaces that they implement. To define proxy classes use 
-H:DynamicProxyConfigurationFiles=<comma-separated-config-files> and -H:DynamicProxyConfigurationResources=<comma-separated-config-resources> opti
ons.
        at org.springframework.aot.beans.factory.InjectedConstructionResolver.resolve(InjectedConstructionResolver.java:88) ~[na:na]
        at org.springframework.aot.beans.factory.InjectedElementResolver.resolve(InjectedElementResolver.java:35) ~[com.cbs.ms.MsConCbsQueryAdjust
LogApplication:0.12.1]
        at org.springframework.aot.beans.factory.InjectedElementResolver.create(InjectedElementResolver.java:66) ~[com.cbs.ms.MsConCbsQueryAdjustL
ogApplication:0.12.1]
        at org.springframework.aot.beans.factory.BeanDefinitionRegistrar$BeanInstanceContext.create(BeanDefinitionRegistrar.java:211) ~[na:na]    
        at org.springframework.aot.ContextBootstrapInitializer.lambda$initialize$1(ContextBootstrapInitializer.java:350) ~[na:na]
        at org.springframework.aot.beans.factory.BeanDefinitionRegistrar$ThrowableFunction.apply(BeanDefinitionRegistrar.java:294) ~[com.cbs.ms.Ms
ConCbsQueryAdjustLogApplication:0.12.1]
        at org.springframework.aot.beans.factory.BeanDefinitionRegistrar.lambda$instanceSupplier$0(BeanDefinitionRegistrar.java:115) ~[na:na]     
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java
:1249) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java
:1191) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) 
~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[
com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[com.cbs.ms.MsConCbsQue
ryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[com.cbs.ms
.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[com.cbs.ms.MsConCbsQueryAdjustL
ogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[com.cbs.ms.MsConCbsQueryAdjustLog
Application:5.3.22]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[co
m.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[c
om.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[com.cbs.ms.MsConCbsQueryA
djustLogApplication:5.3.22]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[
na:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:na]      
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:na
]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:na]
        at com.cbs.ms.MsConCbsQueryAdjustLogApplication.main(MsConCbsQueryAdjustLogApplication.java:92) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplica
tion:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webMvcSwaggerTransformationFilterRegistry': Fac
toryBean threw exception on object creation; nested exception is com.oracle.svm.core.jdk.UnsupportedFeatureError: Proxy class defined by interface
s [interface java.util.List, interface org.springframework.aop.SpringProxy, interface org.springframework.aop.framework.Advised, interface org.spr
ingframework.core.DecoratingProxy] not found. Generating proxy classes at runtime is not supported. Proxy classes need to be defined at image buil
d time by specifying the list of interfaces that they implement. To define proxy classes use -H:DynamicProxyConfigurationFiles=<comma-separated-co
nfig-files> and -H:DynamicProxyConfigurationResources=<comma-separated-config-resources> options.
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:176) ~[
com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:101) ~[co
m.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1884) ~[com.cbs.ms.MsCo
nCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactor
y.java:1284) ~[com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:345) ~[com.cbs.ms.MsConCbsQueryAdjustL
ogApplication:5.3.22]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[com.cbs.ms.MsConCbsQueryAdjustLog
Application:5.3.22]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[com.cbs.ms.MsConCbsQuer
yAdjustLogApplication:5.3.22]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391) ~[com.cb
s.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        at org.springframework.plugin.core.support.AbstractTypeAwareSupport.getBeans(AbstractTypeAwareSupport.java:94) ~[com.cbs.ms.MsConCbsQueryA
djustLogApplication:2.0.0.RELEASE]
        at org.springframework.plugin.core.support.PluginRegistryFactoryBean.getObject(PluginRegistryFactoryBean.java:38) ~[com.cbs.ms.MsConCbsQue
ryAdjustLogApplication:2.0.0.RELEASE]
        at org.springframework.plugin.core.support.PluginRegistryFactoryBean.getObject(PluginRegistryFactoryBean.java:29) ~[com.cbs.ms.MsConCbsQue
ryAdjustLogApplication:2.0.0.RELEASE]
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:169) ~[
com.cbs.ms.MsConCbsQueryAdjustLogApplication:5.3.22]
        ... 35 common frames omitted

**Comment by mhalbritter** [comment]
The solution is the same as in https://github.com/spring-projects-experimental/spring-native/issues/1700

**Comment by czp3009** [comment]
hi @brianmolinaspring , how you turn "Bean property 'type' is not writable or has an invalid setter method" problem to "Proxy class defined by interfaces XXX" problem?  I'm stuck on first problem too.
