### ISSUE TITLE
NativeImageGeneratorRunner must not contain "."

### ISSUE THREAD

**Issue by cforce** [spring-projects-experimental/spring-native#1732]
Running native image commpile from maven under WIndows (triggerd from sindie Intelli) runs into following issue
Any idea where it comes from?
Is the way how the plugin call sthe builder is an issue?
"This can happen implicitly if the builder runs exclusively on the --module-path but specifies the com.oracle.svm.hosted.NativeImageGeneratorRunner main class without --module."

```
C:\Users\User\.jdks\graalvm-ce-19\bin\java.exe -Dmaven.multiModuleProjectDirectory=C:\Users\User\git\serverless\mic-cloud-function-aws -Dmaven.home=C:\Users\User\.m2\wrapper\dists\apache-maven-3.8.1-bin\2l5mhf2pq2clrde7f7qp1rdt5m\apache-maven-3.8.1 -Dclassworlds.conf=C:\Users\User\.m2\wrapper\dists\apache-maven-3.8.1-bin\2l5mhf2pq2clrde7f7qp1rdt5m\apache-maven-3.8.1\bin\m2.conf -Dmaven.ext.class.path=C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-2\222.4345.14\plugins\maven\lib\maven-event-listener.jar -javaagent:C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-2\222.4345.14\lib\idea_rt.jar=51601:C:\Users\User\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-2\222.4345.14\bin -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath C:\Users\User\.m2\wrapper\dists\apache-maven-3.8.1-bin\2l5mhf2pq2clrde7f7qp1rdt5m\apache-maven-3.8.1\boot\plexus-classworlds-2.6.0.jar;C:\Users\User\.m2\wrapper\dists\apache-maven-3.8.1-bin\2l5mhf2pq2clrde7f7qp1rdt5m\apache-maven-3.8.1\boot\plexus-classworlds.license org.codehaus.classworlds.Launcher -Didea.version=2022.2.3 -DskipTests=true package -P native
...

[INFO] 
[INFO] --- native-maven-plugin:0.9.15:compile-no-fork (build-native) @ cloud-function-aws ---
[INFO] Executing: C:\Program Files\GraalVM\graalvm-ce-java17-22.2.0\bin\native-image.cmd -cp C:\Users\User\git\serverless\mic-cloud-function-aws\target\cloud-function-aws-0_0_1-SNAPSHOT-shaded.jar --no-fallback -H:Path=C:\Users\User\git\serverless\mic-cloud-function-aws\target -H:Name=cloud-function-aws --enable-url-protocols=http -H:+AddAllCharsets
Fatal error: com.oracle.svm.core.util.VMError$HostedError: The classpath of com.oracle.svm.hosted.NativeImageGeneratorRunner must not contain ".". This can happen implicitly if the builder runs exclusively on the --module-path but specifies the com.oracle.svm.hosted.NativeImageGeneratorRunner main class without --module.
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageClassLoaderSupport.<init>(NativeImageClassLoaderSupport.java:130)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.installNativeImageClassLoader(NativeImageGeneratorRunner.java:180)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:123)
Error: Image build request failed with exit status 1
```

**Comment by sdeleuze** [comment]
Please use Spring Boot 3 native support which supersedes Spring Native.

**Comment by cforce** [comment]
I do already. This report was based on spring boot 3.
