### ISSUE TITLE
Getting: 'Entity has no identifier' when Entity inherits AbstractAuditable<U, PK>

### ISSUE THREAD

**Issue by sic-sic** [spring-projects-experimental/spring-native#1733]
Here is a demo project:

https://github.com/sic-sic/native-abstract-auditable

The project runs fine without native compilation but when i run the native image, I receive the following error:

	org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory': Entity 'com.example.demo.model.Blog' has no identifier (every '@Entity' class must declare or inherit at least one '@Id' or '@EmbeddedId' property)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1753) ~[demo:6.0.0-RC4]
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599) ~[demo:6.0.0-RC4]
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[demo:6.0.0-RC4]
		at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[demo:6.0.0-RC4]
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[demo:6.0.0-RC4]
		at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[demo:6.0.0-RC4]
		at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[demo:6.0.0-RC4]
		at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1131) ~[demo:6.0.0-RC4]
		at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:906) ~[demo:6.0.0-RC4]
		at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[demo:6.0.0-RC4]
		at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[demo:3.0.0-RC2]
		at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[demo:3.0.0-RC2]
		at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[demo:3.0.0-RC2]
		at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[demo:3.0.0-RC2]
		at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[demo:3.0.0-RC2]
		at com.example.demo.DemoApplication.main(DemoApplication.java:15) ~[demo:na]
	Caused by: org.hibernate.AnnotationException: Entity 'com.example.demo.model.Blog' has no identifier (every '@Entity' class must declare or inherit at least one '@Id' or '@EmbeddedId' property)
		at org.hibernate.cfg.InheritanceState.determineDefaultAccessType(InheritanceState.java:266) ~[na:na]
		at org.hibernate.cfg.InheritanceState.getElementsToProcess(InheritanceState.java:210) ~[na:na]
		at org.hibernate.cfg.annotations.EntityBinder.bindEntityClass(EntityBinder.java:260) ~[na:na]
		at org.hibernate.cfg.AnnotationBinder.bindClass(AnnotationBinder.java:556) ~[na:na]
		at org.hibernate.boot.model.source.internal.annotations.AnnotationMetadataSourceProcessorImpl.processEntityHierarchies(AnnotationMetadataSourceProcessorImpl.java:216) ~[na:na]
		at org.hibernate.boot.model.process.spi.MetadataBuildingProcess$1.processEntityHierarchies(MetadataBuildingProcess.java:247) ~[na:na]
		at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:290) ~[na:na]
		at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1350) ~[demo:6.1.5.Final]
		at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1421) ~[demo:6.1.5.Final]
		at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:66) ~[na:na]
		at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:376) ~[demo:na]
		at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409) ~[demo:na]
		at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396) ~[demo:na]
		at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:352) ~[demo:na]
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1799) ~[demo:6.0.0-RC4]
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1749) ~[demo:6.0.0-RC4]
		... 15 common frames omitted

**Comment by mhalbritter** [comment]
Hey, can you please try if this works with Spring Boot 3 and if not, create an issue? Thanks!
