### ISSUE TITLE
Mybatis - org.springframework.boot.context.properties.bind.MissingParametersCompilerArgumentException

### ISSUE THREAD

**Issue by AllKai** [spring-projects-experimental/spring-native#1738]
**Current environment :**

SpringBoot > 3.0.0
GraalVM > graalvm-java17-22.3.0
Mybatis > 3.5.11
Mybatis-Spring > 3.0.1

**Configuration related to plug-ins：**

```xml
<repositories>
    <repository>
      <id>spring-milestones</id>
      <name>Spring Milestones</name>
      <url>https://repo.spring.io/milestone</url>
    </repository>
  </repositories>
  <pluginRepositories>
    <pluginRepository>
      <id>spring-milestones</id>
      <name>Spring Milestones</name>
      <url>https://repo.spring.io/milestone</url>
    </pluginRepository>
  </pluginRepositories>

  <build>
    <finalName>${project.artifactId}</finalName>
    <plugins>
      <plugin>
        <groupId>org.graalvm.buildtools</groupId>
        <artifactId>native-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <excludes>
            <exclude>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
            </exclude>
          </excludes>
        </configuration>
      </plugin>
    </plugins>
  </build>
```
**Problem：**
when i execute the `mvn clean native:compile -Pnative` command,the following error will occur
```
Exception in thread "main" org.springframework.boot.context.properties.bind.MissingParametersCompilerArgumentException: Constructor binding in a native image requires compilation with -parameters but the following classes were compiled without it:
	org.apache.ibatis.mapping.ResultFlag
	org.apache.ibatis.builder.CacheRefResolver
	org.apache.ibatis.builder.annotation.MethodResolver
	org.apache.ibatis.parsing.XNode
	org.apache.ibatis.builder.ResultMapResolver
	at org.springframework.boot.context.properties.bind.BindableRuntimeHintsRegistrar.registerHints(BindableRuntimeHintsRegistrar.java:87)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBeanFactoryInitializationAotProcessor$ConfigurationPropertiesReflectionHintsContribution.applyTo(ConfigurationPropertiesBeanFactoryInitializationAotProcessor.java:70)
	at org.springframework.context.aot.BeanFactoryInitializationAotContributions.applyTo(BeanFactoryInitializationAotContributions.java:78)
	at org.springframework.context.aot.ApplicationContextAotGenerator.lambda$processAheadOfTime$0(ApplicationContextAotGenerator.java:58)
	at org.springframework.context.aot.ApplicationContextAotGenerator.withCglibClassHandler(ApplicationContextAotGenerator.java:67)
	at org.springframework.context.aot.ApplicationContextAotGenerator.processAheadOfTime(ApplicationContextAotGenerator.java:53)
	at org.springframework.context.aot.ContextAotProcessor.performAotProcessing(ContextAotProcessor.java:106)
	at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:84)
	at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:49)
	at org.springframework.context.aot.AbstractAotProcessor.process(AbstractAotProcessor.java:82)
	at org.springframework.boot.SpringApplicationAotProcessor.main(SpringApplicationAotProcessor.java:76)
```
What am I going to do now?

**Comment by mhalbritter** [comment]
If you're using Spring Boot 3.0.0, you should not use Spring Native. Spring Native is for 2.x only. If you're using Spring Boot 3.0.0 and NOT spring-native but the built-in native support, you're in the wrong issue tracker. Please report that issue on https://github.com/spring-projects/spring-boot/issues. Thanks!
