### ISSUE TITLE
Native Image with Spring Boot 3.0.1 throwing Missing character set id 560 is not loaded at image build time Error

### ISSUE THREAD

**Issue by syedyusufh** [spring-projects-experimental/spring-native#1743]
Have built a native image using the latest version 3.0.1 (after solving many errors) and seeing the below error when application tries to connect to a Oracle database during startup.

Have tried `-H:+AddAllCharsets` and wasn't solving the issue either

```
java.lang.IllegalStateException: Missing character set id 560 is not loaded at image build time
        at oracle.sql.CharacterSet.make(CharacterSet.java:121) ~[xxxxxx:21.6.0.0.0]
        at oracle.jdbc.driver.DBConversion.init(DBConversion.java:184) ~[na:na]
        at oracle.jdbc.driver.DBConversion.<init>(DBConversion.java:137) ~[na:na]
        at oracle.jdbc.driver.T4CConnection.doCharSetNegotiation(T4CConnection.java:3122) ~[xxxxxxx:21.6.0.0.0]
        at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:2658) ~[xxxxxx:21.6.0.0.0]
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:666) ~[xxxxxx:21.6.0.0.0]
        at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:1088) ~[xxxxxx:21.6.0.0.0]
        at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:89) ~[xxxxxx:21.6.0.0.0]
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:732) ~[xxxxxx:21.6.0.0.0]
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:648) ~[xxxxxxx:21.6.0.0.0]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[na:na]
```

**Comment by sdeleuze** [comment]
Hi, likely an issue to raise on https://github.com/oracle/graalvm-reachability-metadata side.
