### ISSUE TITLE
org.springframework.boot.context.properties.ConfigurationPropertiesBeanRegistrationWriterSupplier not found in boot 3.0.1, but referenced from aot 0.12.1

### ISSUE THREAD

**Issue by oeresundsgruppen** [spring-projects-experimental/spring-native#1746]
java.lang.IllegalArgumentException: Unable to instantiate factory class [org.springframework.boot.context.properties.ConfigurationPropertiesBeanRegistrationWriterSupplier] for factory type [org.springframework.aot.context.bootstrap.generator.bean.BeanRegistrationWriterSupplier]
        at org.springframework.core.io.support.SpringFactoriesLoader$FailureHandler.lambda$throwing$0(SpringFactoriesLoader.java:650)
        at org.springframework.core.io.support.SpringFactoriesLoader$FailureHandler.lambda$handleMessage$3(SpringFactoriesLoader.java:674)
        at org.springframework.core.io.support.SpringFactoriesLoader.instantiateFactory(SpringFactoriesLoader.java:231)
        at org.springframework.core.io.support.SpringFactoriesLoader.load(SpringFactoriesLoader.java:206)
        at org.springframework.core.io.support.SpringFactoriesLoader.load(SpringFactoriesLoader.java:142)
        at org.springframework.core.io.support.SpringFactoriesLoader.loadFactories(SpringFactoriesLoader.java:254)
        at org.springframework.aot.context.bootstrap.generator.ApplicationContextAotProcessor.<init>(ApplicationContextAotProcessor.java:81)

**Comment by sdeleuze** [comment]
Spring Native is now superseded by Spring Boot 3 official native support, see [the related reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html) for more details.

As a consequence, I am closing this issue, and recommend trying your use case with latest Spring Boot 3 version. If you still experience the issue reported here, please open an issue directly on the related Spring project (Spring Framework, Data, Security, Boot, Cloud, etc.) with a reproducer.

Thanks for your contribution on the experimental Spring Native project, we hope you will enjoy the official native support introduced by Spring Boot 3.
