### ISSUE TITLE
NoClassDefFoundError DispatcherServlet

### ISSUE THREAD

**Issue by onexuan** [spring-projects-experimental/spring-native#1750]
Spring Boot 3.0.2

Application run failed
java.lang.NoClassDefFoundError: org.springframework.web.servlet.DispatcherServlet
        at org.springframework.boot.autoconfigure.web.servlet.DispatcherServletAutoConfiguration__BeanDefinitions$DispatcherServletConfiguration__BeanDefinitions.getDispatcherServletBeanDefinition(DispatcherServletAutoConfiguration__BeanDefinitions.java:84)
        at com.meto.XApplication__BeanFactoryRegistrations.registerBeanDefinitions(XApplication__BeanFactoryRegistrations.java:132)
        at com.meto.XApplication__ApplicationContextInitializer.initialize(XApplication__ApplicationContextInitializer.java:26)
        at com.meto.initialize(XApplication__ApplicationContextInitializer.java:19)
        at org.springframework.context.aot.AotApplicationContextInitializer.initialize(AotApplicationContextInitializer.java:72)
        at org.springframework.context.aot.AotApplicationContextInitializer.lambda$forInitializerClasses$0(AotApplicationContextInitializer.java:61)
        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:603)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:383)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291)

how to fix this?

**Comment by onexuan** [comment]
I got warming

Warning: Could not resolve org.springframework.web.servlet.DispatcherServlet for reflection configuration. Reason: java.lang.NoClassDefFoundError: jakarta/servlet/http/HttpServlet.
Warning: Could not resolve io.netty.channel.socket.nio.NioServerSocketChannel for reflection configuration. Reason: java.lang.ClassNotFoundException: io.netty.channel.socket.nio.NioServerSocketChannel.

How to fix

**Comment by onexuan** [comment]
NoClassDefFoundError  DispatcherServlet  error has been fixed
But how to fix io.netty.channel.socket.nio.NioServerSocketChannel for reflection configuration. Reason: java.lang.ClassNotFoundException: io.netty.channel.socket.nio.NioServerSocketChannel.
