### ISSUE TITLE
Add Spring Security support

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#247]

**Comment by sdeleuze** [comment]
See related #289 issue.

**Comment by doujs** [comment]
windows  platform , graalvm-ce-java11-20.2.0 and spring-graalvm-native-0.8.2 . I'm working on building a working project to exe for quite a few days and encounter many problems. current is , when I compiled to native exe and run , it prints:


java.lang.IllegalStateException: java.security.NoSuchAlgorithmException: RSA KeyFactory not available
        at org.springframework.security.converter.RsaKeyConverters.rsaFactory(RsaKeyConverters.java:135) ~[na:na]
        at org.springframework.security.converter.RsaKeyConverters.pkcs8(RsaKeyConverters.java:71) ~[na:na]
        at org.springframework.security.config.crypto.RsaKeyConversionServicePostProcessor.pkcs8(RsaKeyConversionServicePostProcessor.java:88) ~[na:na]
        at org.springframework.security.config.crypto.RsaKeyConversionServicePostProcessor.postProcessBeanFactory(RsaKeyConversionServicePostProcessor.java:65) ~[na:na]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:299) ~[na:na]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:185) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:751) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:569) ~[na:na]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[na:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:770) ~[na:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762) ~[na:na]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:421) ~[na:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:329) ~[na:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[na:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[na:na]
        at com.kingbase.AppRun.main(AppRun.java:55) ~[com.kingbase.apprun.exe:na]
Caused by: java.security.NoSuchAlgorithmException: RSA KeyFactory not available
        at java.security.KeyFactory.<init>(KeyFactory.java:138) ~[na:na]
        at java.security.KeyFactory.getInstance(KeyFactory.java:183) ~[na:na]
        at org.springframework.security.converter.RsaKeyConverters.rsaFactory(RsaKeyConverters.java:132) ~[na:na]
        ... 15 common frames omitted

**Comment by eleftherias** [comment]
Thanks for reaching out @doujs. 
We're still actively working on adding Spring Security support.

Can you share some more information on the type of application you are building?
Is it a servlet app or reactive? What kind of security are you using? Form login, OAuth2?

**Comment by mraible** [comment]
I've found you need to add `--enable-https` to solve this issue.

```xml
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <configuration>
        <image>
            <env>
                <BP_BOOT_NATIVE_IMAGE>1</BP_BOOT_NATIVE_IMAGE>
                <BP_BOOT_NATIVE_IMAGE_BUILD_ARGUMENTS>
                    -Dspring.native.remove-yaml-support=true
                    -Dspring.spel.ignore=true
                    --enable-https
                </BP_BOOT_NATIVE_IMAGE_BUILD_ARGUMENTS>
            </env>
        </image>
    </configuration>
</plugin>
```

https://github.com/okta/okta-spring-boot/issues/192#issuecomment-696485752

**Comment by sdeleuze** [comment]
@mraible Thanks for your feedback. We [kind of document that](https://repo.spring.io/milestone/org/springframework/experimental/spring-graalvm-native-docs/0.8.2/spring-graalvm-native-docs-0.8.2.zip!/reference/index.html#_other_options_2) but we could probably make that more discoverable.

@eleftherias We could maybe also work on setting that automatically when needed via #225.

**Comment by doujs** [comment]
@mraible thank you very much , it works now , but i'm encounting another error ,  checking....
@eleftherias It's a servlet app[spring mvc] and Form login.

**Comment by eleftherias** [comment]
@doujs Have you looked at the security sample in this repo? It is also a servlet app with form login. https://github.com/spring-projects-experimental/spring-graalvm-native/tree/master/spring-graalvm-native-samples/security

@sdeleuze Yes, I like the idea of setting the flag automatically.

**Comment by doujs** [comment]
@eleftherias yes , I have read the samples and the docs . I didn't start from the sample but from our working project , so I didn't notice thant . Besides , I think maybe it's better to put the arguments together and tell when to use them , maybe it's better to give an example

**Comment by sdeleuze** [comment]
We could indeed probably improve our documentation for now, I have created the related #352 issue.

**Comment by christian-draeger** [comment]
according to the [example project for spring security](https://github.com/spring-projects-experimental/spring-graalvm-native/tree/master/spring-graalvm-native-samples/security) you need to add the `--enable-all-security-services` (found it in the `compile.sh`). 
had the same error as described and setting the flag at native-image helped. (i'm running a servlet app with basic auth)

**Comment by sdeleuze** [comment]
@eleftherias As discussed previously, I have added required flags for dependency using a starter by starter granularity to the [support documentation](https://github.com/spring-projects-experimental/spring-graalvm-native/blob/master/spring-graalvm-native-docs/src/main/asciidoc/support.adoc). Since `master` branch is now targeting `0.9.0-SNAPSHOT`, feels free to add Spring Security  starter with the limitation of the support and the potentially required flags.

For HTTPS, I think `--enable-https` should be favored against `-H:EnableURLProtocols=http,https` (I think this is equivalent but to be checked). It would be helpful to identify when `--enable-all-security-services` is required (always?).

We can relax the documented limitations as this support progress.

**Comment by eleftherias** [comment]
Closing this issue, since initial Spring Security support is available.

This issue encompasses:

- Form login
- HTTP basic authentication 
- OAuth 2.0
- RSocket Security
- Kotlin Security DSL for WebMvc applications

For any additional features new issues should be created.
