### ISSUE TITLE
Spring Cloud Function not working with Tomcat

### ISSUE THREAD

**Issue by dsyer** [spring-projects-experimental/spring-native#368]
The sample is Netty so I guess we just never tested this yet. The error at runtime is:

```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.context.ApplicationContextInitializer : org.springframework.cloud.function.web.function.FunctionEndpointInitializer
        at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:467)
        at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:449)
        at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:442)
        at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:284)
        at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:264)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298)
        at org.knative.examples.cloudevents.spring.CloudEventSampleApplication.main(CloudEventSampleApplication.java:26)
Caused by: java.lang.NoSuchMethodException: org.springframework.cloud.function.web.function.FunctionEndpointInitializer.<init>()
        at java.lang.Class.getConstructor0(DynamicHub.java:3082)
        at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2178)
        at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:462)
        ... 7 more
```

**Comment by dsyer** [comment]
I tried fixing this by making the condtional class present check in `FunctionEndpointInitializer` static, and adding it to `--initialize-at-build-time`. Didn't work.

**Comment by sdeleuze** [comment]
With verbose logs during the build I see in the logs:
```
WARNING: Could not register reflection metadata for org.springframework.cloud.function.web.function.FunctionEndpointInitializer. Reason: java.lang.NoClassDefFoundError: org/springframework/web/reactive/function/server/RouterFunction
```

@aclement Is there some fine tuning needed on the feature side?

**Comment by aclement** [comment]
Just to clarify that message is not from us, it is from GraalVM, but I will take a look.

**Comment by sdeleuze** [comment]
I think the error is on Spring Cloud Function side, the [classpath check](https://github.com/spring-cloud/spring-cloud-function/commit/01be2060e6556eee482aad54914258a378cd49fe#diff-e1d19021687b44761db557fd3afacc35208e272ff3a37d3d5a6d5e410151f70dR83) is done on `org.springframework.http.server.reactive.HttpHandler` which is in `spring-web` so present when Spring MVC is used. The check should probably done using `org.springframework.web.reactive.function.server.RouterFunction` if the intent is to make it work only when `spring-webflux` is in the classpath.

**Comment by dsyer** [comment]
Still not working. Re-opening.

**Comment by sdeleuze** [comment]
As analyzed by @aclement, the root issue is the `RouterFunction` lambda not it the classpath that make the reflection entry not taken in account.

We should probably wait 0.9.0 and #345 to fix it.

**Comment by sdeleuze** [comment]
@dsyer Could you please remind me how to reproduce the issue? Since we now have the build-time infrastructure we should be able to give it another try.

**Comment by dsyer** [comment]
Just switch the sample from webflux to web MVC. That should do it.

**Comment by sdeleuze** [comment]
It seems this issue is now gone with GraalVM 21.0.0 and our new build-time infrastructure.
