### ISSUE TITLE
Add spring-aspects support

### ISSUE THREAD

**Issue by itziklavon** [spring-projects-experimental/spring-native#427]
getting an error regarding spring aspect
however, i have dependency for spring aop in different module
also issue with springfox, i removed it, and this is the error i get
this is the trace:
```org.springframework.beans.factory.BeanDefinitionStoreException: org.springframework.beans.factory.aspectj.AnnotationBeanConfigurerAspect not found.
Could not configure Spring Data JPA auditing-feature because spring-aspects.jar is not on the classpath!
If you want to use auditing please add spring-aspects.jar to the classpath.
	at org.springframework.data.jpa.repository.config.JpaAuditingRegistrar.registerBeanConfigurerAspectIfNecessary(JpaAuditingRegistrar.java:125) ~[permission-runner:2.4.2]
	at org.springframework.data.jpa.repository.config.JpaAuditingRegistrar.registerBeanDefinitions(JpaAuditingRegistrar.java:88) ~[permission-runner:2.4.2]
	at org.springframework.context.annotation.ImportBeanDefinitionRegistrar.registerBeanDefinitions(ImportBeanDefinitionRegistrar.java:86) ~[permission-runner:5.3.2]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.lambda$loadBeanDefinitionsFromRegistrars$1(ConfigurationClassBeanDefinitionReader.java:396) ~[na:na]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[na:na]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromRegistrars(ConfigurationClassBeanDefinitionReader.java:395) ~[na:na]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:157) ~[na:na]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:129) ~[na:na]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:348) ~[permission-runner:5.3.2]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:252) ~[permission-runner:5.3.2]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:285) ~[na:na]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:99) ~[na:na]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:751) ~[na:na]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:569) ~[na:na]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[na:na]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) ~[permission-runner:2.4.1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[permission-runner:2.4.1]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) ~[permission-runner:2.4.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) ~[permission-runner:2.4.1]
	at com.bo.permissions.PermissionsWebApplication.main(PermissionsWebApplication.java:29) [permission-runner:na]

**Comment by sdeleuze** [comment]
Looking forward for somebody knowledgeable on spring-aspects to experiment on that one.

**Comment by sdeleuze** [comment]
Closing this one in favor of #649.

**Comment by matthenry87** [comment]
Can this one be re-opened? This still doesn't work in 0.10.1.

Here is a sample project:

[https://github.com/matthenry87/native-spring-data-auditing](https://github.com/matthenry87/native-spring-data-auditing)

```2021-06-29 03:18:29.044  WARN 1 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: org.springframework.beans.factory.aspectj.AnnotationBeanConfigurerAspect not found.
Could not configure Spring Data JPA auditing-feature because spring-aspects.jar is not on the classpath!
If you want to use auditing please add spring-aspects.jar to the classpath.
2021-06-29 03:18:29.044  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-06-29 03:18:29.045 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanDefinitionStoreException: org.springframework.beans.factory.aspectj.AnnotationBeanConfigurerAspect not found.
Could not configure Spring Data JPA auditing-feature because spring-aspects.jar is not on the classpath!
If you want to use auditing please add spring-aspects.jar to the classpath.
        at org.springframework.data.jpa.repository.config.JpaAuditingRegistrar.registerBeanConfigurerAspectIfNecessary(JpaAuditingRegistrar.java:125) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:2.5.2]
        at org.springframework.data.jpa.repository.config.JpaAuditingRegistrar.registerBeanDefinitions(JpaAuditingRegistrar.java:88) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:2.5.2]
        at org.springframework.context.annotation.ImportBeanDefinitionRegistrar.registerBeanDefinitions(ImportBeanDefinitionRegistrar.java:86) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:5.3.8]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.lambda$loadBeanDefinitionsFromRegistrars$1(ConfigurationClassBeanDefinitionReader.java:396) ~[na:na]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromRegistrars(ConfigurationClassBeanDefinitionReader.java:395) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:157) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:129) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:343) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:5.3.8]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:5.3.8]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311) ~[na:na]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) ~[na:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:2.5.2]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:2.5.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:2.5.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:2.5.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:2.5.2]
        at io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication.main(NativeSpringDataAuditingApplication.java:31) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:na]```

**Comment by sdeleuze** [comment]
@schauder is already working on this so no need for additional issue.
