### ISSUE TITLE
getting a ClassNotFoundException: sun.security.provider.ConfigFile

### ISSUE THREAD

**Issue by lemonprogis** [spring-projects-experimental/spring-native#428]
Hello spring-graalvm-native! 

First, thanks for y'alls continued work on this project. Having some trouble with a rather slim spring-boot application using webflux, spring data jdbc connecting to mssql using mssql-jdbc 8.4.1.jre11. 

I can compile the jar fine, then i copy it into a multi-stage docker build where I extract out and run native-image on it. then copy that to a final image. We connect to sql server using kerberos so was curious as to why I'm getting the following classdefnotfound: sun.security.provider.ConfigFile (what's odd to me is this seems like a java 8 path?). 

This error is on startup, not compile time. Asking here first, but if this needs to go to graalvm or mssql-jdbc just let me know. 

Thanks!

Java version: 11
spring boot version: 2.4.1
spring-graalvm-native version: 0.8.5
graalvm-ce version: 20.3.0

```bash
time native-image \
  --verbose \
  --enable-https \
  --enable-all-security-services \
  -J-Xmx4G \
  -H:Name=$ARTIFACT \
  -H:+ReportExceptionStackTraces \
  -H:+AddAllCharsets \
  -H:IncludeResourceBundles=com.microsoft.sqlserver.jdbc.SQLServerResource \
  -Dspring.spel.ignore=true \
  -Dspring.native.remove-unused-autoconfig=true \
  -Dspring.native.remove-yaml-support=true \
  -Dspring.native.verbose=true \
  -cp "$CP" $MAINCLASS;
```

Excerpt from stacktrace:

```bash
Caused by: java.lang.ExceptionInInitializerError: null
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:291) ~[na:na]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:3949) ~[na:na]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:3932) ~[na:na]
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7375) ~[na:na]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3206) ~[na:na]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2713) ~[na:na]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2362) ~[na:na]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2213) ~[na:na]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1276) ~[na:na]
        at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:861) ~[app:na]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[na:na]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358) ~[na:na]
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[na:na]
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477) ~[na:na]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560) ~[na:na]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[na:na]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[app:na]
        at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158) ~[na:na]
        at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116) ~[na:na]
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79) ~[na:na]
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:330) ~[app:5.3.2]
        at org.springframework.data.jdbc.repository.config.DialectResolver$DefaultDialectProvider.getDialect(DialectResolver.java:107) ~[app:2.1.2]
        at org.springframework.data.jdbc.repository.config.DialectResolver.lambda$getDialect$0(DialectResolver.java:77) ~[na:na]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632) ~[na:na]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127) ~[na:na]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[na:na]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[na:na]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[na:na]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543) ~[na:na]
        at org.springframework.data.jdbc.repository.config.DialectResolver.getDialect(DialectResolver.java:79) ~[na:na]
        at org.springframework.data.jdbc.repository.config.AbstractJdbcConfiguration.jdbcDialect(AbstractJdbcConfiguration.java:144) ~[app:2.1.2]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[na:na]
        ... 48 common frames omitted
Caused by: java.lang.SecurityException: Configuration error: java.lang.ClassNotFoundException: sun.security.provider.ConfigFile

        at javax.security.auth.login.Configuration.getConfiguration(Configuration.java:279) ~[na:na]
        at com.microsoft.sqlserver.jdbc.KerbAuthentication.<clinit>(KerbAuthentication.java:47) ~[na:na]
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:351) ~[na:na]
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:271) ~[na:na]
        ... 83 common frames omitted
Caused by: java.lang.ClassNotFoundException: sun.security.provider.ConfigFile
        at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60) ~[na:na]
        at java.lang.Class.forName(DynamicHub.java:1292) ~[na:na]
        at javax.security.auth.login.Configuration$2.run(Configuration.java:250) ~[na:na]
        at javax.security.auth.login.Configuration$2.run(Configuration.java:246) ~[na:na]
        at java.security.AccessController.doPrivileged(AccessController.java:120) ~[na:na]
        at javax.security.auth.login.Configuration.getConfiguration(Configuration.java:245) ~[na:na]
        ... 86 common frames omitted
```

**Comment by sdeleuze** [comment]
Hi, you have added the `--enable-all-security-services` flag so I would expect it to work. I suspect it is not Spring related, but worth to check and raise at the right place. Could you please try by adding `sun.security.provider.ConfigFile` to the reflection configuration and see if it solved? Maybe `--enable-all-security-services` does not cover this use case yet ...

**Comment by aclement** [comment]
@lemonprogis Did the steps above enable you to get further? Trying to work out if we may need to add config for that `ConfigFile` type.

**Comment by lemonprogis** [comment]
@aclement thanks! I tried it but it still seemed to not be found? Not sure if I need to add anything additional that the above.

**Comment by sdeleuze** [comment]
Please share a repro.

**Comment by sdeleuze** [comment]
Closing due to lack of feedback.
