### ISSUE TITLE
Apache LogFactory initialize at build-time issue

### ISSUE THREAD

**Issue by halimpuckjava** [spring-projects-experimental/spring-native#434]
hi

spring boot 2.4.1 (kofu 0.4.3) + graalvm 20.3.0.r11-grl 

```
Error: Classes that should be initialized at run time got initialized during image building:
 org.apache.commons.logging.LogFactory was unintentionally initialized at build time. To see why org.apache.commons.logging.LogFactory got initialized use --trace-class-initialization=org.apache.commons.logging.LogFactory
```

**Comment by sdeleuze** [comment]
Hi, please provide a repro.

**Comment by jimbethancourt** [comment]
@halimpuckjava you'll need to add a reflect-config.json file and specify all of the classes in commons-logging where java.lang.Class methods are used that are called.  

You'll also need to specify the following as build arguments passed to the native image builder:
- Specify the path to reflect-config.json file as an argument to -H:ReflectionConfugrationFiles
- Specify --initialize-at-build-time=org.apache.commons.logging.LogFactory

See https://www.graalvm.org/reference-manual/native-image/Reflection/#manual-configuration

**Comment by mmoayyed** [comment]
Just as an additional data point, this seems to also pop up with `spring-graalvm-native-plugin:1.4.2` which should be based on `0.8.5` of this extension here on top of `GraalVM 21.0.0`:


Repository:
https://github.com/apereo/cas-overlay-template/tree/graal

Test with:

```bash
./gradlew buildNativeImage 
```

Full stacktrace:


```
Error: Classes that should be initialized at run time got initialized during image building:
 org.apache.commons.logging.LogFactory was unintentionally initialized at build time. To see why org.apache.commons.logging.LogFactory got initialized use --trace-class-initialization=org.apache.commons.logging.LogFactory

com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 org.apache.commons.logging.LogFactory was unintentionally initialized at build time. To see why org.apache.commons.logging.LogFactory got initialized use --trace-class-initialization=org.apache.commons.logging.LogFactory

        at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
        at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:539)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:226)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:740)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:740)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:563)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1
```


I will look into the manual configuration option and ` reflect-config.json`, as suggested above (Thanks for the notes!)

**Comment by mmoayyed** [comment]
Quick update: using `spring-graalvm-native-plugin:1.4.2`, the following configuration produces a successful build with Gradle 6.8.1 (key setting being `initializeAtBuildTime`).


```groovy
nativeImage {
    mainClassName = "org.main.ExampleApplication"
    toolVersion = "21.0.0"
    reportExceptionStackTraces = true
    removeUnusedAutoConfig = true
    traceClassInitializationFor = ["org.apache.commons.logging.LogFactory"]
    disableToolchainChecking = true
    removeSaturatedTypeFlows = true
    printAnalysisCallTree = true
    enableAllSecurityServices = true
    removeJmxSupport = true
    enableHttp = true
    enableHttps = true
    maxHeapSize = "8G"
    download = "skip"
    javaVersion = project.targetCompatibility
    initializeAtBuildTime = ["org.apache.commons.logging.LogFactory"]
}
```

**Comment by sdeleuze** [comment]
@mmoayyed Curious about this Gradle plugin, do you have more information about it?

**Comment by mmoayyed** [comment]
Sure. Here it is:
https://github.com/ayltai/spring-graalvm-native-plugin

I did just push a PR so it can support the latest version of the spring-native here, and with the above configuration, I am able to produce a successful build via the aforementioned repo. Nonetheless, still seeing inexplicable crashes at startup. Would it be OK if I shared results here, separate issue, stackoverflow, etc?

**Comment by sdeleuze** [comment]
@mmoayyed Please create a dedicated issue.

**Comment by sdeleuze** [comment]
@mmoayyed Could you also please share here the output of running the app with `--trace-class-initialization=org.apache.commons.logging.LogFactory` ? I tried with your repro + the Gradle plugin removing `initializeAtBuildTime = ["org.apache.commons.logging.LogFactory"]` but I get `Trace class initialization requested for org.apache.commons.logging.LogFactory but the class has not been instrumented with <clinit>.` at buildtime with an unrelated error at runtime.

**Comment by mmoayyed** [comment]
@sdeleuze I modified the Gradle build as such:

```
nativeImage {
    mainClassName = "org.apereo.cas.web.CasWebApplication"
    toolVersion = "21.0.0"
    springNativeMode = "reflection"
    reportExceptionStackTraces = true
    removeUnusedAutoConfig = true
    disableToolchainChecking = true
    removeSaturatedTypeFlows = true
    printAnalysisCallTree = true
    enableAllSecurityServices = true
    removeJmxSupport = true
    enableHttp = true
    enableHttps = true
    maxHeapSize = "8G"
    download = "skip"
    javaVersion = project.targetCompatibility
    traceClassInitializationFor = ["org.apache.commons.logging.LogFactory"]
    // initializeAtBuildTime = ["org.apache.commons.logging.LogFactory"]
}
```

Here is the full output of the build:

```
> Task :buildNativeImage
[cas:26429]    classlist:   8,787.47 ms,  1.70 GB
   _____                     _                             _   __           __     _              
  / ___/    ____    _____   (_)   ____    ____ _          / | / /  ____ _  / /_   (_) _   __  ___ 
  \__ \    / __ \  / ___/  / /   / __ \  / __ `/         /  |/ /  / __ `/ / __/  / / | | / / / _ \
 ___/ /   / /_/ / / /     / /   / / / / / /_/ /         / /|  /  / /_/ / / /_   / /  | |/ / /  __/
/____/   / .___/ /_/     /_/   /_/ /_/  \__, /         /_/ |_/   \__,_/  \__/  /_/   |___/  \___/ 
        /_/                            /____/                                                     
Feature operating in REFLECTION mode
Removing unused configurations
Removing JMX support
Use -Dspring.native.verbose=true on native-image call to see more detailed information from the feature
[cas:26429]        (cap):   1,581.15 ms,  2.69 GB
feature operating mode: reflection (spring init active? false)
Found #18 types in static reflection list to register
Skipping #16 types not on the classpath
Attempting proxy registration of #12 proxies
Skipped registration of #6 proxies - relevant types not on classpath
[cas:26429]        setup:   5,762.12 ms,  2.69 GB
Configuring initialization time for specific types and packages:
#139 buildtime-init-classes   #22 buildtime-init-packages   #18 runtime-init-classes    #0 runtime-init-packages

SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
Warning: class initialization of class org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory failed with exception java.lang.NoClassDefFoundError: org/apache/catalina/WebResourceRoot. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory to explicitly request delayed initialization of this class.
Warning: class initialization of class org.apache.commons.logging.LogAdapter$Log4jLog failed with exception java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=org.apache.commons.logging.LogAdapter$Log4jLog to explicitly request delayed initialization of this class.
Jan 28, 2021 6:37:57 PM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 6.1.7.Final
Registering resources - #0 bundles
Processing META-INF/spring.factories files...
Processing spring.factories - EnableAutoConfiguration lists #97 configurations
Excluding 53 auto-configurations from spring.factories file
Processing spring.factories - EnableAutoConfiguration lists #1 configurations
Excluding 0 auto-configurations from spring.factories file
Processing spring.factories - EnableAutoConfiguration lists #5 configurations
Excluding 0 auto-configurations from spring.factories file
Processing spring.factories - EnableAutoConfiguration lists #17 configurations
Excluding 6 auto-configurations from spring.factories file
Processing spring.factories - EnableAutoConfiguration lists #130 configurations
Reducing access on org.springframework.boot.autoconfigure.web.ServerProperties$Netty because HttpServer not around
Reducing access on org.springframework.boot.autoconfigure.web.ServerProperties$Undertow because Undertow not around
Reducing access on org.springframework.boot.autoconfigure.web.ServerProperties$Tomcat because Tomcat not around
Reducing access on org.springframework.boot.autoconfigure.web.ServerProperties$Jetty because WebAppContext not around
Reducing access on org.springframework.boot.autoconfigure.web.ServerProperties$Netty because HttpServer not around
Reducing access on org.springframework.boot.autoconfigure.web.ServerProperties$Undertow because Undertow not around
Reducing access on org.springframework.boot.autoconfigure.web.ServerProperties$Tomcat because Tomcat not around
Reducing access on org.springframework.boot.autoconfigure.web.ServerProperties$Jetty because WebAppContext not around
Reducing access on org.springframework.boot.autoconfigure.web.ServerProperties$Undertow because Undertow not around
Reducing access on org.springframework.boot.autoconfigure.web.ServerProperties$Netty because HttpServer not around
Reducing access on org.springframework.boot.autoconfigure.web.ServerProperties$Tomcat because Tomcat not around
Reducing access on org.springframework.boot.autoconfigure.web.ServerProperties$Jetty because WebAppContext not around
Reducing access on org.springframework.boot.autoconfigure.web.ServerProperties$Netty because HttpServer not around
Reducing access on org.springframework.boot.autoconfigure.web.ServerProperties$Undertow because Undertow not around
Reducing access on org.springframework.boot.autoconfigure.web.ServerProperties$Tomcat because Tomcat not around
Reducing access on org.springframework.boot.autoconfigure.web.ServerProperties$Jetty because WebAppContext not around
Excluding 94 auto-configurations from spring.factories file
spring.factories processing, problem adding access for key org.springframework.boot.liquibase.LiquibaseChangelogMissingFailureAnalyzer: liquibase/exception/ChangeLogParseException
Processing spring.factories - PropertySourceLoader lists #2 property source loaders
Found no META-INF/spring.components -> synthesizing one...
Computed spring.components is 
vvv
^^^
Number of types dynamically registered for reflective access: #4066
WARNING: Could not register reflection metadata for org.springframework.boot.actuate.autoconfigure.cloudfoundry.servlet.CloudFoundryActuatorAutoConfiguration. Reason: java.lang.NoClassDefFoundError: org/springframework/security/config/annotation/web/configuration/WebSecurityCustomizer.
[cas:26429]     analysis:  21,577.94 ms,  3.13 GB
Printing call tree to /Users/Misagh/Workspace/GitWorkspace/cas-overlay-template/build/native/reports/call_tree_cas_20210128_183824.txt
Printing list of used methods to /Users/Misagh/Workspace/GitWorkspace/cas-overlay-template/build/native/reports/used_methods_cas_20210128_183826.txt
Printing list of used classes to /Users/Misagh/Workspace/GitWorkspace/cas-overlay-template/build/native/reports/used_classes_cas_20210128_183826.txt
Printing list of used packages to /Users/Misagh/Workspace/GitWorkspace/cas-overlay-template/build/native/reports/used_packages_cas_20210128_183826.txt
Error: Classes that should be initialized at run time got initialized during image building:
 org.apache.commons.logging.LogFactory was unintentionally initialized at build time. org.springframework.boot.SpringBootFactories caused initialization of this class with the following trace: 
        at org.apache.commons.logging.LogFactory.<clinit>(LogFactory.java:136)
        at org.springframework.boot.context.ConfigurationWarningsApplicationContextInitializer.<clinit>(ConfigurationWarningsApplicationContextInitializer.java:55)
        at org.springframework.boot.SpringBootFactories.<clinit>(SpringBootFactories.java:115)


com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 org.apache.commons.logging.LogFactory was unintentionally initialized at build time. org.springframework.boot.SpringBootFactories caused initialization of this class with the following trace: 
        at org.apache.commons.logging.LogFactory.<clinit>(LogFactory.java:136)
        at org.springframework.boot.context.ConfigurationWarningsApplicationContextInitializer.<clinit>(ConfigurationWarningsApplicationContextInitializer.java:55)
        at org.springframework.boot.SpringBootFactories.<clinit>(SpringBootFactories.java:115)


        at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
        at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:539)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:226)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:740)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:740)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:563)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1
```

Does this help?

## Context

I should also note that using `initializeAtBuildTime = ["org.apache.commons.logging.LogFactory"]` allows this app to build, but I cannot run the native image. Seems like it immediately crashes on startup, after displaying a Spring Boot banner (which should not actually display!). Could you recommend a way to troubleshoot the crash, before I open a separate issue?

Also note that I had to add a `reflect-config.json` file with the following content: 

```
[
    {
        "name": "org.apereo.cas.web.CasWebApplicationContext",
        "allDeclaredConstructors": true
    }
]
```

## Source 

The repo here: https://github.com/apereo/cas-overlay-template/tree/graal should be up to date with the changes that allow the app to build (and yet crash when it's actually run as a native image)

HTH. Please let me know if I can help in any other way.

**Comment by sdeleuze** [comment]
Yes it helps, `LogFactory` was indeed missing from the classes intialized at build time, and we need it since class like `ConfigurationWarningsApplicationContextInitializer`, `LoggingFailureAnalysisReporter` or `LiquibaseServiceLocatorApplicationListener` are intialized at build time themselves.

**Comment by mmoayyed** [comment]
Wonderful, thanks for the fix. I might follow-up with an issue later once 0.9 is released. Look forward to the release :)

**Comment by sendev1** [comment]
Hi @sdeleuze I hope you can help me here.  I am using spring-native:0.9.0-SNAPSHOT and I ran into this issue.

```
[project:8153]     analysis:  26,798.81 ms,  3.93 GB
Error: Classes that should be initialized at run time got initialized during image building:
 org.apache.commons.logging.LogFactory was unintentionally initialized at build time. org.springframework.context.annotation.ConfigurationClassEnhancer caused initialization of this class with the following trace:
        at org.apache.commons.logging.LogFactory.<clinit>(LogFactory.java:136)
        at org.springframework.context.annotation.ConfigurationClassEnhancer.<clinit>(ConfigurationClassEnhancer.java:87)
```



does it mean that the fix is not available in snapshot yet? or does it mean that the issue that I am facing is different that the OP issue? Thanks in advance.
