### ISSUE TITLE
build time infrastructure problem compiling StaticSpringFactories for some samples

### ISSUE THREAD

**Issue by aclement** [spring-projects-experimental/spring-native#457]
The `data-jdbc` sample is setup with the `bti-native` profile. If you try to compile it:

```mvn -Pbti-native clean package```

it will fail with a:

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/aclement/gits2/spring-graal-native/spring-native-samples/data-jdbc/target/spring-bootstrap/src/main/java/org/springframework/nativex/buildtools/StaticSpringFactories.java:[115,66] cannot find symbol
  symbol:   class DialectResolver$JdbcDialectProvider
  location: package org.springframework.data.jdbc.repository.config
```

Think it might be a dot vs dollar issue. The `data-jpa` sample has a somewhat similar problem:
```
/Users/aclement/gits2/spring-graal-native/spring-native-samples/data-jpa/target/spring-bootstrap/src/main/java/org/springframework/nativex/buildtools/StaticSpringFactories.java:[19,37] cannot find symbol
[ERROR]   symbol:   class ProxyUtils$ProxyDetector
[ERROR]   location: package org.springframework.data.util
```

**Comment by bclozel** [comment]
9f92af1de36aa02826148104e1f0ba7e815ebc58 fixed some of this problem instances. We can close this issue if it's fixed completely.

**Comment by aclement** [comment]
It gets further but now fails (for me at least):
```
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.example.data.jdbc.LegoSetRepository' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired}
```

I will investigate.

**Comment by aclement** [comment]
Ok, definitely seems to be a problem with up front code gen. If i build the sample using:
```
mvn -Pbti-native clean package
```

Then I run the packaged jar (so not the native image), it fails with: 
```
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type
    'com.example.data.jdbc.LegoSetRepository' available: expected at least 1 bean which qualifies as autowire 
    candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1790) ~[spring-beans-5.3.3.jar!/:5.3.3]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1346) ~[spring-beans-5.3.3.jar!/:5.3.3]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300) ~[spring-beans-5.3.3.jar!/:5.3.3]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-5.3.3.jar!/:5.3.3]
```

This is the same error you get if you try to run the native image that gets built. I've confirmed that using the 'bti' computed native image configuration with the feature mode of spring-native works in building a native image, which only leaves something up with the generated factories code to be the issue, but I don't quite know what from a cursory look.

**Comment by aclement** [comment]
(There is an issue with the SpringDataComponentProcessor I want to fix but as here it fails without building a native-image that doesn't seem to be the cause of this issue).
