### ISSUE TITLE
No Encoder for class with preset Content-Type 'null'

### ISSUE THREAD

**Issue by AndersClausen** [spring-projects-experimental/spring-native#461]
Hi

I'm using spring boot 2.4.2 with spring graalvm native 0.9.0-SNAPSHOT and it builds the native image just fine, however when I run it and send through a request I get the following error:

```
2021-02-01 15:30:56.306  INFO 1 --- [           main] c.m.shipment.security.AuthApplication    : Started AuthApplication in 0.101 seconds (JVM running for 0.112)
2021-02-01 15:31:53.830 ERROR 1 --- [ctor-http-nio-3] c.m.s.s.c.RestExceptionHandler           : Caught exception in handler

org.springframework.http.converter.HttpMessageNotWritableException: No Encoder for [com.maersk.shipment.security.model.AuthenticationResponse] with preset Content-Type 'null'
        at org.springframework.web.reactive.result.method.annotation.AbstractMessageWriterResultHandler.writeBody(AbstractMessageWriterResultHandler.java:167) ~[na:na]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
        |_ checkpoint ⇢ Handler com.maersk.shipment.security.controllers.AuthenticationController#login(String, ExternalAuthenticationRequest, Boolean) [DispatcherHandler]
Stack trace:
                at org.springframework.web.reactive.result.method.annotation.AbstractMessageWriterResultHandler.writeBody(AbstractMessageWriterResultHandler.java:167) ~[na:na]
                at org.springframework.web.reactive.result.method.annotation.AbstractMessageWriterResultHandler.writeBody(AbstractMessageWriterResultHandler.java:104) ~[na:na]
                at org.springframework.web.reactive.result.method.annotation.ResponseBodyResultHandler.handleResult(ResponseBodyResultHandler.java:86) ~[na:na]

```

I'm using spring-boot-starter-webflux and only have reactive code.
I don't specify the Content-Type anywhere, so what are my options here? Is this a known problem?
Thanks for your help.

**Comment by aclement** [comment]
> what are my options here?

Quickest option to get you going is to run with the agent to collect configuration you are missing: 

https://repo.spring.io/milestone/org/springframework/experimental/spring-graalvm-native-docs/0.8.5/spring-graalvm-native-docs-0.8.5.zip!/reference/index.html#_missing_configuration

Minor addendum I might edit the resource-config.json produced by that agent run to remove spring.factories entries.

Other than that, having a minimal test case would really help us resolve it properly (no agent required) much faster.

**Comment by AndersClausen** [comment]
Hi @aclement 
Thank you very much for your advice - the agent worked like a charm and the error is now gone.
I'm intrigued by your final statement - are you asking me to contribute with a test to this project or are you suggesting I use the access-filter.json as described in the link you provided above?
Cheers.

**Comment by aclement** [comment]
Using the agent is ok but it is probably leading to a bigger image that you really need as the feature is normally discarding a bunch of things the agent is including in the reflection configuration. If you are happy then all good but at some point it'd be nice to work out which reflection entries are making it work and encode those properly as hints in the feature, and throw away the other few thousand :) For that we'd probably need a test case.

**Comment by sdeleuze** [comment]
@AndersClausen Could you please provide a repro for this issue? cc @eleftherias

**Comment by AndersClausen** [comment]
@sdeleuze @eleftherias here is a link to our repo https://github.com/AndersClausen/content-type-error
Please let us know if you need anything else. Cheers

**Comment by sdeleuze** [comment]
Works correctly with `0.9.2-SNAPSHOT`.
