### ISSUE TITLE
Can't find bundles collected by the tracing agent

### ISSUE THREAD

**Issue by sendev1** [spring-projects-experimental/spring-native#467]
I am using spring boot:2.4.0 and spring_native: "0.9.0-SNAPSHOT". When I try to build native image the image build was success but I was facing this error while running image

`java.lang.IllegalArgumentException: Could not find class [springfox.documentation.spi.schema.ModelPropertyBuilderPlugin]`

swagger is user in the project for api documentation and for some reason spring-native did not capture the swagger classes. So I ran tracing agent and hit the REST end point manually from my project and collected necessary configuration files. I placed all the configuration files and when I try to get build native image I am getting this error.

```
Fatal error:java.util.MissingResourceException: Can't find bundle for base name org.apache.catalina.authenticator.LocalStrings, locale en_US
        at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:1091)
        at com.oracle.svm.util.ModuleSupport.getResourceBundle(ModuleSupport.java:46)
        at com.oracle.svm.core.jdk.LocalizationFeature.addBundleToCache(LocalizationFeature.java:267)
        at com.oracle.svm.hosted.ResourcesFeature$ResourcesRegistryImpl.addResourceBundles(ResourcesFeature.java:102)
        at com.oracle.svm.core.configure.ResourceConfigurationParser.parseEntry(ResourceConfigurationParser.java:117)
        at com.oracle.svm.core.configure.ResourceConfigurationParser.parseTopLevelObject(ResourceConfigurationParser.java:98)
        at com.oracle.svm.core.configure.ResourceConfigurationParser.parseAndRegister(ResourceConfigurationParser.java:47)
        at com.oracle.svm.hosted.config.ConfigurationParserUtils.doParseAndRegister(ConfigurationParserUtils.java:132)
        at com.oracle.svm.hosted.config.ConfigurationParserUtils.lambda$parseAndRegisterConfigurations$3(ConfigurationParserUtils.java:119)
        at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:210)
        at com.oracle.svm.hosted.config.ConfigurationParserUtils$1.tryAdvance(ConfigurationParserUtils.java:108)
        at java.util.Spliterator.forEachRemaining(Spliterator.java:326)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:272)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:313)
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.IntPipeline.reduce(IntPipeline.java:479)
        at java.util.stream.IntPipeline.sum(IntPipeline.java:437)
        at com.oracle.svm.hosted.config.ConfigurationParserUtils.parseAndRegisterConfigurations(ConfigurationParserUtils.java:125)
        at com.oracle.svm.hosted.ResourcesFeature.beforeAnalysis(ResourcesFeature.java:115)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$7(NativeImageGenerator.java:701)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:701)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:563)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
        at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1676)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1426)
        at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1387)
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1374)
```

Here is the part of bundle entry from resource-config.json produced by tracing agent.
```
"bundles":[
    {"name":"javax.servlet.LocalStrings"}, 
    {"name":"javax.servlet.http.LocalStrings"}, 
    {"name":"org.apache.catalina.authenticator.LocalStrings"}, 
    {"name":"org.apache.catalina.authenticator.jaspic.LocalStrings"}, 
    {"name":"org.apache.catalina.connector.LocalStrings"}, 
    {"name":"org.apache.catalina.core.LocalStrings"}, 
    {"name":"org.apache.catalina.deploy.LocalStrings"}, 
    {"name":"org.apache.catalina.loader.LocalStrings"}, 
    {"name":"org.apache.catalina.mapper.LocalStrings"}, 
    {"name":"org.apache.catalina.mbeans.LocalStrings"}, 
    {"name":"org.apache.catalina.realm.LocalStrings"}, 
    {"name":"org.apache.catalina.security.LocalStrings"}, 
    {"name":"org.apache.catalina.session.LocalStrings"}, 
    {"name":"org.apache.catalina.startup.LocalStrings"}, 
    {"name":"org.apache.catalina.util.LocalStrings"}, 
    {"name":"org.apache.catalina.valves.LocalStrings"}, 
    {"name":"org.apache.catalina.webresources.LocalStrings"}, 
    {"name":"org.apache.coyote.LocalStrings"}, 
    {"name":"org.apache.coyote.http11.LocalStrings"}, 
    {"name":"org.apache.coyote.http11.filters.LocalStrings"}, 
    {"name":"org.apache.cxf.Messages"}, 
    {"name":"org.apache.cxf.binding.soap.interceptor.Messages"}, 
    {"name":"org.apache.cxf.binding.soap.saaj.Messages"}, 
    {"name":"org.apache.cxf.bus.extension.Messages"}, 
    {"name":"org.apache.cxf.bus.managers.Messages"}, 
    {"name":"org.apache.cxf.bus.spring.Messages"}, 
    {"name":"org.apache.cxf.clustering.Messages"}, 
    {"name":"org.apache.cxf.common.annotation.Messages"}, 
    {"name":"org.apache.cxf.common.injection.Messages"}, 
    {"name":"org.apache.cxf.common.jaxb.Messages"}, 
.
.
.
```
When I removed `org.apache.catalina.authenticator.LocalStrings` and ran native image build and I got error for the next bundle `org.apache.catalina.authenticator.jaspic.LocalStrings`. I removed that one also and ran build this time I got error for the next one in the order. so I removed all catalina bundle and ran build and I got `Fatal error:java.util.MissingResourceException: Can't find bundle for base name org.apache.coyote.LocalStrings, locale en_US` . Before I want to contine to remove the bundles  I wanted to check with spring-native team on this. Why spring-native is not able to find the bundles that were created by tracing agent? Thank you

**Comment by sdeleuze** [comment]
I am not sure, could you please try again with `0.9.1` and provide a repro if the issue still happen?

**Comment by sdeleuze** [comment]
Closing this issue due to lack of feedback.
