### ISSUE TITLE
Spring Boot DevTools - runtime error due to DevToolsDataSourceAutoConfiguration.class file not found

### ISSUE THREAD

**Issue by leccelecce** [spring-projects-experimental/spring-native#528]
[repro-sn528.zip](https://github.com/spring-projects-experimental/spring-native/files/6050633/repro-sn528.zip)
0.9.0-SNAPSHOT on Windows 10

See attached repro project - builds correctly but throws the below exception at runtime.

I have tried with/without the `<optional>true</optional>` flag in the POM.

Also noted that there are a lot of DevTools related warnings in spring-aot:generate - example:

```
[INFO]     [creator]     WARNING: Could not resolve org.springframework.boot.devtools.autoconfigure.DevToolsDataSourceAutoConfiguration for reflection configuration. Reason: java.lang.ClassNotFoundException: org.springframework.boot.devtools.autoconfigure.DevToolsDataSourceAutoConfiguration.
```

```
java.lang.IllegalStateException: Unable to read meta-data for class org.springframework.boot.devtools.autoconfigure.DevToolsDataSourceAutoConfiguration
        at org.springframework.boot.autoconfigure.AutoConfigurationSorter$AutoConfigurationClass.getAnnotationMetadata(AutoConfigurationSorter.java:237) ~[na:na]
        at org.springframework.boot.autoconfigure.AutoConfigurationSorter$AutoConfigurationClass.getOrder(AutoConfigurationSorter.java:208) ~[na:na]
        at org.springframework.boot.autoconfigure.AutoConfigurationSorter$AutoConfigurationClass.access$000(AutoConfigurationSorter.java:154) ~[na:na]
        at org.springframework.boot.autoconfigure.AutoConfigurationSorter.lambda$getInPriorityOrder$0(AutoConfigurationSorter.java:63) ~[na:na]
        at java.util.TimSort.binarySort(TimSort.java:296) ~[na:na]
        at java.util.TimSort.sort(TimSort.java:239) ~[na:na]
        at java.util.Arrays.sort(Arrays.java:1515) ~[na:na]
        at java.util.ArrayList.sort(ArrayList.java:1750) ~[com.ecv.webapp.Application:na]
        at org.springframework.boot.autoconfigure.AutoConfigurationSorter.getInPriorityOrder(AutoConfigurationSorter.java:62) ~[na:na]
        at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector$AutoConfigurationGroup.sortAutoConfigurations(AutoConfigurationImportSelector.java:468) ~[com.ecv.webapp.Application:2.4.3]
        at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector$AutoConfigurationGroup.selectImports(AutoConfigurationImportSelector.java:453) ~[com.ecv.webapp.Application:2.4.3]
        at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGrouping.getImports(ConfigurationClassParser.java:882) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.processGroupImports(ConfigurationClassParser.java:809) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorHandler.process(ConfigurationClassParser.java:780) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:193) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:330) ~[com.ecv.webapp.Application:5.3.4]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:246) ~[com.ecv.webapp.Application:5.3.4]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311) ~[na:na]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:745) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:563) ~[na:na]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[na:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) ~[com.ecv.webapp.Application:2.4.3]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[com.ecv.webapp.Application:2.4.3]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) ~[com.ecv.webapp.Application:2.4.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) ~[com.ecv.webapp.Application:2.4.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311) ~[com.ecv.webapp.Application:2.4.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) ~[com.ecv.webapp.Application:2.4.3]
        at com.ecv.webapp.Application.main(Application.java:41) ~[com.ecv.webapp.Application:na]
Caused by: java.io.FileNotFoundException: class path resource [org/springframework/boot/devtools/autoconfigure/DevToolsDataSourceAutoConfiguration.class] cannot be opened because it does not exist
        at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:180) ~[na:na]
        at org.springframework.core.type.classreading.SimpleMetadataReader.getClassReader(SimpleMetadataReader.java:55) ~[na:na]
        at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:49) ~[na:na]        at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103) ~[na:na]
        at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.createMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:86) ~[na:na]
        at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.getMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:73) ~[na:na]
        at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:81) ~[na:na]
        at org.springframework.boot.autoconfigure.AutoConfigurationSorter$AutoConfigurationClass.getAnnotationMetadata(AutoConfigurationSorter.java:233) ~[na:na]
        ... 28 common frames omitted
```

**Comment by sdeleuze** [comment]
We should clarify devtools status and maybe put some early check if we don't support it.

**Comment by aclement** [comment]
Just a bit of debug info, if I `mvn spring-boot:build-image` on that, it won't work, as described. However, if I add the necessary native-image step to the sample pom to build locally rather than in a container then it starts and runs fine (I can curl it)

**Comment by sdeleuze** [comment]
Devtools support raises multiple challenges, for example there are more failures with `runtime` scope with the AOT plugin. I have added a fail fast check in Spring AOT for 0.9.0, we will add proper support in 0.9.1 via #532.
