### ISSUE TITLE
Strange behavior with Spring AOP

### ISSUE THREAD

**Issue by khaeghar** [spring-projects-experimental/spring-native#579]
Hi,

I've been trying to compile and run an application with aspects, using Spring AOP.

First thing I notice is that, if I don't run the agent with the JAR, the following problem arise:

```
Caused by: org.aspectj.weaver.BCException: AspectJ internal error

        at org.aspectj.weaver.reflect.ReflectionWorld.makeAnnotationFinderIfAny(ReflectionWorld.java:132) ~[na:na]
        at org.aspectj.weaver.reflect.ReflectionWorld.<init>(ReflectionWorld.java:97) ~[na:na]
        at org.aspectj.weaver.reflect.ReflectionWorld.getReflectionWorldFor(ReflectionWorld.java:51) ~[na:na]
        at org.aspectj.weaver.tools.PointcutParser.setClassLoader(PointcutParser.java:222) ~[na:na]
        at org.aspectj.weaver.tools.PointcutParser.<init>(PointcutParser.java:208) ~[na:na]
        at org.aspectj.weaver.tools.PointcutParser.getPointcutParserSupportingSpecifiedPrimitivesAndUsingSpecifiedClassLoaderForResolution(PointcutParser.java:170) ~[na:na]
        at org.springframework.aop.aspectj.AspectJExpressionPointcut.initializePointcutParser(AspectJExpressionPointcut.java:242) ~[na:na]
        at org.springframework.aop.aspectj.AspectJExpressionPointcut.buildPointcutExpression(AspectJExpressionPointcut.java:221) ~[na:na]
        at org.springframework.aop.aspectj.AspectJExpressionPointcut.obtainPointcutExpression(AspectJExpressionPointcut.java:198) ~[na:na]
        at org.springframework.aop.aspectj.AspectJExpressionPointcut.getClassFilter(AspectJExpressionPointcut.java:177) ~[na:na]
        at org.springframework.aop.support.AopUtils.canApply(AopUtils.java:226) ~[na:na]
        at org.springframework.aop.support.AopUtils.canApply(AopUtils.java:289) ~[na:na]
        at org.springframework.aop.support.AopUtils.findAdvisorsThatCanApply(AopUtils.java:321) ~[na:na]
        at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findAdvisorsThatCanApply(AbstractAdvisorAutoProxyCreator.java:128) ~[com.fon.footballfantasy.FootballFantasyApplication:5.3.1]
        at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findEligibleAdvisors(AbstractAdvisorAutoProxyCreator.java:97) ~[com.fon.footballfantasy.FootballFantasyApplication:5.3.1]
        at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.getAdvicesAndAdvisorsForBean(AbstractAdvisorAutoProxyCreator.java:78) ~[com.fon.footballfantasy.FootballFantasyApplication:5.3.1]
        at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:337) ~[com.fon.footballfantasy.FootballFantasyApplication:5.3.1]
        at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:289) ~[com.fon.footballfantasy.FootballFantasyApplication:5.3.1]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:444) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:609) ~[na:na]
        ... 37 common frames omitted
```

Then I executed the agent, creating the config files for the application, with the jar. And it compiles and launches the app, but then, this strange behavior happens:

It returns a 404 for the endpoint call. It seems the logic inside gets executed, but the aspect doesn't and the HTTP Response doesn't makes sense, since it clearly finds the endpoint.

```
2021-03-10 00:57:22.468 DEBUG 92675 --- [nio-8080-exec-1] org.apache.tomcat.util.http.Parameters   : Set encoding to UTF-8
2021-03-10 00:57:22.468 DEBUG 92675 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : GET "/demo", parameters={}
2021-03-10 00:57:22.468 DEBUG 92675 --- [nio-8080-exec-1] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped to ResourceHttpRequestHandler [class path resource [META-INF/resources/], class path resource [resources/], class path resource [static/], class path resource [public/], ServletContext resource [/]]
2021-03-10 00:57:22.468 DEBUG 92675 --- [nio-8080-exec-1] o.s.w.s.r.ResourceHttpRequestHandler     : Resource not found
2021-03-10 00:57:22.469 DEBUG 92675 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed 404 NOT_FOUND
2021-03-10 00:57:22.469 DEBUG 92675 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost]           : Processing ErrorPage[errorCode=0, location=/error]
2021-03-10 00:57:22.469 DEBUG 92675 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : "ERROR" dispatch for GET "/error", parameters={}
2021-03-10 00:57:22.469 DEBUG 92675 --- [nio-8080-exec-1] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController#errorHtml(HttpServletRequest, HttpServletResponse)
2021-03-10 00:57:22.469 DEBUG 92675 --- [nio-8080-exec-1] o.a.c.loader.WebappClassLoaderBase       : getResource(META-INF/resources/error/404.html)
2021-03-10 00:57:22.469 DEBUG 92675 --- [nio-8080-exec-1] o.a.c.loader.WebappClassLoaderBase       :   Delegating to parent classloader jdk.internal.loader.ClassLoaders$AppClassLoader@21a06946
2021-03-10 00:57:22.469 DEBUG 92675 --- [nio-8080-exec-1] o.a.c.loader.WebappClassLoaderBase       :   --> Resource not found, returning null
2021-03-10 00:57:22.469 DEBUG 92675 --- [nio-8080-exec-1] o.a.c.loader.WebappClassLoaderBase       : getResource(resources/error/404.html)
2021-03-10 00:57:22.469 DEBUG 92675 --- [nio-8080-exec-1] o.a.c.loader.WebappClassLoaderBase       :   Delegating to parent classloader jdk.internal.loader.ClassLoaders$AppClassLoader@21a06946
2021-03-10 00:57:22.470 DEBUG 92675 --- [nio-8080-exec-1] o.a.c.loader.WebappClassLoaderBase       :   --> Resource not found, returning null
2021-03-10 00:57:22.470 DEBUG 92675 --- [nio-8080-exec-1] o.a.c.loader.WebappClassLoaderBase       : getResource(static/error/404.html)
2021-03-10 00:57:22.470 DEBUG 92675 --- [nio-8080-exec-1] o.a.c.loader.WebappClassLoaderBase       :   Delegating to parent classloader jdk.internal.loader.ClassLoaders$AppClassLoader@21a06946
2021-03-10 00:57:22.470 DEBUG 92675 --- [nio-8080-exec-1] o.a.c.loader.WebappClassLoaderBase       :   --> Resource not found, returning null
2021-03-10 00:57:22.470 DEBUG 92675 --- [nio-8080-exec-1] o.a.c.loader.WebappClassLoaderBase       : getResource(public/error/404.html)
2021-03-10 00:57:22.470 DEBUG 92675 --- [nio-8080-exec-1] o.a.c.loader.WebappClassLoaderBase       :   Delegating to parent classloader jdk.internal.loader.ClassLoaders$AppClassLoader@21a06946
2021-03-10 00:57:22.470 DEBUG 92675 --- [nio-8080-exec-1] o.a.c.loader.WebappClassLoaderBase       :   --> Resource not found, returning null
2021-03-10 00:57:22.470 DEBUG 92675 --- [nio-8080-exec-1] o.a.c.loader.WebappClassLoaderBase       : getResource(META-INF/resources/error/4xx.html)
2021-03-10 00:57:22.470 DEBUG 92675 --- [nio-8080-exec-1] o.a.c.loader.WebappClassLoaderBase       :   Delegating to parent classloader jdk.internal.loader.ClassLoaders$AppClassLoader@21a06946
2021-03-10 00:57:22.470 DEBUG 92675 --- [nio-8080-exec-1] o.a.c.loader.WebappClassLoaderBase       :   --> Resource not found, returning null
2021-03-10 00:57:22.470 DEBUG 92675 --- [nio-8080-exec-1] o.a.c.loader.WebappClassLoaderBase       : getResource(resources/error/4xx.html)
2021-03-10 00:57:22.470 DEBUG 92675 --- [nio-8080-exec-1] o.a.c.loader.WebappClassLoaderBase       :   Delegating to parent classloader jdk.internal.loader.ClassLoaders$AppClassLoader@21a06946
2021-03-10 00:57:22.470 DEBUG 92675 --- [nio-8080-exec-1] o.a.c.loader.WebappClassLoaderBase       :   --> Resource not found, returning null
2021-03-10 00:57:22.470 DEBUG 92675 --- [nio-8080-exec-1] o.a.c.loader.WebappClassLoaderBase       : getResource(static/error/4xx.html)
2021-03-10 00:57:22.470 DEBUG 92675 --- [nio-8080-exec-1] o.a.c.loader.WebappClassLoaderBase       :   Delegating to parent classloader jdk.internal.loader.ClassLoaders$AppClassLoader@21a06946
2021-03-10 00:57:22.470 DEBUG 92675 --- [nio-8080-exec-1] o.a.c.loader.WebappClassLoaderBase       :   --> Resource not found, returning null
2021-03-10 00:57:22.471 DEBUG 92675 --- [nio-8080-exec-1] o.a.c.loader.WebappClassLoaderBase       : getResource(public/error/4xx.html)
2021-03-10 00:57:22.471 DEBUG 92675 --- [nio-8080-exec-1] o.a.c.loader.WebappClassLoaderBase       :   Delegating to parent classloader jdk.internal.loader.ClassLoaders$AppClassLoader@21a06946
2021-03-10 00:57:22.471 DEBUG 92675 --- [nio-8080-exec-1] o.a.c.loader.WebappClassLoaderBase       :   --> Resource not found, returning null
2021-03-10 00:57:22.471 DEBUG 92675 --- [nio-8080-exec-1] o.s.w.s.v.ContentNegotiatingViewResolver : Selected 'text/html' given [text/html, text/html;q=0.8]
2021-03-10 00:57:22.471 DEBUG 92675 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Exiting from "ERROR" dispatch, status 404
```

It's like it throws the 404 because it doesn't find something else inside the app, not because it can't find the endpoint. And the aspect doesn't log anything.

Java version is 1.8, with GraalVM 21.0.0 and Spring GraalVM Native 0.8.5.

I've created a reproducer:

[AOPTest.zip](https://github.com/spring-projects-experimental/spring-native/files/6115325/AOPTest.zip)

First I did a mvn install, then executed the script to compile. It has the config files added, so both cases can be checked.

I know Spring AOP doesn't appears in the supported libraries for Spring GraalVM Native, but just in case there's intentions of adding it.

**Comment by aclement** [comment]
I was initially confused because you mention 0.8.5 but the sample app is using 0.9.0 but it is missing the AOT configuration steps. So I made the test sample fully 0.9.0 capable. It still doesn't work, some missing config. Then I used the agent, similarly to you, that got to a different error with a missing proxy which surprised me (because shouldn't the agent have picked that up). Fixing the proxy leaves me with an app that builds and starts but the advised endpoint can't be reached (I added a second controller not affected by the aspect and that endpoint is fine).

My initial reaction is that it is related the proxy generation shortcuts we take not being right and not giving us enough debug information to know what it did. The need for me to add a proxy that the agent didn't pick up also backs this up in my mind. Let me try using the extra code from the batch issue to debug it further.

**Comment by aclement** [comment]
Yes, it is that. Here is a technique that worked on my sample. I extracted an interface from the controller and included the annotations on the interface, a bit like:
```
@RestController
public interface Foo {
  @GetMapping(value="/demo")
  String demo();
}
```
and then implemented that by the controller. This enabled JDK proxies to be used properly - and I found Spring AOP worked (in a native image):
  ```
  
2021-03-10 21:56:40.615  INFO 33652 --- [           main] c.e.graalvmdemo.GraalvmDemoApplication   : Started GraalvmDemoApplication in 0.096 seconds (JVM running for 0.098)
2021-03-10 21:56:43.588  INFO 33652 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2021-03-10 21:56:43.588  INFO 33652 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2021-03-10 21:56:43.589  INFO 33652 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
2021-03-10 21:56:43.589  INFO 33652 --- [nio-8080-exec-1] c.e.graalvmdemo.aspect.LoggableAspect    : I'm working!
```

Obviously not an ideal 'fix' in that form, but a workaround to use in the interim perhaps.

**Comment by khaeghar** [comment]
It worked. Thank you very much and apologies for the misconfigured project.
