### ISSUE TITLE
Add a Maven and Gradle multiple module samples

### ISSUE THREAD

**Issue by itzikiusa** [spring-projects-experimental/spring-native#611]
Hi, question
currently i have 2 different modules
1 which contains the basic dependencies(spring web/webflux, cloud config, AOP and more)
and the other will have DB dependency(jpa/mongo/elasticsearch)

does it suppose to work in this kind of structure? how the dependencies know how to work with dependant modules? do i need to add something to my pom?
i'm trying to create native image but i'm getting an error 
```
org.springframework.context.ApplicationContextException: Unable to start reactive web server; nested exception is org.springframework.context.ApplicationContextException: Unable to start ReactiveWebApplicationContext due to missing ReactiveWebServerFactory bean.
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.onRefresh(ReactiveWebServerApplicationContext.java:81) ~[na:na]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:576) ~[na:na]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:63) ~[na:na]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) [com.example.tst.MainApplication:na]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [com.example.tst.MainApplication:na]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) [com.example.tst.MainApplication:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) [com.example.tst.MainApplication:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311) [com.example.tst.MainApplication:na]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) [com.example.tst.MainApplication:na]
	at com.example.tst.MainApplication.main(MainApplication.java:16) [com.example.tst.MainApplication:na]
Caused by: org.springframework.context.ApplicationContextException: Unable to start ReactiveWebApplicationContext due to missing ReactiveWebServerFactory bean.
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.getWebServerFactoryBeanName(ReactiveWebServerApplicationContext.java:107) ~[na:na]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.createWebServer(ReactiveWebServerApplicationContext.java:89) ~[na:na]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.onRefresh(ReactiveWebServerApplicationContext.java:78) ~[na:na]`

**Comment by sdeleuze** [comment]
I think we should add a multi module sample. Please notice than AOP is not supported so please use only [what is supported](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#support) for now.

**Comment by itzikiusa** [comment]
@bclozel 
can we extend the example?
add some dependencies/classes to the core module, and app module should have them
also, in my test, the web dependency was in the core module, not app(as most of spring dependencies and beans)
app module only had the web application it self
