### ISSUE TITLE
Could not find class [org.springframework.http.HttpStatus]

### ISSUE THREAD

**Issue by ivangfr** [spring-projects-experimental/spring-native#612]
Hi, I've updated my project `springboot-elasticsearch` to `spring-native` version `0.9.0`.

I am able to build successfully the Docker native image. However, I am having the following exception at runtime.

> **Note**: It was working with the previous version `0.8.5`.

```
ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.mycompany.  springbootelasticsearch.SpringbootElasticsearchApplication]; nested exception is java.lang.IllegalArgumentException:   Could not find class [org.springframework.http.HttpStatus]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:189) ~  [na:na]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions  (ConfigurationClassPostProcessor.java:330) ~[com.mycompany.springbootelasticsearch.  SpringbootElasticsearchApplication:5.3.4]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry  (ConfigurationClassPostProcessor.java:246) ~[com.mycompany.springbootelasticsearch.  SpringbootElasticsearchApplication:5.3.4]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors  (PostProcessorRegistrationDelegate.java:311) ~[na:na]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors  (PostProcessorRegistrationDelegate.java:112) ~[na:na]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors  (AbstractApplicationContext.java:745) ~[na:na]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:563) ~  [na:na]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh  (ReactiveWebServerApplicationContext.java:63) ~[na:na]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) ~[com.mycompany.  springbootelasticsearch.SpringbootElasticsearchApplication:2.4.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[com.mycompany.  springbootelasticsearch.SpringbootElasticsearchApplication:2.4.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) ~[com.mycompany.  springbootelasticsearch.SpringbootElasticsearchApplication:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) ~[com.mycompany.  springbootelasticsearch.SpringbootElasticsearchApplication:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311) ~[com.mycompany.  springbootelasticsearch.SpringbootElasticsearchApplication:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) ~[com.mycompany.  springbootelasticsearch.SpringbootElasticsearchApplication:2.4.3]
	at com.mycompany.springbootelasticsearch.SpringbootElasticsearchApplication.main  (SpringbootElasticsearchApplication.java:10) ~[com.mycompany.springbootelasticsearch.  SpringbootElasticsearchApplication:na]
Caused by: java.lang.IllegalArgumentException: Could not find class [org.springframework.http.HttpStatus]
	at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:334) ~[na:na]
	at org.springframework.core.type.classreading.MergedAnnotationReadingVisitor.visitEnum  (MergedAnnotationReadingVisitor.java:104) ~[na:na]
	at org.springframework.core.type.classreading.MergedAnnotationReadingVisitor.visitEnum  (MergedAnnotationReadingVisitor.java:80) ~[na:na]
	at org.springframework.asm.ClassReader.readElementValue(ClassReader.java:3056) ~[na:na]
	at org.springframework.asm.ClassReader.readElementValues(ClassReader.java:2975) ~[na:na]
	at org.springframework.asm.ClassReader.readMethod(ClassReader.java:1390) ~[na:na]
	at org.springframework.asm.ClassReader.accept(ClassReader.java:721) ~[na:na]
	at org.springframework.asm.ClassReader.accept(ClassReader.java:401) ~[na:na]
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:49) ~[na:na]
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader  (SimpleMetadataReaderFactory.java:103) ~[na:na]
	at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader  (CachingMetadataReaderFactory.java:123) ~[na:na]
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader  (SimpleMetadataReaderFactory.java:81) ~[na:na]
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.  addCandidateComponentsFromIndex(ClassPathScanningCandidateComponentProvider.java:386) ~[na:na]
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents  (ClassPathScanningCandidateComponentProvider.java:312) ~[na:na]
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.  java:276) ~[na:na]
	at org.springframework.context.annotation.ComponentScanAnnotationParser.parse(ComponentScanAnnotationParser.  java:132) ~[na:na]
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass  (ConfigurationClassParser.java:296) ~[na:na]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass  (ConfigurationClassParser.java:250) ~[na:na]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:207) ~  [na:na]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:175) ~  [na:na]
	... 14 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.http.HttpStatus
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60) ~[na:na]
	at java.lang.Class.forName(DynamicHub.java:1260) ~[na:na]
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:284) ~[na:na]
	at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:324) ~[na:na]
	... 33 common frames omitted
```

Btw, in my controller, I am using `@ResponseStatus(HttpStatus.CREATED)`

```
...
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ResponseStatus;
...

@RestController
@RequestMapping("/api/movies")
public class MoviesController {

	...

    @ResponseStatus(HttpStatus.CREATED)
    @PostMapping
    public String createMovie(@Valid @RequestBody CreateMovieRequest createMovieRequest) {
        Movie movie = movieMapper.toMovie(createMovieRequest);
        return movieService.saveMovie(movie);
    }

    ...
}
```

If I comment `@ResponseStatus(HttpStatus.CREATED)` and the imports of `HttpStatus` and `ResponseStatus`, the app works.

**How to reproduce**

- git clone https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot.git
- cd graalvm-quarkus-micronaut-springboot
- git checkout update-frameworks-version
- cd elasticsearch
- docker-compose up -d
- cd springboot-elasticsearch
- ./mvnw -Pnative spring-boot:build-image
- docker run --rm --name springboot-elasticsearch-native -p 9117:8080 -e ELASTICSEARCH_HOST=elasticsearch --network elasticsearch_default docker.mycompany.com/springboot-elasticsearch-native:1.0.0

**Comment by gtiwari333** [comment]
I was getting the similar ClassNotFoundException and was able to resolve them by using `@TypeHint`
See this PR https://github.com/gtiwari333/spring-boot-blog-app/pull/1/files#diff-dc412f91e6d0abb7cce61ef3e6c3d1cda9a90214d50d606d20573de8b79d716cR31

**Comment by sdeleuze** [comment]
Good catch, indeed we need to refine `HttpStatus` hints.

**Comment by ivangfr** [comment]
Thanks @gtiwari333, it worked. I just added
```
@TypeHints({
	@TypeHint(types = HttpStatus.class)
})
```
to my `@SpringBootApplication` class.
