### ISSUE TITLE
AOT plugin picks up dependencies from Gradle buildSrc

### ISSUE THREAD

**Issue by celcius112** [spring-projects-experimental/spring-native#627]
I have a weird issue in a business project in which I am testing version 0.9.0. This project uses Gradle.

When launching the `bootBuildImage` I end up with a
```
    [creator]     Fatal error:java.lang.TypeNotPresentException: Type org.h2.server.web.WebServlet not present
    [creator]           at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
    [creator]           at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
    [creator]           at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
    [creator]           at java.base/sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
    [creator]           at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
    [creator]           at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
    [creator]           at java.base/sun.reflect.generics.repository.MethodRepository.computeReturnType(MethodRepository.java:75)
    [creator]           at java.base/sun.reflect.generics.repository.MethodRepository.getReturnType(MethodRepository.java:66)
    [creator]           at java.base/java.lang.reflect.Method.getGenericReturnType(Method.java:292)
    [creator]           at com.oracle.svm.reflect.hosted.ReflectionMetadataFeature.replacer(ReflectionMetadataFeature.java:65)
    [creator]           at com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:565)
    [creator]           at com.oracle.graal.pointsto.ObjectScanner.scanArray(ObjectScanner.java:236)
    [creator]           at com.oracle.graal.pointsto.ObjectScanner.doScan(ObjectScanner.java:351)
    [creator]           at com.oracle.graal.pointsto.ObjectScanner.access$400(ObjectScanner.java:60)
    [creator]           at com.oracle.graal.pointsto.ObjectScanner$2$1.run(ObjectScanner.java:388)
    [creator]           at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
...
    [creator]     Caused by: java.lang.ClassNotFoundException: org.h2.server.web.WebServlet
    [creator]           at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
    [creator]           at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
    [creator]           at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    [creator]           at java.base/java.lang.Class.forName0(Native Method)
    [creator]           at java.base/java.lang.Class.forName(Class.java:398)
    [creator]           at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
    [creator]           ... 21 more
```
After going into the `reflect-config.json` created by the AOT plugin, there are indeed declarations of H2 types:
```json
{
    "name": "org.h2.mvstore.db.MVTableEngine",
    "allDeclaredFields": true,
    "allDeclaredConstructors": true,
    "allDeclaredMethods": true
  },
  {
    "name": "org.h2.server.web.WebServlet"
  },
...
```
However after careful analysis of the transitive dependencies and classpath I cannot find any reference to H2 nor spring-data or database-connected dependencies. Also, launching the application in JVM mode does not trigger H2 auto-configuration .(`H2ConsoleAutoConfiguration`).

Adding the H2 dependency will of course resolve the issue here.

**Comment by celcius112** [comment]
To list all dependencies I use the `./gradlew -q dependencies` command. I could provide the output if necessary but it is a bit indigest to read.

**Comment by sdeleuze** [comment]
Could you please share the project (attached zip or as a repository) to allow us to analyze it?

**Comment by celcius112** [comment]
Sorry, I'm trying to divide and conquer the dependencies to pinpoint where the problems is coming from. I will provide a sample then. My guess at the moment is it is coming from spring-cloud-config-server.

**Comment by celcius112** [comment]
After some more research it is not spring-cloud, but instead a custom Gradle plugin. Probably one of its dependency is leaking into the aot-plugin. I'm trying to find which one

**Comment by celcius112** [comment]
Ok found it. So in one of our plugin we are importing `org.owasp:dependency-check-gradle` which seems to be importing H2. Since the Gradle plugins are only used for the build the H2 dependency does not appear in the classpath, hence H2 auto-configuration being filtered out in JVM mode. However the aot-plugin seems to be retrieving this dependency, and as such add uneeded json configuration in reflect-config.json.

I have created this small project to reproduce this error. I have added the dependency-check dependency in a `buildSrc` directory which has similar behavior than when using a plugin:
[h2-leak.zip](https://github.com/spring-projects-experimental/spring-native/files/6158542/h2-leak.zip)

To reproduce, a `./gradlew clean compileAotJava` should add H2 json configuration. Removing the dependency-check dependency and relaunching the Gradle command will not produce the H2 json configuration.

**Comment by celcius112** [comment]
Hello @bclozel @sdeleuze, upgrading to the newest version (0.9.1) does not seem to resolve the issue. Using the small project I provided I still see `org.h2.server.web.WebServlet` and cie being added to the `reflect-config.json`

**Comment by bclozel** [comment]
I've found the initial fix for this issue was incomplete.
I've tracked down the remaining part of the problem in `org.springframework.nativex.type.TypeSystem`; this implementation resolves classes from the classpath entries given as a constructor argument, but also from `Thread.currentThread().getContextClassLoader()` for System classes. We're basically hitting the same problem that we fixed already but in the parallel `TypeSystem` implementation.

I've tried to fix this problem by using instead the classloader used by `org.springframework.core.type.classreading.TypeSystem`, which is based on the list of classpath entries and the base classloader. But this solution fails since the related part of the AOT process is resolving `LoggingInitHints` (part of the `spring-native-configuration` dependency).

I'll discuss that point with @sdeleuze to decide on the best course of action here.

**Comment by bclozel** [comment]
I've solved this issue locally, but I think we're back to a problem we already considered: whether `spring-native-configuration` is a required dependency and where it should be declared.

Currently, the `spring-native` artifact does not depend on `spring-native-configuration`. `spring-native-configuration` is currently a required dependency for the AOT processing, since `@NativeHint` declarations are available in that module and `spring-aot` is looking for specific classes on the classpath of the application being processed.

Fixing this issue is really about isolating the build plugin (Maven or Gradle) from the application classpath we're using for the AOT analysis.

So how come this is working now? The `TypeSystem` is using the `Thread.currentThread().getContextClassLoader()` as a fallback classloader for loading JDK classes - this is wrong as this `ClassLoader` will also contain build plugin dependencies. This is how we're detecting classes that are not on the application classpath.

So far the only solution I can think of are:
1. adding the `spring-native-configuration` dependency to applications (we can do that via the build plugins or ask developers to do so)
2. adding `spring-native-configuration` as a dependency to `spring-native`

**Comment by bclozel** [comment]
@sdeleuze and I discussed this and we think that this issue is strictly related to #488. We can't really fix this problem properly without addressing the broader design. We identified those limitations a while ago, but this is an unintended consequence.

I'm moving this issue to the same milestone as the other issues in that area.
