### ISSUE TITLE
Jolokia actuator endpoint cannot be processed 

### ISSUE THREAD

**Issue by celcius112** [spring-projects-experimental/spring-native#628]
With `spring-boot-starter-actuator` and `jolokia-core` present in the classpath an actuator endpoint is auto-configured for jolokia.

Using spring-native and these dependencies, there is a failure at runtime that does not appear in JVM mode:
```
Caused by: java.lang.IllegalStateException: Error processing condition on org.springframework.boot.actuate.autoconfigure.jolokia.JolokiaEndpointAutoConfiguration
        at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:60) ~[com.example.demo.DemoApplication:2.4.3]
        at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:226) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:600) ~[na:na]
        ... 20 common frames omitted
Caused by: java.lang.IllegalArgumentException: Value must not be empty
        at org.springframework.util.Assert.hasText(Assert.java:289) ~[na:na]
        at org.springframework.boot.actuate.endpoint.EndpointId.<init>(EndpointId.java:57) ~[na:na]
        at org.springframework.boot.actuate.endpoint.EndpointId.of(EndpointId.java:129) ~[na:na]
        at org.springframework.boot.actuate.autoconfigure.endpoint.condition.AbstractEndpointCondition.getEnablementOutcome(AbstractEndpointCondition.java:65) ~[na:na]
        at org.springframework.boot.actuate.autoconfigure.endpoint.condition.OnAvailableEndpointCondition.getMatchOutcome(OnAvailableEndpointCondition.java:51) ~[com.example.demo.DemoApplication:2.4.3]
        at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47) ~[com.example.demo.DemoApplication:2.4.3]
        ... 23 common frames omitted
```

This small project reproduces the error:
[actuator-jolokia.zip](https://github.com/spring-projects-experimental/spring-native/files/6157791/actuator-jolokia.zip)

**Comment by aclement** [comment]
I have fixed this - at least curling the java app vs the compiled app gives the same response.  But given I don't think GraalVM supports JMX (IIRC), I'm not sure what working actually looks like for Jolokia totally working (I'm no expert on Jolokia).

**Comment by celcius112** [comment]
Good point @aclement, there are indeed some actuator endpoints that will become unusable with native image, for instance JMX-related or thread/heap dump endpoints. Might it be a good idea to prevent those endpoint to be auto-configured in case of native image ?
