### ISSUE TITLE
Exception in thread "native-image pid watcher" java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by ansarizeeshan** [spring-projects-experimental/spring-native#650]
Not sure if this a bug or not but I noticed the following "java.lang.OutOfMemoryError" during native-image generation for sample - petclinic-jpa.

Describe the bug.
```
[INFO]     [creator]     Exception in thread "native-image pid watcher" java.lang.OutOfMemoryError: GC overhead limit exceeded
[INFO]     [creator]            at com.oracle.svm.hosted.NativeImageGeneratorRunner$1.run(NativeImageGeneratorRunner.java:101)
[INFO]     [creator]            at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[INFO]     [creator]            at java.base/java.util.TimerThread.run(Timer.java:506)
[INFO]     [creator]     Exception in thread "Libgraal MBean Registration" 
[INFO]     [creator]     Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Libgraal MBean Registration"
[INFO]     [creator]     java.lang.OutOfMemoryError: GC overhead limit exceeded
[INFO]     [creator]     Exception in thread "Thread-1" 
[INFO]     [creator]     Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Thread-1"
[INFO]     [creator]     java.lang.OutOfMemoryError: GC overhead limit exceededFatal error:java.lang.OutOfMemoryError
[INFO]     [creator]            at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[INFO]     [creator]            at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[INFO]     [creator]            at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[INFO]     [creator]            at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[INFO]     [creator]            at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
[INFO]     [creator]            at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
[INFO]     [creator]            at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
[INFO]     [creator]            at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:370)
[INFO]     [creator]            at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:529)
[INFO]     [creator]            at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
[INFO]     [creator]            at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:561)
[INFO]     [creator]     Caused by: java.lang.OutOfMemoryError: Java heap space: failed reallocation of scalar replaced objects
[INFO]     [creator]     Error: Image build request failed with exit status 1
[INFO]     [creator]     unable to invoke layer creator
[INFO]     [creator]     unable to contribute native-image layer
[INFO]     [creator]     error running build
[INFO]     [creator]     exit status 1
[INFO]     [creator]     ERROR: failed to build: exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  43:14 min
[INFO] Finished at: 2021-03-23T10:36:18+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.4.4:build-image (default-cli) on project petclinic-jpa: Execution default-cli of goal org.springframework.boot:spring-boot-maven-plugin:2.4.4:build-image failed: Builder lifecycle 'creator' failed with status code 145 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```
Machine info
````
Processor	Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz   1.61 GHz
Installed RAM	8.00 GB (7.88 GB usable)
Edition	Windows 10 Home Single Language
Version	20H2
Experience	Windows Feature Experience Pack 120.2212.31.0
System type	64-bit operating system, x64-based processor
````

Plugins configured as below:
```
<plugin>
	<groupId>org.springframework.experimental</groupId>
	<artifactId>spring-aot-maven-plugin</artifactId>
	<version>${spring-native.version}</version>
	<executions>
		<execution>
			<id>test-generate</id>
			<goals>
				<goal>test-generate</goal>
			</goals>
		</execution>
		<execution>
			<id>generate</id>
			<goals>
				<goal>generate</goal>
			</goals>
		</execution>
	</executions>
</plugin>
<plugin>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-maven-plugin</artifactId>
	<configuration>
		<image>
			<builder>paketobuildpacks/builder:tiny</builder>
			<env>
				<BP_NATIVE_IMAGE>true</BP_NATIVE_IMAGE>
				<BP_NATIVE_IMAGE_BUILD_ARGUMENTS>--enable-https</BP_NATIVE_IMAGE_BUILD_ARGUMENTS>
			</env>
		</image>
	</configuration>
</plugin>
```

**Comment by chaudharydeepak** [comment]
@ansarizeeshan - not sure it helps, but currently spring native requires crazy memory assignment for docker to build these native images. I had to assign 8GB+ to my docker - else I keep getting out-of-memory issues. Have you tried building it with mvn -Pnative-image package i.e. using native-image-maven-plugin which will build native image on your machine? It would require steps as mentioned here -> https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#getting-started-native-image.

**Comment by sdeleuze** [comment]
This is documented [here](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#_system_requirements) and [here](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#_system_requirements).
