### ISSUE TITLE
Add spring-cloud-gcp-starter-sql-mysql support

### ISSUE THREAD

**Issue by ansarizeeshan** [spring-projects-experimental/spring-native#662]
I am following the below doc to add Cloud SQL support.

[https://cloud.spring.io/spring-cloud-gcp/multi/multi__spring_jdbc.html](https://cloud.spring.io/spring-cloud-gcp/multi/multi__spring_jdbc.html)

but getting errors as:

```
java.lang.IllegalStateException: Unable to read meta-data for class org.springframework.cloud.gcp.autoconfigure.datastore.GcpDatastoreEmulatorAutoConfiguration      
        at org.springframework.boot.autoconfigure.AutoConfigurationSorter$AutoConfigurationClass.getAnnotationMetadata(AutoConfigurationSorter.java:237) ~[na:na]    
        at org.springframework.boot.autoconfigure.AutoConfigurationSorter$AutoConfigurationClass.getOrder(AutoConfigurationSorter.java:208) ~[na:na]
        at org.springframework.boot.autoconfigure.AutoConfigurationSorter$AutoConfigurationClass.access$000(AutoConfigurationSorter.java:154) ~[na:na]
        at org.springframework.boot.autoconfigure.AutoConfigurationSorter.lambda$getInPriorityOrder$0(AutoConfigurationSorter.java:63) ~[na:na]
        at java.util.TimSort.binarySort(TimSort.java:296) ~[na:na]
        at java.util.TimSort.sort(TimSort.java:239) ~[na:na]
        at java.util.Arrays.sort(Arrays.java:1515) ~[na:na]
        at java.util.ArrayList.sort(ArrayList.java:1750) ~[org.springframework.samples.petclinic.PetClinicApplication:na]
        at org.springframework.boot.autoconfigure.AutoConfigurationSorter.getInPriorityOrder(AutoConfigurationSorter.java:62) ~[na:na]
        at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector$AutoConfigurationGroup.sortAutoConfigurations(AutoConfigurationImportSelector.java:468) ~[org.springframework.samples.petclinic.PetClinicApplication:2.4.4]
        at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector$AutoConfigurationGroup.selectImports(AutoConfigurationImportSelector.java:453) ~[org.springframework.samples.petclinic.PetClinicApplication:2.4.4]
        at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGrouping.getImports(ConfigurationClassParser.java:882) ~[na:na]     
        at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.processGroupImports(ConfigurationClassParser.java:809) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorHandler.process(ConfigurationClassParser.java:780) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:193) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331) ~[org.springframework.samples.petclinic.PetClinicApplication:5.3.5]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247) ~[org.springframework.samples.petclinic.PetClinicApplication:5.3.5]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311) ~[na:na]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112) ~[na:na]        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) ~[na:na]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[na:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:769) ~[org.springframework.samples.petclinic.PetClinicApplication:2.4.4]        
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) ~[org.springframework.samples.petclinic.PetClinicApplication:2.4.4]        
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) ~[org.springframework.samples.petclinic.PetClinicApplication:2.4.4] 
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) ~[org.springframework.samples.petclinic.PetClinicApplication:2.4.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1313) ~[org.springframework.samples.petclinic.PetClinicApplication:2.4.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[org.springframework.samples.petclinic.PetClinicApplication:2.4.4]
        at org.springframework.samples.petclinic.PetClinicApplication.main(PetClinicApplication.java:33) ~[org.springframework.samples.petclinic.PetClinicApplication:na]
Caused by: java.io.FileNotFoundException: class path resource [org/springframework/cloud/gcp/autoconfigure/datastore/GcpDatastoreEmulatorAutoConfiguration.class] cannot be opened because it does not exist
        at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:187) ~[na:na]
        at org.springframework.core.type.classreading.SimpleMetadataReader.getClassReader(SimpleMetadataReader.java:55) ~[na:na]
        at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:49) ~[na:na]
        at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103) ~[na:na]
        at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.createMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:86) ~[na:na]
        at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.getMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:73) ~[na:na]
        at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:81) ~[na:na]
        at org.springframework.boot.autoconfigure.AutoConfigurationSorter$AutoConfigurationClass.getAnnotationMetadata(AutoConfigurationSorter.java:233) ~[na:na]    
        ... 28 common frames omitted
```

with below dependencies:
```
<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-gcp-dependencies</artifactId>
				<version>1.2.8.BUILD-SNAPSHOT</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
</dependencyManagement>

<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-gcp-starter-sql-mysql</artifactId>
</dependency>
```

**Comment by sdeleuze** [comment]
As far as I understand, as pointed out on https://spring.io/projects/spring-cloud-gcp:
> Spring Cloud GCP is no longer part of the Spring Cloud release train. The new repository location is https://github.com/GoogleCloudPlatform/spring-cloud-gcp. Check out the migration guide to upgrade from version 1.x to 2.0.0.

So I tend to think this issue should be declined and one created on https://github.com/GoogleCloudPlatform/spring-cloud-gcp.

@spencergibb Could you please confirm?

**Comment by spencergibb** [comment]
That's correct
