### ISSUE TITLE
Http protocol not supported

### ISSUE THREAD

**Issue by aathilingam** [spring-projects-experimental/spring-native#677]
I have a spring native app that makes http call to another service. 
I compiled the service using native image maven plugin (mvn -Pnative-image package). Seeing this message when my app tries to make a http call,  **The URL protocol http is supported but not enabled by default. It must be enabled by adding the --enable-url-protocols=http option to the native-image command.** 

Does the maven plugin provide an option to enable HTTP protocol? Appreciate your help.

```
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:8081/v1/test": Accessing an URL protocol that was not enabled. The URL protocol http is supported but not enabled by default. It must be enabled by adding the --enable-url-protocols=http option to the native-image command.; nested exception is java.net.MalformedURsampleception: Accessing an URL protocol that was not enabled. The URL protocol http is supported but not enabled by default. It must be enabled by adding the --enable-url-protocols=http option to the native-image command.
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:785) ~[com.app.demo.sample.SampleApplication:5.3.4]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711) ~[com.app.demo.sample.SampleApplication:5.3.4]
	at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:361) ~[com.app.demo.sample.SampleApplication:5.3.4]
  ----
	at java.util.HashMap$KeySet.forEach(HashMap.java:928) ~[na:na]
	at com.app.demo.sample.swagger.SwaggerAutoRefresh.automaticRefresh(SwaggerAutoRefresh.java:27) ~[com.app.demo.sample.SampleApplication:1.0-SNAPSHOT]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[na:na]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[na:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.util.concurrent.ScheduledThreadPoosampleecutor$ScheduledFutureTask.run(ScheduledThreadPoosampleecutor.java:305) ~[na:na]
	at java.util.concurrent.ThreadPoosampleecutor.runWorker(ThreadPoosampleecutor.java:1128) ~[na:na]
	at java.util.concurrent.ThreadPoosampleecutor$Worker.run(ThreadPoosampleecutor.java:628) ~[na:na]
	at java.lang.Thread.run(Thread.java:834) ~[na:na]
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519) ~[na:na]
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192) ~[na:na]
Caused by: java.net.MalformedURsampleception: Accessing an URL protocol that was not enabled. The URL protocol http is supported but not enabled by default. It must be enabled by adding the --enable-url-protocols=http option to the native-image command.
	at com.oracle.svm.core.jdk.JavaNetSubstitutions.unsupported(JavaNetSubstitutions.java:215) ~[na:na]
	at com.oracle.svm.core.jdk.JavaNetSubstitutions.getURLStreamHandler(JavaNetSubstitutions.java:172) ~[na:na]
	at java.net.URL.getURLStreamHandler(URL.java:71) ~[na:na]
	at java.net.URL.<init>(URL.java:651) ~[na:na]
	at java.net.URL.fromURI(URL.java:719) ~[na:na]
	at java.net.URI.toURL(URI.java:1116) ~[na:na]
	at org.springframework.http.client.SimpleClientHttpRequestFactory.createRequest(SimpleClientHttpRequestFactory.java:145) ~[na:na]
	at org.springframework.http.client.support.HttpAccessor.createRequest(HttpAccessor.java:124) ~[na:na]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:772) ~[com.app.demo.sample.SampleApplication:5.3.4]
	... 18 common frames omitted

```

**Comment by aathilingam** [comment]
Ok, I just have to add the build args to native image maven plugin as below. Closing this ticket.

```
<profiles>
        <profile>
            <id>native-image</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.graalvm.nativeimage</groupId>
                        <artifactId>native-image-maven-plugin</artifactId>
                        <version>21.0.0</version>
                        <configuration>
                            <buildArgs>
                                <buildArgss>--enable-url-protocols=http</buildArgss>
                            </buildArgs>
                            <!-- The native image build needs to know the entry point to your application -->
                            <mainClass>com.app.demo.sample.SampleApplication</mainClass>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>native-image</goal>
                                </goals>
                                <phase>package</phase>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
```
