### ISSUE TITLE
ClassNotFoundException on Apache Commons Pool at runtime

### ISSUE THREAD

**Issue by scalastic** [spring-projects-experimental/spring-native#688]
Hi,

I am trying to get a spring-boot-starter-data-redis-reactive application working with spring-native 0.9.1. When the application is starting in docker, I get this exceptions : 
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jedisConnectionFactory' defined in class path resource [io/scalastic/coronapubsub/virusapp/config/RedisHumanConfig.class]: Invocation of init method failed;
Caused by: java.lang.IllegalArgumentException: Unable to create org.apache.commons.pool2.impl.EvictionPolicy instance of type org.apache.commons.pool2.impl.DefaultEvictionPolicy
Caused by: java.lang.ClassNotFoundException: org.apache.commons.pool2.impl.DefaultEvictionPolicy
```

Which Native Hints syntax should I set on my [Configuration Bean]( https://github.com/scalastic/virusapp/blob/main/src/main/java/io/scalastic/coronapubsub/virusapp/config/RedisHumanConfig.java) ?
Thanks.

The complete stack trace bellow : 
```
2021-03-30 16:03:07.360  INFO 1 --- [           main] i.s.c.virusapp.VirusappApplication       : Starting VirusappApplication using Java 11.0.10 on 9ceb86101175 with PID 1 (/workspace/io.scalastic.coronapubsub.virusapp.VirusappApplication started by cnb in /workspace)
2021-03-30 16:03:07.360  INFO 1 --- [           main] i.s.c.virusapp.VirusappApplication       : No active profile set, falling back to default profiles: default
2021-03-30 16:03:07.376  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2021-03-30 16:03:07.376  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2021-03-30 16:03:07.376  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 0 ms. Found 0 Redis repository interfaces.
2021-03-30 16:03:07.381  WARN 1 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jedisConnectionFactory' defined in class path resource [io/scalastic/coronapubsub/virusapp/config/RedisHumanConfig.class]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Unable to create org.apache.commons.pool2.impl.EvictionPolicy instance of type org.apache.commons.pool2.impl.DefaultEvictionPolicy
2021-03-30 16:03:07.382  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-03-30 16:03:07.383 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jedisConnectionFactory' defined in class path resource [io/scalastic/coronapubsub/virusapp/config/RedisHumanConfig.class]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Unable to create org.apache.commons.pool2.impl.EvictionPolicy instance of type org.apache.commons.pool2.impl.DefaultEvictionPolicy
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786) ~[na:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602) ~[na:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[na:na]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[na:na]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[na:na]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[na:na]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[na:na]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[na:na]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[na:na]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[na:na]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:769) ~[io.scalastic.coronapubsub.virusapp.VirusappApplication:2.4.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) ~[io.scalastic.coronapubsub.virusapp.VirusappApplication:2.4.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) ~[io.scalastic.coronapubsub.virusapp.VirusappApplication:2.4.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) ~[io.scalastic.coronapubsub.virusapp.VirusappApplication:2.4.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1313) ~[io.scalastic.coronapubsub.virusapp.VirusappApplication:2.4.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[io.scalastic.coronapubsub.virusapp.VirusappApplication:2.4.4]
	at io.scalastic.coronapubsub.virusapp.VirusappApplication.main(VirusappApplication.java:25) ~[io.scalastic.coronapubsub.virusapp.VirusappApplication:na]
Caused by: java.lang.IllegalArgumentException: Unable to create org.apache.commons.pool2.impl.EvictionPolicy instance of type org.apache.commons.pool2.impl.DefaultEvictionPolicy
	at org.apache.commons.pool2.impl.BaseGenericObjectPool.setEvictionPolicyClassName(BaseGenericObjectPool.java:667) ~[na:na]
	at org.apache.commons.pool2.impl.BaseGenericObjectPool.setEvictionPolicyClassName(BaseGenericObjectPool.java:698) ~[na:na]
	at org.apache.commons.pool2.impl.BaseGenericObjectPool.setConfig(BaseGenericObjectPool.java:240) ~[na:na]
	at org.apache.commons.pool2.impl.GenericObjectPool.setConfig(GenericObjectPool.java:308) ~[io.scalastic.coronapubsub.virusapp.VirusappApplication:2.9.0]
	at org.apache.commons.pool2.impl.GenericObjectPool.<init>(GenericObjectPool.java:121) ~[io.scalastic.coronapubsub.virusapp.VirusappApplication:2.9.0]
	at redis.clients.jedis.util.Pool.initPool(Pool.java:45) ~[na:na]
	at redis.clients.jedis.util.Pool.<init>(Pool.java:24) ~[na:na]
	at redis.clients.jedis.JedisPoolAbstract.<init>(JedisPoolAbstract.java:15) ~[na:na]
	at redis.clients.jedis.JedisPool.<init>(JedisPool.java:206) ~[na:na]
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.createRedisPool(JedisConnectionFactory.java:398) ~[io.scalastic.coronapubsub.virusapp.VirusappApplication:2.4.6]
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.createPool(JedisConnectionFactory.java:365) ~[io.scalastic.coronapubsub.virusapp.VirusappApplication:2.4.6]
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.afterPropertiesSet(JedisConnectionFactory.java:347) ~[io.scalastic.coronapubsub.virusapp.VirusappApplication:2.4.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845) ~[na:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782) ~[na:na]
	... 16 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.commons.pool2.impl.DefaultEvictionPolicy
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60) ~[na:na]
	at java.lang.Class.forName(DynamicHub.java:1260) ~[na:na]
	at org.apache.commons.pool2.impl.BaseGenericObjectPool.setEvictionPolicy(BaseGenericObjectPool.java:680) ~[na:na]
	at org.apache.commons.pool2.impl.BaseGenericObjectPool.setEvictionPolicyClassName(BaseGenericObjectPool.java:658) ~[na:na]
	... 29 common frames omitted

```

**Comment by scalastic** [comment]
Ok, found the Hint to add : `@TypeHint(types = DefaultEvictionPolicy.class, typeNames = "org.apache.commons.pool2.impl.DefaultEvictionPolicy")`

Now I'm dealing with another exception `com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class io.scalastic.coronapubsub.virusapp.model.Human and no properties discovered to create BeanSerializer` same as (https://github.com/spring-projects-experimental/spring-native/issues/659).

Adding `@JsonAutoDetect(fieldVisibility = Visibility.ANY)` on Component (one possible solution on HotSpot apps) doesn't fix the problem...

**Comment by sdeleuze** [comment]
Indeed we should probably add related Apache Commons Pool hints in Spring Native.

Interesting that you see the same error than #659, please test again when both issues will be fixed.

**Comment by scalastic** [comment]
@sdeleuze Just to trace, now get a functional `Spring Native` `0.9.1` app with `Spring Data Redis` with **hints** on : 
- `DefaultEvictionPolicy` to fix Apache Commons Pool error,
- `GenericToStringSerializer` and `my model entity` to fix #659 same error,
- `redis.clients.jedis.Queable` and `redis.clients.jedis.Builder` to fix `JedisConnectionFactory` error on instantiation

**Comment by mp911de** [comment]
Isn't that something that should be addressed by Commons Pool since all other folks using Commons Pool with a Graal native arrangement will face this issue?

**Comment by sdeleuze** [comment]
@mp911de Yes it should ultimately like [others non Spring hints ](https://github.com/spring-projects-experimental/spring-native/tree/main/spring-native-configuration/src/main/java) but my proposal for now is that we ship what is needed even transitively in Spring Native and we will create the various issues on downstream project when native configuration 2.0 and related native testing support will be ready. If you want to create a PR or issue on Apache Commons Pool that's fine to me, but I wanted to share the global pattern we follow for now.

**Comment by sdeleuze** [comment]
@scalastic Could you please share your project in order to allow me to create a sample from it?

**Comment by scalastic** [comment]
@sdeleuze this is it https://github.com/scalastic/virusapp on `main` branch

**Comment by sdeleuze** [comment]
Using `0.9.2-SNAPSHOT` I was able to remove `GenericToStringSerializer` and DefaultEvictionPolicy` hints.
