### ISSUE TITLE
FileNotFoundException on spring-boot-starter-amqp at runtime

### ISSUE THREAD

**Issue by NicklasWallgren** [spring-projects-experimental/spring-native#702]
Hey, 

I'm trying to to get `spring-boot-starter-amqp` working with `spring-native`. I get the following exception when the application boots. The `HELP.md` doesn't mention anything about the`spring-boot-starter-amqp` package.

Thanks.

```
Caused by: java.io.FileNotFoundException: class path resource [org/springframework/amqp/rabbit/annotation/MultiRabbitBootstrapConfiguration.class] cannot be opened because it does not exist
        at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:187) ~[na:na]
        at org.springframework.core.type.classreading.SimpleMetadataReader.getClassReader(SimpleMetadataReader.java:55) ~[na:na]
        at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:49) ~[na:na]
        at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103) ~[na:na]
        at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.createMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:86) ~[na:na]
        at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.getMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:73) ~[na:na]
        at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:81) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassParser.asSourceClass(ConfigurationClassParser.java:696) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.lambda$processGroupImports$1(ConfigurationClassParser.java:813) ~[na:na]
        ... 33 common frames omitted
```

**Comment by snicoll** [comment]
> The HELP.md doesn't mention anything about thespring-boot-starter-amqp package.

When I add this starter on start.spring.io, the `HELP.md` contains the following entry at the top of the file:

```
The following dependency is not known to work with Spring Native: 'Spring for RabbitMQ'. As a result, your application may not work as expected.
```

RabbitMQ is not yet supported, but we have a PR to add support. I am going to close this one now in favor of #699
