### ISSUE TITLE
spring-boot project failed to build-image using spring-native 

### ISSUE THREAD

**Issue by Paradox98** [spring-projects-experimental/spring-native#723]
spring-boot 2.4.4
spring-native 0.9.1
graalvm 21.0.0.2

```
[demoAppLauncher:1170]    classlist:  34,426.92 ms,  3.10 GB
Warning: class initialization of class org.springframework.boot.logging.logback.LogbackLoggingSystem failed with exception java.lang.NoClassDefFoundError: ch/qos/logback/core/Context. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=org.springframework.boot.logging.logback.LogbackLoggingSystem to explicitly request delayed initialization of this class.
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
Warning: class initialization of class org.springframework.boot.logging.logback.LogbackLoggingSystem failed with exception java.lang.NoClassDefFoundError: ch/qos/logback/core/Context. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=org.springframework.boot.logging.logback.LogbackLoggingSystem to explicitly request delayed initialization of this class.
[demoAppLauncher:1170]        setup:   1,118.24 ms,  3.10 GB
Error: could not find target field: private static org.apache.commons.logging.Log org.springframework.nativex.substitutions.framework.Target_SpringFactoriesLoader.logger
com.oracle.svm.core.util.UserError$UserException: could not find target field: private static org.apache.commons.logging.Log org.springframework.nativex.substitutions.framework.Target_SpringFactoriesLoader.logger
        at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
        at com.oracle.svm.core.util.UserError.guarantee(UserError.java:96)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findOriginalField(AnnotationSubstitutionProcessor.java:757)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleFieldInAliasClass(AnnotationSubstitutionProcessor.java:429)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:343)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:309)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:265)
        at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:929)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:863)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:561)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
        at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1676)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1426)
        at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1387)
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1374)

```
How can I locate the problem? Why is it possible to execute jar directly, but native-image is white

**Comment by sdeleuze** [comment]
Please share your project in order to allow us to help you.

**Comment by Paradox98** [comment]
> Please share your project in order to allow us to help you.

The project is very dependent on a lot, it is impossible to show all

**Comment by Paradox98** [comment]
```
Error: could not find target field: private static org.apache.commons.logging.Log org.springframework.nativex.substitutions.framework.Target_SpringFactoriesLoader.logger
[builder] com.oracle.svm.core.util.UserError$UserException: could not find target field: private static org.apache.commons.logging.Log org.springframework.nativex.substitutions.framework.Target_SpringFactoriesLoader.logger
[builder]       at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
[builder]       at com.oracle.svm.core.util.UserError.guarantee(UserError.java:96)
[builder]       at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findOriginalField(AnnotationSubstitutionProcessor.java:757)
[builder]       at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleFieldInAliasClass(AnnotationSubstitutionProcessor.java:429)
[builder]       at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:343)
[builder]       at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:309)
[builder]       at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:265)
[builder]       at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:929)
[builder]       at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:863)
[builder]       at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:561)
[builder]       at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
[builder]       at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
[builder]       at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[builder]       at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[builder]       at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[builder]       at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[builder] Error: Image build request failed with exit status 1
[builder] ERROR: failed to build: exit status 1
```

look like this one https://github.com/oracle/graal/issues/3035

**Comment by sdeleuze** [comment]
If sharing the original project is not possible, could you please try to craft a minimal repro one in order to allow us to help you?

**Comment by Paradox98** [comment]
I’m trying to do this, but if I can locate a specific problem, it’s solved

**Comment by AuroraTwinkle** [comment]
@Paradox98 Hello, have you solved this problem? I  have a problem like this: **could not find target field: private java.util.List org.springframework.nativex.substitutions.framework.Target_ResourceHttpRequestHandler.locationResources**

**Comment by sdeleuze** [comment]
Wrong version of Spring Framework / Spring Boot used maybe, check the recommended version in the support doc of the version you use.

**Comment by bgrnwdvg** [comment]
@AuroraTwinkle I'm seeing the same error, were you able to find a solution? I've double checked my library versions to make sure everything is compatible and I believe it is.

- spring-native 0.10.6 (compatible with [spring-boot 2.5.9](https://docs.spring.io/spring-native/docs/0.10.6/reference/htmlsingle/#_validate_spring_boot_version_2) and [GraalVM 21.3.0](https://docs.spring.io/spring-native/docs/0.10.6/reference/htmlsingle/#support-graalvm))
- spring-boot 2.5.9
- spring-cloud-function 3.1.3 (compatible with spring-boot 2.5.9 according to the [compatibility matrix](https://github.com/spring-cloud/spring-cloud-release/wiki/Supported-Versions#supported-releases))
- GraalVM Community Edition 21.3.0 (Java 11)
- Native Image 21.3.0 (Java 11)

**Comment by sdeleuze** [comment]
@bgrnwdvg Please use a recent version with related compatible version (latest 0.11.x or 0.12.x release). If you can reproduce with those, please create a new issue with a reproducer.
