### ISSUE TITLE
Add support for Spring Web Services (SOAP)

### ISSUE THREAD

**Issue by douglashg** [spring-projects-experimental/spring-native#743]
jaxax.xml.transform.TransformerException: com.sun.org.apache.xpath.internal.functions.FuncNormalizeSpace.<init>()
at com.sun.org.apache.xpath.internal.compiler.FunctionTable.getFunction(FunctionTable.java:353)

**Comment by sdeleuze** [comment]
Could you please provide a project that would allow us to reproduce this error ?

**Comment by douglashg** [comment]
I use "spring-boot-starter-web-services" module

**Comment by douglashg** [comment]
I can´t send the original project, but if you need , I can create a simple project with same error....

**Comment by douglashg** [comment]
I created a simple demo project using "Spring Initializ", version 2.4.6 (SNAPSHOT)  adding dependencies "Native , Web Services".

[demo1.zip](https://github.com/spring-projects-experimental/spring-native/files/6337880/demo1.zip)

...and then run on docker cmd:  mvn spring-boot:build-image -DskipTests

Result:
[INFO]     [creator]     *** Images (87b36c7fedfb):
[INFO]     [creator]           docker.io/library/demo:0.0.1-SNAPSHOT
[INFO]     [creator]     Adding cache layer 'paketo-buildpacks/graalvm:jdk'
[INFO]     [creator]     Adding cache layer 'paketo-buildpacks/native-image:native-image'
[INFO]
[INFO] Successfully built image 'docker.io/library/demo:0.0.1-SNAPSHOT'
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15:47 min
[INFO] Finished at: 2021-04-19T14:25:34-03:00
[INFO] ------------------------------------------------------------------------


.... But when try start docker : docker run --rm -p 8080:8080 demo:0.0.1-SNAPSHOT

Result:
Caused by: javax.xml.xpath.XPathExpressionException: javax.xml.transform.TransformerException: com.sun.org.apache.xpath.internal.functions.FuncNormalizeSpace.<init>()
        at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.compile(XPathImpl.java:170) ~[na:na]
        at org.springframework.xml.xpath.Jaxp13XPathExpressionFactory.createXPathExpression(Jaxp13XPathExpressionFactory.java:79) ~[na:na]
        ... 33 common frames omitted
Caused by: javax.xml.transform.TransformerException: com.sun.org.apache.xpath.internal.functions.FuncNormalizeSpace.<init>()
        at com.sun.org.apache.xpath.internal.compiler.FunctionTable.getFunction(FunctionTable.java:353) ~[na:na]
        at com.sun.org.apache.xpath.internal.compiler.Compiler.compileFunction(Compiler.java:1060) ~[na:na]
        at com.sun.org.apache.xpath.internal.compiler.Compiler.compile(Compiler.java:204) ~[na:na]
        at com.sun.org.apache.xpath.internal.compiler.Compiler.compile(Compiler.java:152) ~[na:na]
        at com.sun.org.apache.xpath.internal.compiler.Compiler.compileExpression(Compiler.java:126) ~[na:na]
        at com.sun.org.apache.xpath.internal.XPath.<init>(XPath.java:187) ~[na:na]
        at com.sun.org.apache.xpath.internal.XPath.<init>(XPath.java:268) ~[na:na]
        at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.compile(XPathImpl.java:162) ~[na:na]
        ... 34 common frames omitted

**Comment by douglashg** [comment]
Can you verify for me

**Comment by sdeleuze** [comment]
`spring-boot-starter-web-services` [is not yet supported](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#support) so that expected.

**Comment by douglashg** [comment]
I would like to be part of this team, how can I sign up?

**Comment by sdeleuze** [comment]
You can provide PRs.
