### ISSUE TITLE
NullPointerException with kafka with sasl

### ISSUE THREAD

**Issue by han1448** [spring-projects-experimental/spring-native#751]
Hello,
I'm getting NullPointerException while kafka sasl authentication.
And I'm not sure this error is related to spring-native. It might to be related to graalvm config or error.

- springboot: 2.4.5
- spring-native: 0.9.2
- graalvm: graalvm-ce-java8-21.0.0.2

**This application works fine without native-image.**
But When I build it, then I get an error.

### Error message
```
java.lang.NullPointerException: null
        at java.util.regex.Matcher.getTextLength(Matcher.java:1283) ~[na:na]
        at java.util.regex.Matcher.reset(Matcher.java:309) ~[na:na]
        at java.util.regex.Matcher.<init>(Matcher.java:229) ~[na:na]
        at java.util.regex.Pattern.matcher(Pattern.java:1093) ~[na:na]
        at org.apache.kafka.common.security.scram.internals.ScramFormatter.saslName(ScramFormatter.java:106) ~[com.myAppKt:na]
        at org.apache.kafka.common.security.scram.internals.ScramSaslClient.evaluateChallenge(ScramSaslClient.java:115) ~[com.myAppKt:na]
        at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.lambda$createSaslToken$1(SaslClientAuthenticator.java:520) ~[com.myAppKt:na]
        at java.security.AccessController.doPrivileged(AccessController.java:147) ~[com.myAppKt:na]
        at javax.security.auth.Subject.doAs(Subject.java:422) ~[com.myAppKt:na]
        at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.createSaslToken(SaslClientAuthenticator.java:520) ~[com.myAppKt:na]
        at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.sendSaslClientToken(SaslClientAuthenticator.java:427) ~[com.myAppKt:na]
        at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.sendInitialToken(SaslClientAuthenticator.java:326) ~[com.myAppKt:na]
        at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.authenticate(SaslClientAuthenticator.java:267) ~[com.myAppKt:na]
        at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:176) ~[com.myAppKt:na]
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:547) [com.myAppKt:na]
        at org.apache.kafka.common.network.Selector.poll(Selector.java:485) [com.myAppKt:na]
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:544) [com.myAppKt:na]
        at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:325) [com.myAppKt:na]
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:240) [com.myAppKt:na]
        at java.lang.Thread.run(Thread.java:748) [com.myAppKt:na]
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519) [com.myAppKt:na]
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192) [com.myAppKt:na]
```

### Configuration
- application.yaml
```
spring:
  kafka:
    properties:
      security:
        protocol: "SASL_SSL"
      ssl:
        truststore:
          location: "/mytruststore/my.truststore.jks"
          password: "pasword"
        endpoint:
          identification:
            algorithm: ""
      sasl:
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="user" password="password";
        mechanism: "SCRAM-SHA-512"
```
- pom.xml
```
  <plugin>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-maven-plugin</artifactId>
      <configuration>
          <image>
              <builder>paketobuildpacks/builder:tiny</builder>
              <env>
                  <BP_NATIVE_IMAGE>true</BP_NATIVE_IMAGE>
                  <BP_NATIVE_IMAGE_BUILD_ARGUMENTS>
                      --enable-https
                      -H:IncludeResourceBundles=sun.security.util.Resources
                  </BP_NATIVE_IMAGE_BUILD_ARGUMENTS>
              </env>
          </image>
      </configuration>
  </plugin>
```

Before I reached this error, I tried to add some classes in the `@TypeHint` annotation.
```
@TypeHint(
    types = [
        SaslClientCallbackHandler::class,
        DefaultLogin::class, AbstractLogin.DefaultLoginCallbackHandler::class, PlainLoginModule::class,
        LoginModule::class, ScramLoginModule::class, ScramSaslClient::class, ScramSaslClient.ScramSaslClientFactory::class,
    ]
)
```

It seems it can't retrieve the username from `sasl.jass.conf`

Or are there any classes that has to be added in the `@TypeHint`?

**Comment by sdeleuze** [comment]
Hi, where is located `sasl.jass.conf`, in `src/main/resources` or in a JAR?

**Comment by han1448** [comment]
@sdeleuze 
Hi,
`sasl.jass.conf` has the following format.
```
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
   username="myname" \
   password="my-secret";
```

Do you mean truststore file location?
I tried to use docker volume to link my host file.
For example
```bash
docker run -it -v /mytruststore/:/mytruststore \
-e "SPRING_PROFILES_ACTIVE=default" \
-e "--spring.application.name=myapp" \
test.com/application/myapp:1.0.0-SNAPSHOT 
```

Here is full log.
```

2021-04-29 00:50:29.389  INFO 1 --- [actor-tcp-nio-1] o.a.k.clients.producer.ProducerConfig    : ProducerConfig values: 
        acks = 1
        batch.size = 16384
        bootstrap.servers = [mykafka.com:11498]
        buffer.memory = 33554432
        client.dns.lookup = use_all_dns_ips
        client.id = producer-1
        compression.type = gzip
        connections.max.idle.ms = 540000
        delivery.timeout.ms = 120000
        enable.idempotence = false
        interceptor.classes = []
        internal.auto.downgrade.txn.commit = true
        key.serializer = class org.apache.kafka.common.serialization.StringSerializer
        linger.ms = 300
        max.block.ms = 60000
        max.in.flight.requests.per.connection = 5
        max.request.size = 5242880
        metadata.max.age.ms = 300000
        metadata.max.idle.ms = 300000
        metric.reporters = []
        metrics.num.samples = 2
        metrics.recording.level = INFO
        metrics.sample.window.ms = 30000
        partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
        receive.buffer.bytes = 32768
        reconnect.backoff.max.ms = 1000
        reconnect.backoff.ms = 50
        request.timeout.ms = 30000
        retries = 2147483647
        retry.backoff.ms = 100
        sasl.client.callback.handler.class = null
        sasl.jaas.config = [hidden]
        sasl.kerberos.kinit.cmd = /usr/bin/kinit
        sasl.kerberos.min.time.before.relogin = 60000
        sasl.kerberos.service.name = null
        sasl.kerberos.ticket.renew.jitter = 0.05
        sasl.kerberos.ticket.renew.window.factor = 0.8
        sasl.login.callback.handler.class = null
        sasl.login.class = null
        sasl.login.refresh.buffer.seconds = 300
        sasl.login.refresh.min.period.seconds = 60
        sasl.login.refresh.window.factor = 0.8
        sasl.login.refresh.window.jitter = 0.05
        sasl.mechanism = SCRAM-SHA-512
        security.protocol = SASL_SSL
        security.providers = null
        send.buffer.bytes = 131072
        ssl.cipher.suites = null
        ssl.enabled.protocols = [TLSv1.2]
        ssl.endpoint.identification.algorithm = 
        ssl.engine.factory.class = null
        ssl.key.password = null
        ssl.keymanager.algorithm = SunX509
        ssl.keystore.location = null
        ssl.keystore.password = null
        ssl.keystore.type = JKS
        ssl.protocol = TLSv1.2
        ssl.provider = null
        ssl.secure.random.implementation = null
        ssl.trustmanager.algorithm = PKIX
        ssl.truststore.location = /mytruststore/my.truststore.jks
        ssl.truststore.password = [hidden]
        ssl.truststore.type = JKS
        transaction.timeout.ms = 60000
        transactional.id = null
        value.serializer = class org.apache.kafka.common.serialization.StringSerializer

2021-04-29 00:50:29.560  INFO 1 --- [actor-tcp-nio-1] o.a.k.c.s.authenticator.AbstractLogin    : Successfully logged in.
2021-04-29 00:50:29.735  INFO 1 --- [actor-tcp-nio-1] o.a.kafka.common.utils.AppInfoParser     : Kafka version: 2.6.0
2021-04-29 00:50:29.736  INFO 1 --- [actor-tcp-nio-1] o.a.kafka.common.utils.AppInfoParser     : Kafka commitId: 62abe01bee039651
2021-04-29 00:50:29.736  INFO 1 --- [actor-tcp-nio-1] o.a.kafka.common.utils.AppInfoParser     : Kafka startTimeMs: 1619657429734
2021-04-29 00:50:30.171  WARN 1 --- [ad | producer-1] o.apache.kafka.common.network.Selector   : [Producer clientId=producer-1] Unexpected error from mykafka.com:11498; closing connection

java.lang.NullPointerException: null
        at java.util.regex.Matcher.getTextLength(Matcher.java:1283) ~[na:na]
        at java.util.regex.Matcher.reset(Matcher.java:309) ~[na:na]
        at java.util.regex.Matcher.<init>(Matcher.java:229) ~[na:na]
        at java.util.regex.Pattern.matcher(Pattern.java:1093) ~[na:na]
        at org.apache.kafka.common.security.scram.internals.ScramFormatter.saslName(ScramFormatter.java:106) ~[na:na]
        at org.apache.kafka.common.security.scram.internals.ScramSaslClient.evaluateChallenge(ScramSaslClient.java:115) ~[com.myAppKt:na]
        at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.lambda$createSaslToken$1(SaslClientAuthenticator.java:520) ~[na:na]
        at java.security.AccessController.doPrivileged(AccessController.java:147) ~[na:na]
        at javax.security.auth.Subject.doAs(Subject.java:422) ~[na:na]
        at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.createSaslToken(SaslClientAuthenticator.java:520) ~[na:na]
        at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.sendSaslClientToken(SaslClientAuthenticator.java:427) ~[na:na]
        at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.sendInitialToken(SaslClientAuthenticator.java:326) ~[na:na]
        at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.authenticate(SaslClientAuthenticator.java:267) ~[na:na]
        at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:176) ~[na:na]
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:547) [com.myAppKt:na]
        at org.apache.kafka.common.network.Selector.poll(Selector.java:485) [com.myAppKt:na]
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:544) [com.myAppKt:na]
        at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:325) [com.myAppKt:na]
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:240) [com.myAppKt:na]
        at java.lang.Thread.run(Thread.java:748) [com.myAppKt:na]
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519) [com.myAppKt:na]
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192) [com.myAppKt:na]

```

Most of the errors were solved by adding the relevant class to `@TypeHint`
But in this time, I don't know which class should be added.
And I want to know if there is another way.

**Comment by sdeleuze** [comment]
No, I mean where the file is located. If that's in `src/main/resources` it will be added automatically to the native image by Spring Native. If it is in a JAR, you need to add a related resource hint to ship it into the native image. You can check with `-H:Log=registerResource:3` native image option which resource files are included. Thanks in advance for your feedback.

**Comment by robtha** [comment]
I too failed running spring boot kafka as native image.
After adding some Native Hints I got stuck with the following error:

```
Caused by: org.apache.kafka.common.errors.SaslAuthenticationException: Failed to create SaslClient with mechanism PLAIN
Caused by: javax.security.sasl.SaslException: Cannot get userid/password
        at com.sun.security.sasl.ClientFactoryImpl.getUserInfo(ClientFactoryImpl.java:157) ~[com.example.kafka.KafkaApplication:na]
        at com.sun.security.sasl.ClientFactoryImpl.createSaslClient(ClientFactoryImpl.java:94) ~[com.example.kafka.KafkaApplication:na]
        at javax.security.sasl.Sasl.createSaslClient(Sasl.java:433) ~[na:na]
        at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.lambda$createSaslClient$0(SaslClientAuthenticator.java:217) ~[com.example.kafka.KafkaApplication:na]

...
Caused by: javax.security.auth.callback.UnsupportedCallbackException: Could not login: the client is being asked for a password, but the Kafka client code does not currently support obtaining a password from the user.
        at org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler.handle(SaslClientCallbackHandler.java:73) ~[com.example.kafka.KafkaApplication:na]
        at com.sun.security.sasl.ClientFactoryImpl.getUserInfo(ClientFactoryImpl.java:136) ~[com.example.kafka.KafkaApplication:na]
```
		
I used the following configuration settings for kafka:

```
spring.kafka.properties.bootstrap.servers=xyz.aws.confluent.cloud:9092
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='123456' password='abcdefgh...';
```

After some debugging I ended up in `SaslClientCallbackHandler`. The code at line 58 seems to be the problem. As far as I can see the exeption can only be thrown if `Subject` returned from `AccessControllerContext `is null.

```
public void handle(Callback[] callbacks) throws UnsupportedCallbackException {
	Subject subject = Subject.getSubject(AccessController.getContext());
	...
```

I found an issue in the graal repository that indicates this to be problem in GraalVM

https://github.com/oracle/graal/issues/2745	
https://github.com/oracle/graal/pull/3098

As for `ScramSaslClient `the username is provided by SaslClientCallbackHandler I assume that your NPE is resulted from the same problem with AccessController.

**Comment by han1448** [comment]
@robtha 
Thanks for your comment.
It looks like a same issue that I got stuck.
