### ISSUE TITLE
Whether it already supports FastJson

### ISSUE THREAD

**Issue by Paradox98** [spring-projects-experimental/spring-native#752]
```
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Unsupported method java.lang.ClassLoader.defineClass(String, byte[], int, int, ProtectionDomain) is reachable
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:87)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:754)
        at com.alibaba.fastjson.util.ASMClassLoader.defineClassPublic(ASMClassLoader.java:174)
        at com.alibaba.fastjson.parser.deserializer.ASMDeserializerFactory.createJavaBeanDeserializer(ASMDeserializerFactory.java:89)
        at com.alibaba.fastjson.parser.ParserConfig.createJavaBeanDeserializer(ParserConfig.java:1082)
        at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(ParserConfig.java:888)
        at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(ParserConfig.java:593)
        at com.alibaba.fastjson.util.TypeUtils.castToJavaBean(TypeUtils.java:1541)
        at com.alibaba.fastjson.util.TypeUtils.cast(TypeUtils.java:1099)
        at com.alibaba.fastjson.JSONArray.toJavaList(JSONArray.java:453)

```

**Comment by sdeleuze** [comment]
As far as I know, [FastJson](https://github.com/alibaba/fastjson) is not supported at Spring level and it does not provide GraalVM native image support, so I don't think support should be implemented here. We are collaborating with the GraalVM team on a place and guidelines to provide native configuration for libraries like that, so when that's ready that's probably how such support should be provided.
