### ISSUE TITLE
Spring cloud gateway can not startup!

### ISSUE THREAD

**Issue by ZhangGangTW** [spring-projects-experimental/spring-native#771]
I using kotlin + spring native + spring cloud gateway+ spring boot actuator

build.gradle.kts:
```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import org.springframework.boot.gradle.tasks.bundling.BootBuildImage

plugins {
    id("org.springframework.boot") version "2.4.5"
    id("io.spring.dependency-management") version "1.0.11.RELEASE"
    kotlin("jvm") version "1.4.32"
    kotlin("plugin.spring") version "1.4.32"
    id("org.springframework.experimental.aot") version "0.9.2"
}

group = "com.ws"
version = "1.0.2"
java.sourceCompatibility = JavaVersion.VERSION_11

repositories {
    maven { url = uri("https://repo.spring.io/release") }
    mavenCentral()
}

extra["springCloudVersion"] = "2020.0.2"

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-webflux")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
    implementation("io.projectreactor.kotlin:reactor-kotlin-extensions")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-reactor")
    implementation("org.springframework.cloud:spring-cloud-starter-gateway")
}

dependencyManagement {
    imports {
        mavenBom("org.springframework.cloud:spring-cloud-dependencies:${property("springCloudVersion")}")
    }
}

tasks.withType<KotlinCompile> {
    kotlinOptions {
        freeCompilerArgs = listOf("-Xjsr305=strict")
        jvmTarget = "11"
    }
}

tasks.withType<Test> {
    useJUnitPlatform()
}

tasks.withType<BootBuildImage> {
    builder = "paketobuildpacks/builder:tiny"
    imageName = "hataketed/${rootProject.name}:${version}"
    environment = mapOf(
        "BP_NATIVE_IMAGE" to "true"
    )
}
```

After ./gradlew bootBuildImage and then run the image, got this issue:
```
2021-05-08 08:03:05.613  INFO 1 --- [           main] o.s.nativex.NativeListener               : This application is bootstrapped with code generated with Spring AOT

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.4.5)

2021-05-08 08:03:05.633  INFO 1 --- [           main] o.s.boot.SpringApplication               : Starting application using Java 11.0.10 on 53a5a2f2b607 with PID 1 (started by cnb in /workspace)
2021-05-08 08:03:05.633  INFO 1 --- [           main] o.s.boot.SpringApplication               : No active profile set, falling back to default profiles: default
2021-05-08 08:03:05.704 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Error processing condition on org.springframework.cloud.gateway.config.GatewayAutoConfiguration$GatewayActuatorConfiguration.gatewayControllerEndpoint
        at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:60) ~[com.ws.sidecar.ingress.WsSidecarIngressApplicationKt:2.4.5]
        at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:193) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:153) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:129) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:343) ~[com.ws.sidecar.ingress.WsSidecarIngressApplicationKt:5.3.6]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247) ~[com.ws.sidecar.ingress.WsSidecarIngressApplicationKt:5.3.6]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311) ~[na:na]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) ~[na:na]
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:63) ~[na:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:782) ~[com.ws.sidecar.ingress.WsSidecarIngressApplicationKt:2.4.5]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:774) ~[com.ws.sidecar.ingress.WsSidecarIngressApplicationKt:2.4.5]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439) ~[com.ws.sidecar.ingress.WsSidecarIngressApplicationKt:2.4.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:339) ~[com.ws.sidecar.ingress.WsSidecarIngressApplicationKt:2.4.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1340) ~[com.ws.sidecar.ingress.WsSidecarIngressApplicationKt:2.4.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329) ~[com.ws.sidecar.ingress.WsSidecarIngressApplicationKt:2.4.5]
        at com.ws.sidecar.ingress.WsSidecarIngressApplicationKt.main(WsSidecarIngressApplication.kt:13) ~[na:na]
Caused by: java.lang.IllegalArgumentException: Value must not be empty
        at org.springframework.util.Assert.hasText(Assert.java:289) ~[na:na]
        at org.springframework.boot.actuate.endpoint.EndpointId.<init>(EndpointId.java:57) ~[na:na]
        at org.springframework.boot.actuate.endpoint.EndpointId.of(EndpointId.java:129) ~[na:na]
        at org.springframework.boot.actuate.autoconfigure.endpoint.condition.AbstractEndpointCondition.getEnablementOutcome(AbstractEndpointCondition.java:65) ~[na:na]
        at org.springframework.boot.actuate.autoconfigure.endpoint.condition.OnAvailableEndpointCondition.getMatchOutcome(OnAvailableEndpointCondition.java:51) ~[com.ws.sidecar.ingress.WsSidecarIngressApplicationKt:2.4.5]
        at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47) ~[com.ws.sidecar.ingress.WsSidecarIngressApplicationKt:2.4.5]
        ... 18 common frames omitted

```

**Comment by sdeleuze** [comment]
Duplicates #184.
