### ISSUE TITLE
Add support for spring-cloud-sleuth-zipkin

### ISSUE THREAD

**Issue by goafabric** [spring-projects-experimental/spring-native#780]
While spring-cloud-sleuth was recently presented to work with spring-native,
the zipkin variant seems to fail currently.

Maybe thats just a ResourceHint missing, both from the experience with other cases,
this usually unfolds into a multititude of other Hints.
As with the other things, would be great if its getting fixed.

--- cut ---
Caused by: java.io.FileNotFoundException: class path resource [org/springframework/cloud/sleuth/autoconfig/zipkin2/ZipkinRestTemplateSenderConfiguration.class] cannot be opened because it does not exist
        at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:187) ~[na:na]
        at org.springframework.core.type.classreading.SimpleMetadataReader.getClassReader(SimpleMetadataReader.java:55) ~[na:na]
        at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:49) ~[na:na]

**Comment by sdeleuze** [comment]
@marcingrzejszczak @spencergibb Could you please add the relevant sample and hints?

**Comment by marcingrzejszczak** [comment]
Added in https://github.com/spring-projects-experimental/spring-native/pull/785
