### ISSUE TITLE
Container-based build env - failure when running native-image

### ISSUE THREAD

**Issue by ddobrin** [spring-projects-experimental/spring-native#835]
Cloned the main branch of Spring-native.

Followed [docs](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#how-to-contribute-using-container-build-env) and executed "./run-dev-container.sh -p -r" to force the container image rebuild.

In the container, tested a simple [class](https://github.com/ddobrin/native-spring-on-k8s-with-graalvm-workshop/blob/main/setup/Helloworkshop.java):
> javac Helloworkshop.java
> java Helloworkshop
> native-image Helloworkshop

Fails with:
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:315)
	at java.nio.file.Files.createTempFile(Files.java:913)
	at com.oracle.svm.driver.NativeImage.createImageBuilderArgumentFile(NativeImage.java:1403)
	at com.oracle.svm.driver.NativeImage.buildImage(NativeImage.java:1442)
	at com.oracle.svm.driver.NativeImageServer.buildImage(NativeImageServer.java:761)
	at com.oracle.svm.driver.NativeImage.completeImageBuild(NativeImage.java:1271)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1510)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1480)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1467)
	at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1959)
Caused by: java.lang.RuntimeException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: NativePRNG, provider: SUN, class: sun.security.provider.NativePRNG)
	at java.security.SecureRandom.getDefaultPRNG(SecureRandom.java:294)
	at java.security.SecureRandom.<init>(SecureRandom.java:219)
	at java.nio.file.TempFileHelper.<clinit>(TempFileHelper.java:55)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
	... 9 more
Caused by: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: NativePRNG, provider: SUN, class: sun.security.provider.NativePRNG)
	at java.security.Provider$Service.newInstance(Provider.java:1901)
	at java.security.SecureRandom.getDefaultPRNG(SecureRandom.java:290)
	... 13 more
Caused by: java.lang.AssertionError: NativePRNG not available
	at sun.security.provider.NativePRNG.<init>(NativePRNG.java:207)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.security.Provider.newInstanceUtil(Provider.java:176)
	at java.security.Provider$Service.newInstance(Provider.java:1894)

**Comment by sdeleuze** [comment]
I tried and it seems to work on my side, maybe fixed by e65266bc8b4de0212790b0ec5d8035ff5397a708.
```
class HelloWorld {
    public static void main(String[] args) {
        System.out.println("Hello, World!"); 
    }
}
```
```
seb@docker:~/spring-native$ javac hello.java
seb@docker:~/spring-native$ java HelloWorld       
Hello, World!
seb@docker:~/spring-native$ native-image HelloWorld       
[helloworld:500]    classlist:     555.16 ms,  0.96 GB
[helloworld:500]        (cap):     355.77 ms,  0.96 GB
[helloworld:500]        setup:   1,156.25 ms,  0.96 GB
[helloworld:500]     (clinit):      96.18 ms,  1.71 GB
[helloworld:500]   (typeflow):   3,605.58 ms,  1.71 GB
[helloworld:500]    (objects):   3,568.34 ms,  1.71 GB
[helloworld:500]   (features):     376.96 ms,  1.71 GB
[helloworld:500]     analysis:   7,830.37 ms,  1.71 GB
[helloworld:500]     universe:     212.80 ms,  1.71 GB
[helloworld:500]      (parse):     414.67 ms,  1.71 GB
[helloworld:500]     (inline):     853.82 ms,  1.72 GB
[helloworld:500]    (compile):   2,589.11 ms,  3.28 GB
[helloworld:500]      compile:   4,175.29 ms,  3.28 GB
[helloworld:500]        image:     647.49 ms,  3.28 GB
[helloworld:500]        write:      99.91 ms,  3.28 GB
# Printing build artifacts to: helloworld.build_artifacts.txt
[helloworld:500]      [total]:  14,778.10 ms,  3.28 GB
seb@docker:~/spring-native$ ./helloworld 
Hello, World!
```
