### ISSUE TITLE
No HttpMessageConverter when trying to fetch JSON using RestTemplate 

### ISSUE THREAD

**Issue by lealoureiro** [spring-projects-experimental/spring-native#838]
Hi guys,

I have simple Spring Boot application (2.5.1) where it makes basic HTTP requests using RestTemplate to fetch some JSON files from internet.

But i'm getting some errors when one of the services tries to fetch and parse JSON that is just a simple list of strings.

The application runs fine when run in "JVM Mode".

I also tried to add some entries related to `HttpMessageConverter` in `reflect-config.json` and `resource-config.json` files.

```
2021-06-18 16:09:46.628  WARN 84683 --- [   API Worker 1] o.l.m.services.IndianGodsServiceImpl     : org.springframework.web.client.RestClientException: No HttpMessageConverter for org.leandroloureiro.mahabharatagods.services.IndianGodsServiceImpl$1

java.util.concurrent.CompletionException: org.springframework.web.client.RestClientException: No HttpMessageConverter for org.leandroloureiro.mahabharatagods.services.IndianGodsServiceImpl$1
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[na:na]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[na:na]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702) ~[na:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.lang.Thread.run(Thread.java:829) ~[na:na]
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:553) ~[na:na]
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192) ~[na:na]
Caused by: org.springframework.web.client.RestClientException: No HttpMessageConverter for org.leandroloureiro.mahabharatagods.services.IndianGodsServiceImpl$1
	at org.springframework.web.client.RestTemplate$HttpEntityRequestCallback.doWithRequest(RestTemplate.java:1000) ~[na:na]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:774) ~[mahabharata-gods-native:5.3.8]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:751) ~[mahabharata-gods-native:5.3.8]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:651) ~[mahabharata-gods-native:5.3.8]
	at org.leandroloureiro.mahabharatagods.services.IndianGodsServiceImpl.lambda$getGodList$0(IndianGodsServiceImpl.java:56) ~[mahabharata-gods-native:1.0.0-SNAPSHOT]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[na:na]
	... 5 common frames omitted
```

Service code:
```
@Service
public class IndianGodsServiceImpl implements IndianGodsService {

    private static final Logger LOG = LoggerFactory.getLogger(IndianGodsServiceImpl.class);

    private final RestTemplate client;
    private final Executor apiCallExecutor;
    private final String indianGodsServiceHostname;

    public IndianGodsServiceImpl(RestTemplate client, Executor apiCallExecutor, String indianGodsServiceHostname) {
        this.client = client;
        this.apiCallExecutor = apiCallExecutor;
        this.indianGodsServiceHostname = indianGodsServiceHostname;
    }

    @Override
    public CompletableFuture<Optional<List<String>>> getGodList() {

        return CompletableFuture.supplyAsync(() -> {

            ParameterizedTypeReference<List<String>> type = new ParameterizedTypeReference<>() {
            };

            var either = getURI(indianGodsServiceHostname);

            LOG.info("Fetching gods...");

            List<String> gods;
            if (either.isRight()) {
                gods = client.exchange(
                        either.get(),
                        HttpMethod.GET,
                        new HttpEntity<>(type),
                        type
                ).getBody();

            } else {
                gods = new ArrayList<>();
            }

            LOG.info("Loaded {} gods.", Objects.nonNull(gods) ? gods.size() : 0);

            return gods;

        }, apiCallExecutor).handle((response, e) -> {
            if (Objects.isNull(e)) {
                if (response.isEmpty()) {
                    return Optional.empty();
                }
                return Optional.of(response);
            }
            LOG.warn(e.getLocalizedMessage(), e);
            return Optional.empty();
        });
    }

    private static Either<String, URI> getURI(String address) {

        try {

            var baseUrl = "http://" + address + "/jabrena/latency-problems/indian";

            return Either.right(new URI(baseUrl));

        } catch (URISyntaxException e) {

            LOG.error("Failed to create resource URL", e);
            return Either.left("Indian Gods resource URI invalid!");

        }
    }

}

```

The full project is available here. [Project](https://github.com/lealoureiro/mahabharata-gods-native)

**Comment by sdeleuze** [comment]
The native app seems to compile and run fine for me, how should I reproduce?

**Comment by lealoureiro** [comment]
Yes indeed, the app compiles and runs fine. I forgot to specify exactly how to reproduce the problem.

You need to call the "top gods" endpoint (make sure the application has internet access).
With httpie would be:

```bash
http :8080/top-gods
```

**Comment by sdeleuze** [comment]
Ok indeed I can reproduce, but after a quick check I was not able to identify the source of the issue. Most probably missing reflection entries. Could you please try to run it with [the native configuration generated by the tracing agent](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#tracing-agent) to see if that works?

**Comment by lealoureiro** [comment]
I tried to run with TracingAgent as explained in details you mentioned but now I'm having this issue:

```bash
Error: Main entry point class 'org.graalvm.junit.platform.NativeImageJUnitLauncher' not found.
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

Seems like some jUnit classes to run in native are missing... 

I'm using GraalVM with SDKMan  21.1.0.r11-grl

**Comment by sdeleuze** [comment]
This is caused by https://github.com/graalvm/native-build-tools/issues/73, use `mvn -Pnative -DskipTests package` or add the missing dependency with:

```
				<dependency>
					<groupId>org.graalvm.buildtools</groupId>
					<artifactId>junit-platform-native</artifactId>
					<version>${native.buildtools.version}</version>
					<scope>test</scope>
				</dependency>
```

**Comment by lealoureiro** [comment]
Added:

```xml
        <dependency>
            <groupId>org.graalvm.buildtools</groupId>
            <artifactId>junit-platform-native</artifactId>
            <version>${native.buildtools.version}</version>
            <scope>test</scope>
        </dependency>
```
And:

```xml
<configuration>
    <buildArgs>--trace-class-initialization=jdk.xml.internal.SecuritySupport</buildArgs>
</configuration>
```

And I'm still facing this problems:
```bash
[native-tests:9349]     analysis:   9,346.91 ms,  1.72 GB
Error: Classes that should be initialized at run time got initialized during image building:
 jdk.xml.internal.SecuritySupport was unintentionally initialized at build time. org.slf4j.impl.StaticLoggerBinder caused initialization of this class with the following trace:
	at jdk.xml.internal.SecuritySupport.<clinit>(SecuritySupport.java:48)
	at javax.xml.parsers.FactoryFinder.<clinit>(FactoryFinder.java:69)
	at javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:147)
	at ch.qos.logback.core.joran.event.SaxEventRecorder.buildSaxParser(SaxEventRecorder.java:79)
	at ch.qos.logback.core.joran.event.SaxEventRecorder.recordEvents(SaxEventRecorder.java:57)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:151)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
```

I tried to add this annotation in the Application class, but didn't help:
```java
@NativeHint(
        options = {"--enable-url-protocols=http"},
        initialization = {
                @InitializationHint(
                        initTime = InitializationTime.BUILD,
                        types = {
                                org.slf4j.impl.StaticLoggerBinder.class,
                                org.slf4j.LoggerFactory.class,
                                ch.qos.logback.classic.Logger.class,
                                ch.qos.logback.core.spi.AppenderAttachableImpl.class,
                                ch.qos.logback.core.status.StatusBase.class,
                                ch.qos.logback.classic.Level.class,
                                ch.qos.logback.core.status.InfoStatus.class,
                                ch.qos.logback.classic.PatternLayout.class,
                                ch.qos.logback.core.CoreConstants.class
                        }
                )
        }
)
```

I notice that the class that is being mentioned in the error: **org.slf4j.impl.StaticLoggerBinder** is already defined in **--initialize-at-build-time** at **native-image.properties** in **generated-test-sources**

**Comment by sdeleuze** [comment]
This error is due to the `logback-test.xml` file, please remove it since it is not supported yet. I think for now we should focus on running the app via `./mvnw clean -Pnative -DskipTests package` since your tests are using Mockito and other unsupported testing libraries.

**Comment by sdeleuze** [comment]
Works with additional hints which are IMO specific to your application.

```
@TypeHint(types = {
        ParameterizedTypeReference.class,
        Type.class
}, typeNames = "org.leandroloureiro.mahabharatagods.services.IndianGodsServiceImpl$1", access = AccessBits.FULL_REFLECTION)
```
