### ISSUE TITLE
Remove remaining suspicious static fields from Spring AOT

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#879]
Could potentially cause issues with Gradle daemon

**Comment by sdeleuze** [comment]
What I see on my side with the Gradle daemon after some time:
```
16:04 $ ./gradlew --stacktrace -x :test nativeBuild
> Task :generateAot FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':generateAot'.
> Could not generate spring.factories source code
* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':generateAot'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$3(ExecuteActionsTaskExecuter.java:186)
...
org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:411)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:398)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:391)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:377)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.RuntimeException: Cannot resolve org.springframework.nativex.GeneratedClassNotFoundExceptionFailureAnalyzer
        at org.springframework.core.type.classreading.DefaultTypeSystem.resolve(DefaultTypeSystem.java:57)
        at org.springframework.core.type.classreading.TypeSystem.resolveClass(TypeSystem.java:34)
        at org.springframework.aot.factories.SpringFactory.resolve(SpringFactory.java:48)
        at org.springframework.aot.factories.SpringFactoriesContributor.loadSpringFactories(SpringFactoriesContributor.java:103)
        at org.springframework.aot.factories.SpringFactoriesContributor.contribute(SpringFactoriesContributor.java:67)
        ... 125 more
Caused by: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
        at org.springframework.asm.ClassReader.readStream(ClassReader.java:321)
        at org.springframework.asm.ClassReader.<init>(ClassReader.java:287)
        at org.springframework.core.type.classreading.DefaultClassDescriptorReader.getClassReader(DefaultClassDescriptorReader.java:44)
        at org.springframework.core.type.classreading.DefaultClassDescriptorReader.readDescriptor(DefaultClassDescriptorReader.java:37)
        at org.springframework.core.type.classreading.DefaultTypeDescriptor.<init>(DefaultTypeDescriptor.java:46)
        at org.springframework.core.type.classreading.DefaultTypeSystem.resolve(DefaultTypeSystem.java:54)
```
