### ISSUE TITLE
Spring Data Audit Not Working Even After 0.10.1

### ISSUE THREAD

**Issue by matthenry87** [spring-projects-experimental/spring-native#882]
This still doesn't work in 0.10.1, even after the support for @Transactional and @Async was added w/ the Class Proxy hints.

Here is a sample project:

https://github.com/matthenry87/native-spring-data-auditing

```
Could not configure Spring Data JPA auditing-feature because spring-aspects.jar is not on the classpath!
If you want to use auditing please add spring-aspects.jar to the classpath.
2021-06-29 03:18:29.044  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-06-29 03:18:29.045 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanDefinitionStoreException: org.springframework.beans.factory.aspectj.AnnotationBeanConfigurerAspect not found.
Could not configure Spring Data JPA auditing-feature because spring-aspects.jar is not on the classpath!
If you want to use auditing please add spring-aspects.jar to the classpath.
        at org.springframework.data.jpa.repository.config.JpaAuditingRegistrar.registerBeanConfigurerAspectIfNecessary(JpaAuditingRegistrar.java:125) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:2.5.2]
        at org.springframework.data.jpa.repository.config.JpaAuditingRegistrar.registerBeanDefinitions(JpaAuditingRegistrar.java:88) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:2.5.2]
        at org.springframework.context.annotation.ImportBeanDefinitionRegistrar.registerBeanDefinitions(ImportBeanDefinitionRegistrar.java:86) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:5.3.8]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.lambda$loadBeanDefinitionsFromRegistrars$1(ConfigurationClassBeanDefinitionReader.java:396) ~[na:na]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromRegistrars(ConfigurationClassBeanDefinitionReader.java:395) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:157) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:129) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:343) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:5.3.8]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:5.3.8]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311) ~[na:na]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) ~[na:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:2.5.2]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:2.5.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:2.5.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:2.5.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:2.5.2]
        at io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication.main(NativeSpringDataAuditingApplication.java:31) ~[io.mattyhenry87.nativespringdataauditing.NativeSpringDataAuditingApplication:na]

**Comment by sdeleuze** [comment]
@christophstrobl @schauder Could you please remind me the status of Spring Data Audit support?

**Comment by schauder** [comment]
This was fixed by #794 which went on `main` just *after* the release of 10.1.

Therefore I think we can close this as a duplicate.

**Comment by sdeleuze** [comment]
I tried the provided sample, upgrading to `0.10.2-SNAPSHOT` and adding `spring-aspect` dependency, but it fails with the following error:

```
org.springframework.beans.factory.BeanDefinitionStoreException: org.springframework.beans.factory.aspectj.AnnotationBeanConfigurerAspect not found. 
Could not configure Spring Data JPA auditing-feature because spring-aspects.jar is not on the classpath!
If you want to use auditing please add spring-aspects.jar to the classpath.
	at org.springframework.data.jpa.repository.config.JpaAuditingRegistrar.registerBeanConfigurerAspectIfNecessary(JpaAuditingRegistrar.java:125) ~[native-spring-data-auditing:2.5.2]
```
Could you please have a look?

**Comment by schauder** [comment]
I noticed #794 was only for JDBC, this is about JPA. I'll work on a PR for all Spring Data Modules.
