### ISSUE TITLE
Add JNIConfiguration make failed native packaging

### ISSUE THREAD

**Issue by laurentforet** [spring-projects-experimental/spring-native#901]
On a simple working web project, build with spring initializer with spring-native 0.10.1.

I try to add access to a native librairie with a java wrapper (https://jce.iaik.tugraz.at/products/core-crypto-toolkits/pkcs11-wrapper/) . 

So I had in my project a `META-INF\native-images\{group-id}\{artifactid}\native-image.properties`  with the following line : 
```
Arg = -H:JNIConfigurationFiles=${.}/jni-config.json
```
And a simple `META-INF\native-images\{group-id}\{artifactid}\jni-config.json` : 
```
[
  {
    "name" : "iaik.pkcs.pkcs11.wrapper.PKCS11Implementation",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredClasses" : true,
    "allPublicClasses" : true
  }
]
```

And that's 2 files make fail the build ` mvn -Pnative package -DskipTests=true` :  

```
[native-cps:20644]     (clinit):   1,165.89 ms,  5.73 GB
[native-cps:20644]   (typeflow):  28,006.51 ms,  5.73 GB
[native-cps:20644]    (objects):  33,187.64 ms,  5.73 GB
[native-cps:20644]   (features):   5,940.93 ms,  5.73 GB
[native-cps:20644]     analysis:  70,561.21 ms,  5.73 GB
[native-cps:20644]     universe:   2,482.15 ms,  5.73 GB
Fatal error:java.lang.NoClassDefFoundError
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
        at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:499)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:370)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:531)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:568)
Caused by: java.lang.NoClassDefFoundError: org/springframework/dao/DataAccessException
        at jdk.internal.vm.ci/jdk.vm.ci.hotspot.CompilerToVM.getDeclaredMethods(Native Method)
        at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotResolvedObjectTypeImpl.getDeclaredMethods(HotSpotResolvedObjectTypeImpl.java:987)
        at com.oracle.svm.jni.access.JNIAccessibleMethod.anyMatchIgnoreReturnType(JNIAccessibleMethod.java:139)
        at com.oracle.svm.jni.access.JNIAccessibleMember.findHidingSubclasses(JNIAccessibleMember.java:103)
        at com.oracle.svm.jni.access.JNIAccessibleMember.findHidingSubclasses(JNIAccessibleMember.java:110)
        at com.oracle.svm.jni.access.JNIAccessibleMember.setHidingSubclasses(JNIAccessibleMember.java:83)
        at com.oracle.svm.jni.access.JNIAccessibleMethod.finishBeforeCompilation(JNIAccessibleMethod.java:135)
        at com.oracle.svm.jni.access.JNIAccessFeature.beforeCompilation(JNIAccessFeature.java:363)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$doRun$8(NativeImageGenerator.java:644)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:71)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:644)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$2(NativeImageGenerator.java:495)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.ClassNotFoundException: org.springframework.dao.DataAccessException
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 18 more
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
        at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1772)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1519)
        at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1480)
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1467)
        at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1959)
```

It makes me think that I have broken the previous jni config. I do not know how I can solve this issue. 
Any help will be appreciated.

**Comment by laurentforet** [comment]
The complete log of the build [cps-native-build-failed.log](https://github.com/spring-projects-experimental/spring-native/files/6796580/cps-native-build-failed.log)

**Comment by ttddyy** [comment]
Hi @laurentforet 

I haven't used JNI but looking at the code:

First, in `native-image.properties` file, there is a typo. `Arg` should be `Args`. So, your configuration is not taken into account. However, since `jni-config.json` is the default name of the file, regardless of your `native-image.properties` file, the actual `META-INF/.../jni-config.json` should be picked up.

I am not sure about this but based on the error log, it is trying to instantiate a class. So the target class, assuming `PKCS11Implementation`, may need this entry:
```json
"methods": [
  {
    "name": "<init>",
    "parameterTypes": [] 
  }
]
```

note: `parameterTypes` may need arg types based on how it is instantiated

**Comment by sdeleuze** [comment]
@ttddyy Thanks for your help on qualifying this issue.

@laurentforet Based on the discussion above, it seems I can close this issue. Please comment if that's not the case.
