### ISSUE TITLE
JavaFx not work with spring native

### ISSUE THREAD

**Issue by WangZemin0816** [spring-projects-experimental/spring-native#905]
OS: windows11

The build exe of spring native run failed.

Jul 18, 2021 9:59:48 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @e1c34d2'
Graphics Device initialization failed for :  d3d, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:254)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:264)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)

**Comment by sdeleuze** [comment]
That's probably something to raise on GraalVM side, maybe in https://github.com/oracle/graal/issues/403.

**Comment by liudonghua123** [comment]
I have a similar issue on this. See https://github.com/oracle/graal/issues/403#issuecomment-985385284.
