### ISSUE TITLE
How to `@EnableReactiveMethodSecurity` on a native webflux app ?

### ISSUE THREAD

**Issue by ch4mpy** [spring-projects-experimental/spring-native#938]
I started from `security-webflux` sample and tried to activate method security in two steps:

- add `@EnableReactiveMethodSecurity` to `SecurityConfig`
- add `@PreAuthorize("hasRole('ADMIN')")` and change return type to `Mono<String>` to `admin()` method in `MainController`

As error message suggests, I tried to decorate `SecurityWebfluxApplication` with `@AotProxyHint(targetClass=com.example.webflux.MainController.class, proxyFeatures = ProxyBits.IS_STATIC)`, but this has absolutely no effect (same error, same suggestion).

Native app packaging with `mvn clean spring-boot:build-image`works, but application won't start with `docker run security-webflux:0.0.1-SNAPSHOT`:
```
2021-07-27 20:57:11.807 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mainController' defined in class path resource [com/example/webflux/MainController.class]: Initialization of bean failed; nested exception is org.springframework.aop.framework.AopConfigException: Unexpected problem loading and instantiating proxy for target class class com.example.webflux.MainController; nested exception is java.lang.IllegalStateException: Class proxy missing at runtime, hint required at build time: @AotProxyHint(targetClass=com.example.webflux.MainController.class, proxyFeatures = ProxyBits.IS_STATIC)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:610) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[na:na]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[na:na]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[na:na]
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:64) ~[na:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) [com.example.webflux.SecurityWebfluxApplication:na]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) [com.example.webflux.SecurityWebfluxApplication:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) [com.example.webflux.SecurityWebfluxApplication:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) [com.example.webflux.SecurityWebfluxApplication:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) [com.example.webflux.SecurityWebfluxApplication:na]
        at com.example.webflux.SecurityWebfluxApplication.main(SecurityWebfluxApplication.java:13) [com.example.webflux.SecurityWebfluxApplication:na]
Caused by: org.springframework.aop.framework.AopConfigException: Unexpected problem loading and instantiating proxy for target class class com.example.webflux.MainController; nested exception is java.lang.IllegalStateException: Class proxy missing at runtime, hint required at build time: @AotProxyHint(targetClass=com.example.webflux.MainController.class, proxyFeatures = ProxyBits.IS_STATIC)
        at org.springframework.aop.framework.BuildTimeAopProxy.getProxy(BuildTimeAopProxy.java:159) ~[na:na]
        at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:110) ~[na:na]
        at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.createProxy(AbstractAutoProxyCreator.java:478) ~[com.example.webflux.SecurityWebfluxApplication:5.3.9]
        at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:342) ~[com.example.webflux.SecurityWebfluxApplication:5.3.9]
        at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:291) ~[com.example.webflux.SecurityWebfluxApplication:5.3.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:437) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602) ~[na:na]
        ... 15 common frames omitted
Caused by: java.lang.IllegalStateException: Class proxy missing at runtime, hint required at build time: @AotProxyHint(targetClass=com.example.webflux.MainController.class, proxyFeatures = ProxyBits.IS_STATIC)
        at org.springframework.aop.framework.BuildTimeAopProxy.getProxy(BuildTimeAopProxy.java:147) ~[na:na]
        ... 22 common frames omitted
```

I opened [a PR](https://github.com/spring-projects-experimental/spring-native/pull/939) with my modifications to reproduce this error.

**Comment by sdeleuze** [comment]
@eleftherias Could you please have a look to this one?

**Comment by ch4mpy** [comment]
Funny: I wanted to check the issue still occurs on the modified `security-webflux` from my [PR](https://github.com/ch4mpy/spring-native/commit/0859564612c31738ad78173a7e38ecd32a8d603f) with latest buildpacks image. 
It was gone but just for the 1st build :/

Here is what I did:
-`mvn clean spring-boot:build-image` => build successful
- `docker run security-webflux:0.0.1-SNAPSHOT` => start successful
- remove `@AotProxyHint(targetClass = com.example.webflux.MainController.class, proxyFeatures = ProxyBits.IS_STATIC)` from main class => build sucessful
- `docker run security-webflux:0.0.1-SNAPSHOT` => start fails with `java.lang.IllegalStateException: Class proxy missing at runtime, hint required at build time: @AotProxyHint(targetClass=com.example.webflux.MainController.class, proxyFeatures = ProxyBits.IS_STATIC)`
- restore `@AotProxyHint(targetClass = com.example.webflux.MainController.class, proxyFeatures = ProxyBits.IS_STATIC)` on main class => build sucessful
- `docker run security-webflux:0.0.1-SNAPSHOT` => start still fails with `java.lang.IllegalStateException: Class proxy missing at runtime, hint required at build time: @AotProxyHint(targetClass=com.example.webflux.MainController.class, proxyFeatures = ProxyBits.IS_STATIC)`

**Comment by ch4mpy** [comment]
I got it for the last question: 
- in `security-method` only **interfaces** are decorated with spring-security annotations
- in `security-method-class-proxies`, `@AotProxyHint` is required because a **class** is decorated with spring-security annotations.

Closing as issue is gone with latest snapshots.
