### ISSUE TITLE
RestController with Annotations at the Service Interface is not working in native Mode

### ISSUE THREAD

**Issue by goafabric** [spring-projects-experimental/spring-native#955]
Imagine an interface and an Implementing Restcontroller Class like below.
While everything works like a charm in JVM mode and I've been using this for years,
its not working in native mode.

The Application crashes with the Exception below:

org.springframework.http.converter.HttpMessageNotWritableException: No converter for [class org.goafabric.calleeservice.service.Callee] with preset Content-Type 'null'

Calle is just a simple Pojo ....

--- Interface ---
@RequestMapping(value = "callees", produces = MediaType.APPLICATION_JSON_VALUE)
public interface CalleeService {
    @GetMapping("sayMyName")
    Callee sayMyName (@RequestParam String name);

    @GetMapping("sayMyOtherName/{name}")
    Callee sayMyOtherName(@PathVariable String name);
}

--- Implementing class ---
And an implementing class
@RestController
public class CalleeServiceBean implements CalleeService {
    @Autowired
    CalleeLogic calleeLogic;

    public Callee sayMyName (@RequestParam String name) {
        return calleeLogic.sayMyName(name);
    }
}

--- Complete Exception ---

org.springframework.http.converter.HttpMessageNotWritableException: No converter for [class org.goafabric.calleeservice.service.Callee] with preset Content-Type 'null'
at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:312) ~[na:na]
at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.handleReturnValue(RequestResponseBodyMethodProcessor.java:183) ~[na:na]
at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:78) ~[na:na]
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:124) ~[na:na]
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[org.goafabric.calleeservice.Application:5.3.9]

**Comment by sdeleuze** [comment]
@goafabric Could you test if this is still an issue with `0.11.0-SNAPSHOT` or the upcoming `0.11.0-M1`?

**Comment by goafabric** [comment]
@sdeleuze yes sure, can do that,thx

**Comment by sdeleuze** [comment]
Please provide a repro for this using `0.11.0-RC1` and I will have a deeper loop. Please avoid adding `springdoc-openapi-ui ` to the mix.

**Comment by goafabric** [comment]
@sdeleuze thx for your time and support .. Service Interface seems to work with 0.11.0-RC1 and for the Spring Security Problem we already have another issue .. so i think you can close this one

one more thing, concerning https://github.com/spring-projects-experimental/spring-native/issues/949 I added another comment after it's closed, at least with 10.4 the issue is till open for me
but i can retry with 0.11-0-RC

thx again for your time and effort for everything spring native, 
regards
Andreas
