### ISSUE TITLE
time zone problem

### ISSUE THREAD

**Issue by turing1989** [spring-projects-experimental/spring-native#976]
we use spring-native  && spring-boot-data-jpa , in IDEA start is ok , but use ‘mvn clean -U -DskipTests spring-boot:build-image
’  to build image then:

Caused by: java.lang.ExceptionInInitializerError: null

at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:315) ~[na:na]

at com.mysql.jdbc.Util.stackTraceToString(Util.java:356) ~[na:na]

at com.mysql.jdbc.Util.<clinit>(Util.java:120) ~[na:na]

at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375) ~[na:na]

at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295) ~[na:na]

at com.mysql.jdbc.NonRegisteringDriver.parseURL(NonRegisteringDriver.java:720) ~[na:na]

at com.mysql.jdbc.NonRegisteringDriver.acceptsURL(NonRegisteringDriver.java:259) ~[na:na]

at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:109) ~[na:na]

at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:331) ~[na:na]

at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:114) ~[na:na]

at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:108) ~[na:na]

at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[com.example.demo.DemoApplication:na]

at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158) ~[na:na]

at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116) ~[na:na]

at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79) ~[na:na]

at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:330) ~[com.example.demo.DemoApplication:na]

at org.springframework.boot.jdbc.EmbeddedDatabaseConnection.isEmbedded(EmbeddedDatabaseConnection.java:184) ~[com.example.demo.DemoApplication:na]

at org.springframework.boot.autoconfigure.orm.jpa.HibernateDefaultDdlAutoProvider.getDefaultDdlAuto(HibernateDefaultDdlAutoProvider.java:42) ~[na:na]

at org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration.lambda$getVendorProperties$1(HibernateJpaConfiguration.java:130) ~[com.example.demo.DemoApplication:na]

at org.springframework.boot.autoconfigure.orm.jpa.HibernateSettings.getDdlAuto(HibernateSettings.java:41) ~[na:na]

at org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties.determineDdlAuto(HibernateProperties.java:143) ~[com.example.demo.DemoApplication:na]

at org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties.getAdditionalProperties(HibernateProperties.java:103) ~[com.example.demo.DemoApplication:na]

at org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties.determineHibernateProperties(HibernateProperties.java:95) ~[com.example.demo.DemoApplication:na]

at org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration.getVendorProperties(HibernateJpaConfiguration.java:132) ~[com.example.demo.DemoApplication:na]

at org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration.entityManagerFactory(JpaBaseConfiguration.java:132) ~[com.example.demo.DemoApplication:na]

at java.lang.reflect.Method.invoke(Method.java:498) ~[na:na]

at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[na:na]

... 20 common frames omitted

Caused by: java.lang.RuntimeException: Can't load resource bundle due to underlying exception java.util.MissingResourceException: Resource bundle not found com.mysql.jdbc.LocalizedErrorMessages, locale en_US. Register the resource bundle using the option -H:IncludeResourceBundles=com.mysql.jdbc.LocalizedErrorMessages.

at com.mysql.jdbc.Messages.<clinit>(Messages.java:54) ~[na:na]

at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375) ~[na:na]

at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295) ~[na:na]

... 46 common frames omitted

Caused by: java.util.MissingResourceException: Resource bundle not found com.mysql.jdbc.LocalizedErrorMessages, locale en_US. Register the resource bundle using the option -H:IncludeResourceBundles=com.mysql.jdbc.LocalizedErrorMessages.

at com.oracle.svm.core.jdk.localization.OptimizedLocalizationSupport.getCached(OptimizedLocalizationSupport.java:72) ~[na:na]

at java.util.ResourceBundle.getBundle(ResourceBundle.java:53) ~[na:na]

at com.mysql.jdbc.Messages.<clinit>(Messages.java:52) ~[na:na]

... 48 common frames omitted

I guess it may be the time zone problem. How to solve it？Thank you!

**Comment by sdeleuze** [comment]
Did you try with `serverTimezone=UTC` like in https://github.com/spring-projects-experimental/spring-native/blob/main/samples/petclinic-jpa/src/main/resources/application.properties#L3?

**Comment by turing1989** [comment]
> Did you try with `serverTimezone=UTC` like in https://github.com/spring-projects-experimental/spring-native/blob/main/samples/petclinic-jpa/src/main/resources/application.properties#L3?

it is not work

**Comment by sdeleuze** [comment]
Ok please provide a reproducer project, we will then have a deeper look.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
