### ISSUE TITLE
Support for WebServerFactoryCustomizer / tomcat SslConnectorCustomizer

### ISSUE THREAD

**Issue by arielcarrera** [spring-projects-experimental/spring-native#982]
When a custom web server factory is defined to open a custom SSL port a Graalvm exception is thrown (**Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Setting a custom URLStreamHandlerFactory**).

Custom config:

        @Bean
	public WebServerFactoryCustomizer<TomcatServletWebServerFactory> sslStoreCustomizer() throws Exception {
		return tomcat -> {
			Ssl ssl = new Ssl();
			ssl.setKeyAlias(keyAlias);
			ssl.setKeyPassword(keystorePassword);
			tomcat.setSsl(ssl);
			tomcat.setSslStoreProvider(new SslStoreProvider() {
				@Override
				public KeyStore getKeyStore() {
					return keyStore;
				}
				@Override
				public KeyStore getTrustStore() {
					return null;
				}
			});
		};
	}

Error log:

> Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Setting a custom URLStreamHandlerFactory.
>         at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:88) ~[?:?]
>         at java.net.URL.setURLStreamHandlerFactory(URL.java:85) ~[?:?]
>         at org.apache.catalina.webresources.TomcatURLStreamHandlerFactory.<init>(TomcatURLStreamHandlerFactory.java:130) ~[?:?]
>         at org.apache.catalina.webresources.TomcatURLStreamHandlerFactory.getInstanceInternal(TomcatURLStreamHandlerFactory.java:53) ~[?:?]
>         at org.apache.catalina.webresources.TomcatURLStreamHandlerFactory.getInstance(TomcatURLStreamHandlerFactory.java:43) ~[?:?]
>         at org.springframework.boot.web.embedded.tomcat.SslConnectorCustomizer.configureSslStoreProvider(SslConnectorCustomizer.java:110) ~[?:?]
>         at org.springframework.boot.web.embedded.tomcat.SslConnectorCustomizer.configureSsl(SslConnectorCustomizer.java:89) ~[?:?]
>         at org.springframework.boot.web.embedded.tomcat.SslConnectorCustomizer.customize(SslConnectorCustomizer.java:57) ~[?:?]
>         at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.customizeSsl(TomcatServletWebServerFactory.java:351) ~[MyApplication:2.5.3]
>         at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.customizeConnector(TomcatServletWebServerFactory.java:329) ~[MyApplication:2.5.3]
>         at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:191) ~[MyApplication:2.5.3]
>         at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:182) ~[?:?]
>         at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:160) ~[?:?]
>         ... 8 more
> 

Is there any way to support this? Does anyone know any sample setup / substitution to suggest to me?

**Comment by arielcarrera** [comment]
I think that it is related to [https://github.com/oracle/graal/issues/1721](https://github.com/oracle/graal/issues/1721)
