### ISSUE TITLE
micrometer percentiles throws NoSuchMethodException

### ISSUE THREAD

**Issue by gbrehmer** [spring-projects-experimental/spring-native#986]
If I enable http request percentiles each http call throws an exception:

```
management:
    metrics:
        distribution:
            percentiles:
                http.server.requests: 0.99, 0.95
```

```
java.lang.IllegalArgumentException: java.lang.NoSuchMethodException: org.HdrHistogram.Histogram.<init>(long, long, int)
	at org.HdrHistogram.DoubleHistogram.<init>(DoubleHistogram.java:220) ~[na:na]
	at org.HdrHistogram.DoubleHistogram.<init>(DoubleHistogram.java:141) ~[na:na]
	at org.HdrHistogram.DoubleHistogram.<init>(DoubleHistogram.java:77) ~[na:na]
	at io.micrometer.core.instrument.distribution.TimeWindowPercentileHistogram.<init>(TimeWindowPercentileHistogram.java:38) ~[na:na]
	at io.micrometer.core.instrument.AbstractTimer.<init>(AbstractTimer.java:85) ~[na:na]
	at io.micrometer.core.instrument.cumulative.CumulativeTimer.<init>(CumulativeTimer.java:43) ~[na:na]
	at io.micrometer.core.instrument.simple.SimpleMeterRegistry.newTimer(SimpleMeterRegistry.java:90) ~[wa48-mqtt-http-auth:1.7.2]
	at io.micrometer.core.instrument.MeterRegistry.lambda$timer$2(MeterRegistry.java:310) ~[wa48-mqtt-http-auth:1.7.2]
	at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:614) ~[wa48-mqtt-http-auth:1.7.2]
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:568) ~[wa48-mqtt-http-auth:1.7.2]
	at io.micrometer.core.instrument.MeterRegistry.timer(MeterRegistry.java:308) ~[wa48-mqtt-http-auth:1.7.2]
	at io.micrometer.core.instrument.Timer$Builder.register(Timer.java:403) ~[na:na]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.getTimer(WebMvcMetricsFilter.java:161) ~[na:na]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.lambda$record$0(WebMvcMetricsFilter.java:139) ~[na:na]
	at org.springframework.boot.actuate.metrics.AutoTimer.apply(AutoTimer.java:109) ~[wa48-mqtt-http-auth:2.5.3]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.record(WebMvcMetricsFilter.java:138) ~[na:na]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:103) ~[na:na]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[na:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) ~[na:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) ~[na:na]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[wa48-mqtt-http-auth:5.3.9]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[na:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) ~[na:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) ~[na:na]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[na:na]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[na:na]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[na:na]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) ~[na:na]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[wa48-mqtt-http-auth:9.0.50]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[na:na]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[na:na]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) ~[na:na]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[na:na]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) ~[na:na]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1723) ~[na:na]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[na:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[na:na]
	at java.lang.Thread.run(Thread.java:829) ~[na:na]
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:567) ~[na:na]
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192) ~[na:na]
Caused by: java.lang.NoSuchMethodException: org.HdrHistogram.Histogram.<init>(long, long, int)
	at java.lang.Class.getConstructor0(DynamicHub.java:3349) ~[na:na]
	at java.lang.Class.getConstructor(DynamicHub.java:2151) ~[na:na]
	at org.HdrHistogram.DoubleHistogram.<init>(DoubleHistogram.java:178) ~[na:na]
	... 41 common frames omitted
```

**Comment by mhalbritter** [comment]
Works with spring-native 0.12.0
