### ISSUE TITLE
NoSuchBeanDefinitionException

### ISSUE THREAD

**Issue by necipakca** [spring-projects-experimental/spring-native#987]
After I build image, I run to native-image and I get following stacktrace.
I have no idea why I get this.

'org.springframework.boot' version '2.5.3'
'org.springframework.experimental.aot' version '0.10.2'
'org.graalvm.buildtools.native' version '0.9.1'

nativeBuild {
	classpath("$buildDir/resources/aot", "$buildDir/classes/java/aot")
	mainClass = "a.b.SorguApplication";
	verbose = true
	buildArgs =[
			'-H:+ReportUnsupportedElementsAtRuntime',
			'-H:+ReportExceptionStackTraces',
			'--initialize-at-run-time=io.netty.handler.codec.compression.BrotliDecoder,io.netty.util.internal.logging.Log4JLogger',
			'--initialize-at-build-time=org.slf4j.MarkerFactory,org.apache.ibatis.logging.slf4j.Slf4jLocationAwareLoggerImpl,org.apache.ibatis.logging.LogFactory,org.apache.commons.logging.impl.SLF4JLocationAwareLog,org.slf4j.MDC,ch.qos.logback.classic.spi.ThrowableProxy,org.slf4j.impl.StaticLoggerBinder,org.slf4j.LoggerFactory,ch.qos.logback.classic.Logger,ch.qos.logback.core.spi.AppenderAttachableImpl,ch.qos.logback.core.status.StatusBase,ch.qos.logback.classic.Level,ch.qos.logback.core.status.InfoStatus,ch.qos.logback.classic.PatternLayout,ch.qos.logback.core.CoreConstants'
	]
}

Stack trace : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'auditCheckListNotUsed': Unsatisfied dependency expressed through field 'entityMapper'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'a.b.persistence.mapper.EntityMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired}
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:660)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1413)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:601)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
        at a.b.SorguApplication.main(SorguApplication.java:26)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'a.b.persistence.mapper.EntityMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired}
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1790)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1346)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:657)
        ... 20 common frames omitted

**Comment by sdeleuze** [comment]
Could you please provide a reproducer project?

**Comment by necipakca** [comment]
I can add debug log but unfortunately I can not provide reproduce project because It has complex configuration which is not easy to replicate. 
I hope debug log helps you.
Aslo I can provide any additional output you want.

[debug.log](https://github.com/spring-projects-experimental/spring-native/files/7022038/debug.log)

**Comment by sdeleuze** [comment]
Sorry but to be able to help we will really need a repro. Please reopen if you achieve to create a minimal reproducer.

**Comment by liuzhou12315** [comment]
the same problem
