### ISSUE TITLE
Add support for ImportAware on Configuration classes

### ISSUE THREAD

**Issue by snicoll** [spring-projects-experimental/spring-native#996]
When configuration classes are parsed at build time, `ConfigurationClassPostProcessor` honors two callbacks, see

https://github.com/spring-projects/spring-framework/blob/3c2dfebf4ec5e9d791c1f3c9fa0ad35a5a9fcd6b/spring-context/src/main/java/org/springframework/context/annotation/ConfigurationClassPostProcessor.java#L460-L489

Some classes required to be initialized again at runtime unfortunately, see `AbstractAsyncConfiguration`. This requires to load the ASM metadata of the class at runtime so dedicated entries in reflection config are likely to be necessary as well.

**Comment by snicoll** [comment]
This turns out to be a significant amount of work. It's not only the metadata of the class that's important, but also the class that imported it. At runtime, configuration class parsing keeps a stack of configuration classes and knows the chain of imports. 

Providing the metadata of `ProxyAsyncConfiguration` is not helping:

```
Caused by: java.lang.IllegalArgumentException: @EnableAsync is not present on importing class org.springframework.scheduling.annotation.ProxyAsyncConfiguration
	at org.springframework.scheduling.annotation.AbstractAsyncConfiguration.setImportMetadata(AbstractAsyncConfiguration.java:61)
	at org.springframework.aot.context.annotation.ImportAwareInvoker.setAnnotationMetadata(ImportAwareInvoker.java:29)
	at org.springframework.scheduling.annotation.ContextBootstrapInitializer.lambda$registerProxyAsyncConfiguration$1(ContextBootstrapInitializer.java:12)
	at org.springframework.aot.beans.factory.SmartFunction.apply(SmartFunction.java:18)
	at org.springframework.aot.beans.factory.BeanDefinitionRegistrar.lambda$instanceSupplier$0(BeanDefinitionRegistrar.java:69)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1231)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1173)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	... 36 more
```

That's because `@EnableAsync` is on a user-class that led `ProxyAsyncConfiguration` to be loaded. We need to keep that link so that we can read the relevant annotation metadata at runtime again.

**Comment by snicoll** [comment]
I've managed to make a basic sample work by writing down the structure of the bean factory at build time for the related import classes. I am not sure it'll work in all cases, typically when the same annotation is present on two different configuration classes.

**Comment by snicoll** [comment]
Closed by https://github.com/spring-projects-experimental/spring-native/commit/914bb211a11c906ab772a216c70168aa85c254e9
